--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/DiamondMemory/ui/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(31)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Scene:addChild(bg)

--Create woman_1
local woman_1 = cc.Sprite:create("game/DiamondMemory/ui/woman.png")
woman_1:setName("woman_1")
woman_1:setTag(34)
woman_1:setCascadeColorEnabled(true)
woman_1:setCascadeOpacityEnabled(true)
woman_1:setAnchorPoint(0.5000, 0.0000)
woman_1:setPosition(345.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(woman_1)
layout:setPositionPercentX(0.2695)
layout:setPercentWidth(0.5414)
layout:setPercentHeight(0.7903)
layout:setSize({width = 693.0000, height = 569.0000})
layout:setLeftMargin(-1.5000)
layout:setRightMargin(588.5000)
layout:setTopMargin(151.0000)
woman_1:setBlendFunc({src = 1, dst = 771})
Scene:addChild(woman_1)

--Create gamestartBtn
local gamestartBtn = ccui.Button:create()
gamestartBtn:ignoreContentAdaptWithSize(false)
gamestartBtn:loadTextureNormal("game/DiamondMemory/ui/btn.png",0)
gamestartBtn:setTitleFontName("game/DiamondMemory/ui/FZY3JW.TTF")
gamestartBtn:setTitleFontSize(40)
gamestartBtn:setTitleText("Start")
gamestartBtn:setTitleColor({r = 65, g = 65, b = 70})
gamestartBtn:setLayoutComponentEnabled(true)
gamestartBtn:setName("gamestartBtn")
gamestartBtn:setTag(5)
gamestartBtn:setCascadeColorEnabled(true)
gamestartBtn:setCascadeOpacityEnabled(true)
gamestartBtn:setPosition(799.1040, 292.6800)
gamestartBtn:setScaleX(1.5000)
gamestartBtn:setScaleY(1.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(gamestartBtn)
layout:setPositionPercentX(0.6243)
layout:setPositionPercentY(0.4065)
layout:setPercentWidth(0.1367)
layout:setPercentHeight(0.0972)
layout:setSize({width = 175.0000, height = 70.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(711.6040)
layout:setRightMargin(393.3960)
layout:setTopMargin(392.3200)
layout:setBottomMargin(257.6800)
Scene:addChild(gamestartBtn)

--Create aboutBtn
local aboutBtn = ccui.Button:create()
aboutBtn:ignoreContentAdaptWithSize(false)
aboutBtn:loadTextureNormal("Default/Button_Normal.png",0)
aboutBtn:setTitleFontSize(14)
aboutBtn:setTitleColor({r = 65, g = 65, b = 70})
aboutBtn:setLayoutComponentEnabled(true)
aboutBtn:setName("aboutBtn")
aboutBtn:setTag(6)
aboutBtn:setCascadeColorEnabled(true)
aboutBtn:setCascadeOpacityEnabled(true)
aboutBtn:setVisible(false)
aboutBtn:setPosition(62.7200, 322.2720)
aboutBtn:setScaleY(0.9400)
layout = ccui.LayoutComponent:bindLayoutComponent(aboutBtn)
layout:setPositionPercentX(0.0490)
layout:setPositionPercentY(0.4476)
layout:setPercentWidth(0.0773)
layout:setPercentHeight(0.1375)
layout:setSize({width = 99.0000, height = 99.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(13.2200)
layout:setRightMargin(1167.7800)
layout:setTopMargin(348.2280)
layout:setBottomMargin(272.7720)
Scene:addChild(aboutBtn)

--Create setBtn
local setBtn = ccui.Button:create()
setBtn:ignoreContentAdaptWithSize(false)
setBtn:loadTextureNormal("game/DiamondMemory/ui/btn_set.png",0)
setBtn:setTitleFontSize(14)
setBtn:setTitleColor({r = 65, g = 65, b = 70})
setBtn:setLayoutComponentEnabled(true)
setBtn:setName("setBtn")
setBtn:setTag(101)
setBtn:setCascadeColorEnabled(true)
setBtn:setCascadeOpacityEnabled(true)
setBtn:setPosition(108.8000, 638.5680)
setBtn:setScaleY(0.9400)
layout = ccui.LayoutComponent:bindLayoutComponent(setBtn)
layout:setPositionPercentX(0.0850)
layout:setPositionPercentY(0.8869)
layout:setPercentWidth(0.0664)
layout:setPercentHeight(0.1181)
layout:setSize({width = 85.0000, height = 85.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(66.3000)
layout:setRightMargin(1128.7000)
layout:setTopMargin(38.9320)
layout:setBottomMargin(596.0680)
Scene:addChild(setBtn)

--Create feedbackBtn
local feedbackBtn = ccui.Button:create()
feedbackBtn:ignoreContentAdaptWithSize(false)
feedbackBtn:loadTextureNormal("Default/Button_Normal.png",0)
feedbackBtn:setTitleFontSize(14)
feedbackBtn:setTitleColor({r = 65, g = 65, b = 70})
feedbackBtn:setLayoutComponentEnabled(true)
feedbackBtn:setName("feedbackBtn")
feedbackBtn:setTag(614)
feedbackBtn:setCascadeColorEnabled(true)
feedbackBtn:setCascadeOpacityEnabled(true)
feedbackBtn:setVisible(false)
feedbackBtn:setPosition(62.7200, 62.0640)
feedbackBtn:setScaleY(0.9400)
layout = ccui.LayoutComponent:bindLayoutComponent(feedbackBtn)
layout:setPositionPercentX(0.0490)
layout:setPositionPercentY(0.0862)
layout:setPercentWidth(0.0773)
layout:setPercentHeight(0.1375)
layout:setSize({width = 99.0000, height = 99.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(13.2200)
layout:setRightMargin(1167.7800)
layout:setTopMargin(608.4360)
layout:setBottomMargin(12.5640)
Scene:addChild(feedbackBtn)

--Create noticeBtn
local noticeBtn = ccui.Button:create()
noticeBtn:ignoreContentAdaptWithSize(false)
noticeBtn:loadTextureNormal("Default/Button_Normal.png",0)
noticeBtn:setTitleFontSize(14)
noticeBtn:setTitleColor({r = 65, g = 65, b = 70})
noticeBtn:setLayoutComponentEnabled(true)
noticeBtn:setName("noticeBtn")
noticeBtn:setTag(615)
noticeBtn:setCascadeColorEnabled(true)
noticeBtn:setCascadeOpacityEnabled(true)
noticeBtn:setVisible(false)
noticeBtn:setPosition(62.7200, 201.2400)
noticeBtn:setScaleY(0.9400)
layout = ccui.LayoutComponent:bindLayoutComponent(noticeBtn)
layout:setPositionPercentX(0.0490)
layout:setPositionPercentY(0.2795)
layout:setPercentWidth(0.0773)
layout:setPercentHeight(0.1375)
layout:setSize({width = 99.0000, height = 99.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(13.2200)
layout:setRightMargin(1167.7800)
layout:setTopMargin(469.2600)
layout:setBottomMargin(151.7400)
Scene:addChild(noticeBtn)

--Create ruleBtn
local ruleBtn = ccui.Button:create()
ruleBtn:ignoreContentAdaptWithSize(false)
ruleBtn:loadTextureNormal("game/DiamondMemory/ui/btn.png",0)
ruleBtn:setTitleFontName("game/DiamondMemory/ui/FZY3JW.TTF")
ruleBtn:setTitleFontSize(40)
ruleBtn:setTitleText("Rule")
ruleBtn:setTitleColor({r = 65, g = 65, b = 70})
ruleBtn:setLayoutComponentEnabled(true)
ruleBtn:setName("ruleBtn")
ruleBtn:setTag(33)
ruleBtn:setCascadeColorEnabled(true)
ruleBtn:setCascadeOpacityEnabled(true)
ruleBtn:setVisible(false)
ruleBtn:setPosition(1092.9920, 315.6480)
ruleBtn:setScaleX(1.5000)
ruleBtn:setScaleY(1.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(ruleBtn)
layout:setPositionPercentX(0.8539)
layout:setPositionPercentY(0.4384)
layout:setPercentWidth(0.1367)
layout:setPercentHeight(0.0972)
layout:setSize({width = 175.0000, height = 70.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(1005.4920)
layout:setRightMargin(99.5079)
layout:setTopMargin(369.3520)
layout:setBottomMargin(280.6480)
Scene:addChild(ruleBtn)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("game/DiamondMemory/ui/add_left.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(43)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setAnchorPoint(0.0000, 1.0000)
Image_2:setPosition(2.1608, 717.8010)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.0017)
layout:setPositionPercentY(0.9969)
layout:setPercentWidth(0.4055)
layout:setPercentHeight(0.9958)
layout:setSize({width = 519.0000, height = 717.0000})
layout:setLeftMargin(2.1608)
layout:setRightMargin(758.8392)
layout:setTopMargin(2.1990)
layout:setBottomMargin(0.8010)
Scene:addChild(Image_2)

--Create best
local best = ccui.Text:create()
best:ignoreContentAdaptWithSize(true)
best:setTextAreaSize({width = 0, height = 0})
best:setFontName("game/DiamondMemory/ui/FZY3JW.TTF")
best:setFontSize(40)
best:setString([[BEST:100]])
best:setLayoutComponentEnabled(true)
best:setName("best")
best:setTag(54)
best:setCascadeColorEnabled(true)
best:setCascadeOpacityEnabled(true)
best:setPosition(733.0000, 593.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(best)
layout:setPositionPercentX(0.5727)
layout:setPositionPercentY(0.8243)
layout:setPercentWidth(0.1367)
layout:setPercentHeight(0.0653)
layout:setSize({width = 175.0000, height = 47.0000})
layout:setLeftMargin(645.5000)
layout:setRightMargin(459.5000)
layout:setTopMargin(103.0000)
layout:setBottomMargin(570.0000)
Scene:addChild(best)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

