--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 150, g = 200, b = 255})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(19)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(Panel_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game/huangcheng/image/gameover.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(20)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(640.0000, 552.5485)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7674)
layout:setPercentWidth(0.3906)
layout:setPercentHeight(0.1958)
layout:setSize({width = 500.0000, height = 141.0000})
layout:setLeftMargin(390.0000)
layout:setRightMargin(390.0000)
layout:setTopMargin(96.9515)
layout:setBottomMargin(482.0485)
Panel_1:addChild(Image_1)

--Create Text
local Text = ccui.Text:create()
Text:ignoreContentAdaptWithSize(true)
Text:setTextAreaSize({width = 0, height = 0})
Text:setFontName("game/huangcheng/button/nvpk.ttf")
Text:setFontSize(48)
Text:setString([[本局得分：0]])
Text:setLayoutComponentEnabled(true)
Text:setName("Text")
Text:setTag(21)
Text:setCascadeColorEnabled(true)
Text:setCascadeOpacityEnabled(true)
Text:setPosition(639.9994, 336.6125)
Text:setTextColor({r = 255, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4675)
layout:setPercentWidth(0.2094)
layout:setPercentHeight(0.0806)
layout:setSize({width = 268.0000, height = 58.0000})
layout:setLeftMargin(505.9994)
layout:setRightMargin(506.0006)
layout:setTopMargin(354.3875)
layout:setBottomMargin(307.6125)
Panel_1:addChild(Text)

--Create zhuye
local zhuye = ccui.Button:create()
zhuye:ignoreContentAdaptWithSize(false)
zhuye:loadTextureNormal("game/huangcheng/button/zhuye_1.png",0)
zhuye:loadTexturePressed("game/huangcheng/button/zhuye_2.png",0)
zhuye:loadTextureDisabled("Default/Button_Disable.png",0)
zhuye:setTitleFontSize(14)
zhuye:setTitleColor({r = 65, g = 65, b = 70})
zhuye:setScale9Enabled(true)
zhuye:setCapInsets({x = 15, y = 11, width = 58, height = 69})
zhuye:setLayoutComponentEnabled(true)
zhuye:setName("zhuye")
zhuye:setTag(22)
zhuye:setCascadeColorEnabled(true)
zhuye:setCascadeOpacityEnabled(true)
zhuye:setPosition(640.0000, 185.6314)
layout = ccui.LayoutComponent:bindLayoutComponent(zhuye)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2578)
layout:setPercentWidth(0.0688)
layout:setPercentHeight(0.1264)
layout:setSize({width = 88.0000, height = 91.0000})
layout:setLeftMargin(596.0000)
layout:setRightMargin(596.0000)
layout:setTopMargin(488.8686)
layout:setBottomMargin(140.1314)
Panel_1:addChild(zhuye)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

