--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game/knight/images/bg.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(31)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Scene:addChild(Image_1)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("game/knight/images/role.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(64)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setAnchorPoint(0.5000, 0.0000)
Image_2:setPosition(516.8556, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.7179)
layout:setPercentWidth(0.7361)
layout:setPercentHeight(0.4141)
layout:setSize({width = 530.0000, height = 530.0000})
layout:setLeftMargin(251.8556)
layout:setRightMargin(-61.8556)
layout:setTopMargin(750.0000)
Scene:addChild(Image_2)

--Create gamestartBtn
local gamestartBtn = ccui.Button:create()
gamestartBtn:ignoreContentAdaptWithSize(false)
gamestartBtn:loadTextureNormal("game/knight/images/btn.png",0)
gamestartBtn:setTitleFontName("game/knight/images/font.ttf")
gamestartBtn:setTitleFontSize(36)
gamestartBtn:setTitleText("play")
gamestartBtn:setTitleColor({r = 229, g = 229, b = 229})
gamestartBtn:setLayoutComponentEnabled(true)
gamestartBtn:setName("gamestartBtn")
gamestartBtn:setTag(5)
gamestartBtn:setCascadeColorEnabled(true)
gamestartBtn:setCascadeOpacityEnabled(true)
gamestartBtn:setPosition(244.1434, 588.2338)
layout = ccui.LayoutComponent:bindLayoutComponent(gamestartBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.3391)
layout:setPositionPercentY(0.4596)
layout:setPercentWidth(0.2778)
layout:setPercentHeight(0.0547)
layout:setSize({width = 200.0000, height = 70.0000})
layout:setVerticalEdge(3)
layout:setLeftMargin(144.1434)
layout:setRightMargin(375.8566)
layout:setTopMargin(656.7662)
layout:setBottomMargin(553.2338)
Scene:addChild(gamestartBtn)

--Create ruleBtn
local ruleBtn = ccui.Button:create()
ruleBtn:ignoreContentAdaptWithSize(false)
ruleBtn:loadTextureNormal("game/knight/images/btn.png",0)
ruleBtn:setTitleFontName("game/knight/images/font.ttf")
ruleBtn:setTitleFontSize(36)
ruleBtn:setTitleText("help")
ruleBtn:setLayoutComponentEnabled(true)
ruleBtn:setName("ruleBtn")
ruleBtn:setTag(6)
ruleBtn:setCascadeColorEnabled(true)
ruleBtn:setCascadeOpacityEnabled(true)
ruleBtn:setPosition(244.5752, 437.3219)
layout = ccui.LayoutComponent:bindLayoutComponent(ruleBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3397)
layout:setPositionPercentY(0.3417)
layout:setPercentWidth(0.2778)
layout:setPercentHeight(0.0547)
layout:setSize({width = 200.0000, height = 70.0000})
layout:setLeftMargin(144.5752)
layout:setRightMargin(375.4248)
layout:setTopMargin(807.6781)
layout:setBottomMargin(402.3219)
Scene:addChild(ruleBtn)

--Create setBtn
local setBtn = ccui.Button:create()
setBtn:ignoreContentAdaptWithSize(false)
setBtn:loadTextureNormal("game/knight/images/btn_set.png",0)
setBtn:setTitleFontSize(14)
setBtn:setTitleColor({r = 65, g = 65, b = 70})
setBtn:setLayoutComponentEnabled(true)
setBtn:setName("setBtn")
setBtn:setTag(46)
setBtn:setCascadeColorEnabled(true)
setBtn:setCascadeOpacityEnabled(true)
setBtn:setPosition(95.1990, 1186.3020)
setBtn:setScaleY(0.9400)
layout = ccui.LayoutComponent:bindLayoutComponent(setBtn)
layout:setPositionPercentX(0.1322)
layout:setPositionPercentY(0.9268)
layout:setPercentWidth(0.1264)
layout:setPercentHeight(0.0734)
layout:setSize({width = 91.0000, height = 94.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(49.6990)
layout:setRightMargin(579.3010)
layout:setTopMargin(46.6975)
layout:setBottomMargin(1139.3020)
Scene:addChild(setBtn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

