--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create levelpnl
local levelpnl = ccui.Layout:create()
levelpnl:ignoreContentAdaptWithSize(false)
levelpnl:setBackGroundImage("game/cattleRun/image/level_1.png",0)
levelpnl:setClippingEnabled(false)
levelpnl:setBackGroundColorOpacity(102)
levelpnl:setTouchEnabled(true);
levelpnl:setLayoutComponentEnabled(true)
levelpnl:setName("levelpnl")
levelpnl:setTag(58)
levelpnl:setCascadeColorEnabled(true)
levelpnl:setCascadeOpacityEnabled(true)
levelpnl:setPosition(440.0000, 212.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(levelpnl)
layout:setPositionPercentX(0.3438)
layout:setPositionPercentY(0.2951)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.5556)
layout:setSize({width = 400.0000, height = 400.0000})
layout:setLeftMargin(440.0000)
layout:setRightMargin(440.0000)
layout:setTopMargin(107.5000)
layout:setBottomMargin(212.5000)
Layer:addChild(levelpnl)

--Create duigou
local duigou = ccui.ImageView:create()
duigou:ignoreContentAdaptWithSize(false)
duigou:loadTexture("game/cattleRun/image/zhengque.png",0)
duigou:setLayoutComponentEnabled(true)
duigou:setName("duigou")
duigou:setTag(76)
duigou:setCascadeColorEnabled(true)
duigou:setCascadeOpacityEnabled(true)
duigou:setPosition(198.0000, 190.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(duigou)
layout:setPositionPercentX(0.4950)
layout:setPositionPercentY(0.4750)
layout:setPercentWidth(0.3075)
layout:setPercentHeight(0.3375)
layout:setSize({width = 123.0000, height = 135.0000})
layout:setLeftMargin(136.5000)
layout:setRightMargin(140.5000)
layout:setTopMargin(142.5000)
layout:setBottomMargin(122.5000)
levelpnl:addChild(duigou)

--Create wrong
local wrong = ccui.ImageView:create()
wrong:ignoreContentAdaptWithSize(false)
wrong:loadTexture("game/cattleRun/image/cuowu.png",0)
wrong:setLayoutComponentEnabled(true)
wrong:setName("wrong")
wrong:setTag(77)
wrong:setCascadeColorEnabled(true)
wrong:setCascadeOpacityEnabled(true)
wrong:setPosition(198.0000, 190.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(wrong)
layout:setPositionPercentX(0.4950)
layout:setPositionPercentY(0.4750)
layout:setPercentWidth(0.2375)
layout:setPercentHeight(0.2425)
layout:setSize({width = 95.0000, height = 97.0000})
layout:setLeftMargin(150.5000)
layout:setRightMargin(154.5000)
layout:setTopMargin(161.5000)
layout:setBottomMargin(141.5000)
levelpnl:addChild(wrong)

--Create content
local content = ccui.Layout:create()
content:ignoreContentAdaptWithSize(false)
content:setClippingEnabled(false)
content:setBackGroundColorOpacity(102)
content:setTouchEnabled(true);
content:setLayoutComponentEnabled(true)
content:setName("content")
content:setTag(75)
content:setCascadeColorEnabled(true)
content:setCascadeOpacityEnabled(true)
content:setPosition(99.0000, 110.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(content)
layout:setPositionPercentX(0.2475)
layout:setPositionPercentY(0.2750)
layout:setPercentWidth(0.5000)
layout:setPercentHeight(0.3925)
layout:setSize({width = 200.0000, height = 157.0000})
layout:setLeftMargin(99.0000)
layout:setRightMargin(101.0000)
layout:setTopMargin(133.0000)
layout:setBottomMargin(110.0000)
levelpnl:addChild(content)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

