--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setBackGroundImage("",0)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(145)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setPosition(248.9400, 120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.1945)
layout:setPositionPercentY(0.1667)
layout:setPercentWidth(0.6250)
layout:setPercentHeight(0.6944)
layout:setSize({width = 800.0000, height = 500.0000})
layout:setLeftMargin(248.9400)
layout:setRightMargin(231.0601)
layout:setTopMargin(100.0000)
layout:setBottomMargin(120.0000)
Layer:addChild(Panel_1)

--Create replay
local replay = ccui.Button:create()
replay:ignoreContentAdaptWithSize(false)
replay:loadTextureNormal("Default/Button_Normal.png",0)
replay:setTitleFontSize(14)
replay:setTitleColor({r = 65, g = 65, b = 70})
replay:setScale9Enabled(true)
replay:setCapInsets({x = 15, y = 11, width = 226, height = 75})
replay:setLayoutComponentEnabled(true)
replay:setName("replay")
replay:setTag(150)
replay:setCascadeColorEnabled(true)
replay:setCascadeOpacityEnabled(true)
replay:setPosition(237.1181, 102.9153)
layout = ccui.LayoutComponent:bindLayoutComponent(replay)
layout:setPositionPercentX(0.2964)
layout:setPositionPercentY(0.2058)
layout:setPercentWidth(0.3200)
layout:setPercentHeight(0.1940)
layout:setSize({width = 256.0000, height = 97.0000})
layout:setLeftMargin(109.1181)
layout:setRightMargin(434.8819)
layout:setTopMargin(348.5847)
layout:setBottomMargin(54.4153)
Panel_1:addChild(replay)

--Create home
local home = ccui.Button:create()
home:ignoreContentAdaptWithSize(false)
home:loadTextureNormal("Default/Button_Normal.png",0)
home:setTitleFontSize(14)
home:setTitleColor({r = 65, g = 65, b = 70})
home:setScale9Enabled(true)
home:setCapInsets({x = 15, y = 11, width = 223, height = 73})
home:setLayoutComponentEnabled(true)
home:setName("home")
home:setTag(151)
home:setCascadeColorEnabled(true)
home:setCascadeOpacityEnabled(true)
home:setPosition(592.6005, 102.9153)
layout = ccui.LayoutComponent:bindLayoutComponent(home)
layout:setPositionPercentX(0.7408)
layout:setPositionPercentY(0.2058)
layout:setPercentWidth(0.3162)
layout:setPercentHeight(0.1900)
layout:setSize({width = 253.0000, height = 95.0000})
layout:setLeftMargin(466.1005)
layout:setRightMargin(80.8995)
layout:setTopMargin(349.5847)
layout:setBottomMargin(55.4153)
Panel_1:addChild(home)

--Create GameOver_1
local GameOver_1 = cc.Sprite:create("Default/Sprite.png")
GameOver_1:setName("GameOver_1")
GameOver_1:setTag(146)
GameOver_1:setCascadeColorEnabled(true)
GameOver_1:setCascadeOpacityEnabled(true)
GameOver_1:setPosition(659.2722, 544.6311)
layout = ccui.LayoutComponent:bindLayoutComponent(GameOver_1)
layout:setPositionPercentX(0.5151)
layout:setPositionPercentY(0.7564)
layout:setPercentWidth(0.2891)
layout:setPercentHeight(0.0667)
layout:setSize({width = 370.0000, height = 48.0000})
layout:setLeftMargin(474.2722)
layout:setRightMargin(435.7278)
layout:setTopMargin(151.3689)
layout:setBottomMargin(520.6311)
GameOver_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(GameOver_1)

--Create High__2
local High__2 = cc.Sprite:create("Default/Sprite.png")
High__2:setName("High__2")
High__2:setTag(147)
High__2:setCascadeColorEnabled(true)
High__2:setCascadeOpacityEnabled(true)
High__2:setPosition(659.2722, 342.8657)
layout = ccui.LayoutComponent:bindLayoutComponent(High__2)
layout:setPositionPercentX(0.5151)
layout:setPositionPercentY(0.4762)
layout:setPercentWidth(0.2305)
layout:setPercentHeight(0.1292)
layout:setSize({width = 295.0000, height = 93.0000})
layout:setLeftMargin(511.7722)
layout:setRightMargin(473.2278)
layout:setTopMargin(330.6343)
layout:setBottomMargin(296.3657)
High__2:setBlendFunc({src = 1, dst = 771})
Layer:addChild(High__2)

--Create Socer__4
local Socer__4 = cc.Sprite:create("Default/Sprite.png")
Socer__4:setName("Socer__4")
Socer__4:setTag(149)
Socer__4:setCascadeColorEnabled(true)
Socer__4:setCascadeOpacityEnabled(true)
Socer__4:setPosition(659.2722, 433.5127)
layout = ccui.LayoutComponent:bindLayoutComponent(Socer__4)
layout:setPositionPercentX(0.5151)
layout:setPositionPercentY(0.6021)
layout:setPercentWidth(0.2305)
layout:setPercentHeight(0.1292)
layout:setSize({width = 295.0000, height = 93.0000})
layout:setLeftMargin(511.7722)
layout:setRightMargin(473.2278)
layout:setTopMargin(239.9873)
layout:setBottomMargin(387.0127)
Socer__4:setBlendFunc({src = 1, dst = 771})
Layer:addChild(Socer__4)

--Create score
local score = ccui.Text:create()
score:ignoreContentAdaptWithSize(true)
score:setTextAreaSize({width = 0, height = 0})
score:setFontSize(24)
score:setString([[50000]])
score:setTextHorizontalAlignment(1)
score:setTextVerticalAlignment(1)
score:setLayoutComponentEnabled(true)
score:setName("score")
score:setTag(152)
score:setCascadeColorEnabled(true)
score:setCascadeOpacityEnabled(true)
score:setAnchorPoint(0.0000, 0.5000)
score:setPosition(643.0374, 436.9036)
score:setTextColor({r = 0, g = 128, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(score)
layout:setPositionPercentX(0.5024)
layout:setPositionPercentY(0.6068)
layout:setPercentWidth(0.0523)
layout:setPercentHeight(0.0389)
layout:setSize({width = 67.0000, height = 28.0000})
layout:setLeftMargin(643.0374)
layout:setRightMargin(569.9626)
layout:setTopMargin(269.0964)
layout:setBottomMargin(422.9036)
Layer:addChild(score)

--Create high
local high = ccui.Text:create()
high:ignoreContentAdaptWithSize(true)
high:setTextAreaSize({width = 0, height = 0})
high:setFontSize(24)
high:setString([[60000]])
high:setTextHorizontalAlignment(1)
high:setTextVerticalAlignment(1)
high:setLayoutComponentEnabled(true)
high:setName("high")
high:setTag(153)
high:setCascadeColorEnabled(true)
high:setCascadeOpacityEnabled(true)
high:setAnchorPoint(0.0000, 0.5000)
high:setPosition(643.0374, 344.1424)
high:setTextColor({r = 0, g = 128, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(high)
layout:setPositionPercentX(0.5024)
layout:setPositionPercentY(0.4780)
layout:setPercentWidth(0.0523)
layout:setPercentHeight(0.0389)
layout:setSize({width = 67.0000, height = 28.0000})
layout:setLeftMargin(643.0374)
layout:setRightMargin(569.9626)
layout:setTopMargin(361.8576)
layout:setBottomMargin(330.1424)
Layer:addChild(high)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

