--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create gameBg
local gameBg = cc.Sprite:create("game/FarmerfFightLandlord/image/bg.png")
gameBg:setName("gameBg")
gameBg:setTag(41)
gameBg:setCascadeColorEnabled(true)
gameBg:setCascadeOpacityEnabled(true)
gameBg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(gameBg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
gameBg:setBlendFunc({src = 1, dst = 771})
Scene:addChild(gameBg)

--Create landlordPool
local landlordPool = ccui.Layout:create()
landlordPool:ignoreContentAdaptWithSize(false)
landlordPool:setClippingEnabled(false)
landlordPool:setLayoutComponentEnabled(true)
landlordPool:setName("landlordPool")
landlordPool:setTag(40)
landlordPool:setCascadeColorEnabled(true)
landlordPool:setCascadeOpacityEnabled(true)
landlordPool:setAnchorPoint(0.5000, 0.5000)
landlordPool:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(landlordPool)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Scene:addChild(landlordPool)

--Create armsPool
local armsPool = ccui.Layout:create()
armsPool:ignoreContentAdaptWithSize(false)
armsPool:setClippingEnabled(false)
armsPool:setBackGroundColorOpacity(102)
armsPool:setLayoutComponentEnabled(true)
armsPool:setName("armsPool")
armsPool:setTag(47)
armsPool:setCascadeColorEnabled(true)
armsPool:setCascadeOpacityEnabled(true)
armsPool:setAnchorPoint(0.5000, 0.5000)
armsPool:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(armsPool)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Scene:addChild(armsPool)

--Create farmer
local farmer = ccui.ImageView:create()
farmer:ignoreContentAdaptWithSize(false)
farmer:loadTexture("game/FarmerfFightLandlord/image/farmer.png",0)
farmer:setLayoutComponentEnabled(true)
farmer:setName("farmer")
farmer:setTag(39)
farmer:setCascadeColorEnabled(true)
farmer:setCascadeOpacityEnabled(true)
farmer:setPosition(360.0000, 170.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(farmer)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1328)
layout:setPercentWidth(0.1681)
layout:setPercentHeight(0.1445)
layout:setSize({width = 121.0000, height = 185.0000})
layout:setLeftMargin(299.5000)
layout:setRightMargin(299.5000)
layout:setTopMargin(1017.5000)
layout:setBottomMargin(77.5000)
Scene:addChild(farmer)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

