--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create shade
local shade = ccui.Layout:create()
shade:ignoreContentAdaptWithSize(false)
shade:setClippingEnabled(false)
shade:setBackGroundColorType(1)
shade:setBackGroundColor({r = 0, g = 0, b = 0})
shade:setBackGroundColorOpacity(204)
shade:setTouchEnabled(true);
shade:setLayoutComponentEnabled(true)
shade:setName("shade")
shade:setTag(93)
shade:setCascadeColorEnabled(true)
shade:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(shade)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(shade)

--Create TopPanel
local TopPanel = ccui.Layout:create()
TopPanel:ignoreContentAdaptWithSize(false)
TopPanel:setClippingEnabled(false)
TopPanel:setBackGroundColorOpacity(102)
TopPanel:setTouchEnabled(true);
TopPanel:setLayoutComponentEnabled(true)
TopPanel:setName("TopPanel")
TopPanel:setTag(78)
TopPanel:setCascadeColorEnabled(true)
TopPanel:setCascadeOpacityEnabled(true)
TopPanel:setAnchorPoint(0.5000, 0.5000)
TopPanel:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TopPanel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.8403)
layout:setPercentHeight(0.3359)
layout:setSize({width = 605.0000, height = 430.0000})
layout:setLeftMargin(57.5000)
layout:setRightMargin(57.5000)
layout:setTopMargin(425.0000)
layout:setBottomMargin(425.0000)
Layer:addChild(TopPanel)

--Create winbg
local winbg = ccui.ImageView:create()
winbg:ignoreContentAdaptWithSize(false)
winbg:loadTexture("game/FarmerfFightLandlord/image/popbg.png",0)
winbg:setLayoutComponentEnabled(true)
winbg:setName("winbg")
winbg:setTag(80)
winbg:setCascadeColorEnabled(true)
winbg:setCascadeOpacityEnabled(true)
winbg:setPosition(302.5000, 214.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(winbg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4977)
layout:setPercentWidth(0.9785)
layout:setPercentHeight(1.2000)
layout:setSize({width = 592.0000, height = 516.0000})
layout:setLeftMargin(6.5000)
layout:setRightMargin(6.5000)
layout:setTopMargin(-42.0000)
layout:setBottomMargin(-44.0000)
TopPanel:addChild(winbg)

--Create closeBtn
local closeBtn = ccui.Button:create()
closeBtn:ignoreContentAdaptWithSize(false)
closeBtn:loadTextureNormal("game/FarmerfFightLandlord/image/clone.png",0)
closeBtn:setTitleFontName("game/FarmerfFightLandlord/image/nvpk.ttf")
closeBtn:setTitleFontSize(14)
closeBtn:setTitleColor({r = 65, g = 65, b = 70})
closeBtn:setLayoutComponentEnabled(true)
closeBtn:setName("closeBtn")
closeBtn:setTag(81)
closeBtn:setCascadeColorEnabled(true)
closeBtn:setCascadeOpacityEnabled(true)
closeBtn:setPosition(574.0240, 414.6060)
layout = ccui.LayoutComponent:bindLayoutComponent(closeBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9488)
layout:setPositionPercentY(0.9642)
layout:setPercentWidth(0.1355)
layout:setPercentHeight(0.2000)
layout:setSize({width = 82.0000, height = 86.0000})
layout:setLeftMargin(533.0240)
layout:setRightMargin(-10.0240)
layout:setTopMargin(-27.6060)
layout:setBottomMargin(371.6060)
TopPanel:addChild(closeBtn)

--Create ruleScrollView
local ruleScrollView = ccui.ScrollView:create()
ruleScrollView:setBounceEnabled(true)
ruleScrollView:setInnerContainerSize({width = 490, height = 500})
ruleScrollView:ignoreContentAdaptWithSize(false)
ruleScrollView:setClippingEnabled(true)
ruleScrollView:setBackGroundColorOpacity(102)
ruleScrollView:setLayoutComponentEnabled(true)
ruleScrollView:setName("ruleScrollView")
ruleScrollView:setTag(115)
ruleScrollView:setCascadeColorEnabled(true)
ruleScrollView:setCascadeOpacityEnabled(true)
ruleScrollView:setPosition(55.8316, 16.4559)
layout = ccui.LayoutComponent:bindLayoutComponent(ruleScrollView)
layout:setPositionPercentX(0.0923)
layout:setPositionPercentY(0.0383)
layout:setPercentWidth(0.8099)
layout:setPercentHeight(0.9302)
layout:setSize({width = 490.0000, height = 400.0000})
layout:setLeftMargin(55.8316)
layout:setRightMargin(59.1684)
layout:setTopMargin(13.5441)
layout:setBottomMargin(16.4559)
TopPanel:addChild(ruleScrollView)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(false)
Text_1:setFontName("game/FarmerfFightLandlord/image/nvpk.ttf")
Text_1:setFontSize(30)
Text_1:setString([[The landlord moves down from the top of the screen. The farmer is at the bottom of the screen. Click the screen and drag to control the landlord to move left and right. The farmer will throw weapons to attack the landlord. When the local landlord encounters the farmer, the game ends.]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(116)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(245.9303, 244.1228)
Text_1:setTextColor({r = 0, g = 128, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.5019)
layout:setPositionPercentY(0.4882)
layout:setPercentWidth(0.9592)
layout:setPercentHeight(1.0000)
layout:setSize({width = 470.0000, height = 500.0000})
layout:setLeftMargin(10.9303)
layout:setRightMargin(9.0697)
layout:setTopMargin(5.8772)
layout:setBottomMargin(-5.8772)
ruleScrollView:addChild(Text_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

