--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg
local bg = cc.Sprite:create("game/Basketball/image/bg.png")
bg:setName("bg")
bg:setTag(38)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
bg:setBlendFunc({src = 1, dst = 771})
Scene:addChild(bg)

--Create ball
local ball = ccui.ImageView:create()
ball:ignoreContentAdaptWithSize(false)
ball:loadTexture("game/Basketball/image/logo.png",0)
ball:setLayoutComponentEnabled(true)
ball:setName("ball")
ball:setTag(9)
ball:setCascadeColorEnabled(true)
ball:setCascadeOpacityEnabled(true)
ball:setAnchorPoint(0.5000, 0.0000)
ball:setPosition(323.0000, 0.6572)
layout = ccui.LayoutComponent:bindLayoutComponent(ball)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.2523)
layout:setPositionPercentY(0.0009)
layout:setPercentWidth(0.2422)
layout:setPercentHeight(0.8500)
layout:setSize({width = 310.0000, height = 612.0000})
layout:setLeftMargin(168.0000)
layout:setRightMargin(802.0000)
layout:setTopMargin(107.3428)
layout:setBottomMargin(0.6572)
Scene:addChild(ball)

--Create startBtn
local startBtn = ccui.Button:create()
startBtn:ignoreContentAdaptWithSize(false)
startBtn:loadTextureNormal("game/Basketball/image/button.png",0)
startBtn:setTitleFontName("game/Basketball/image/a.ttf")
startBtn:setTitleFontSize(60)
startBtn:setTitleText("开始游戏")
startBtn:setLayoutComponentEnabled(true)
startBtn:setName("startBtn")
startBtn:setTag(289)
startBtn:setCascadeColorEnabled(true)
startBtn:setCascadeOpacityEnabled(true)
startBtn:setPosition(815.2400, 141.6442)
layout = ccui.LayoutComponent:bindLayoutComponent(startBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.6369)
layout:setPositionPercentY(0.1967)
layout:setPercentWidth(0.2781)
layout:setPercentHeight(0.1611)
layout:setSize({width = 356.0000, height = 116.0000})
layout:setLeftMargin(637.2400)
layout:setRightMargin(286.7600)
layout:setTopMargin(520.3558)
layout:setBottomMargin(83.6442)
Scene:addChild(startBtn)

--Create ruleBtn
local ruleBtn = ccui.Button:create()
ruleBtn:ignoreContentAdaptWithSize(false)
ruleBtn:loadTextureNormal("game/Basketball/image/button.png",0)
ruleBtn:setTitleFontName("game/Basketball/image/a.ttf")
ruleBtn:setTitleFontSize(60)
ruleBtn:setTitleText("Rule")
ruleBtn:setLayoutComponentEnabled(true)
ruleBtn:setName("ruleBtn")
ruleBtn:setTag(33)
ruleBtn:setCascadeColorEnabled(true)
ruleBtn:setCascadeOpacityEnabled(true)
ruleBtn:setVisible(false)
ruleBtn:setPosition(852.2240, 183.3042)
layout = ccui.LayoutComponent:bindLayoutComponent(ruleBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.6658)
layout:setPositionPercentY(0.2546)
layout:setPercentWidth(0.2781)
layout:setPercentHeight(0.1611)
layout:setSize({width = 356.0000, height = 116.0000})
layout:setLeftMargin(674.2240)
layout:setRightMargin(249.7760)
layout:setTopMargin(478.6958)
layout:setBottomMargin(125.3042)
Scene:addChild(ruleBtn)

--Create scoreLabel
local scoreLabel = ccui.Text:create()
scoreLabel:ignoreContentAdaptWithSize(true)
scoreLabel:setTextAreaSize({width = 0, height = 0})
scoreLabel:setFontName("game/Basketball/image/a.ttf")
scoreLabel:setFontSize(48)
scoreLabel:setString([[最高分：0]])
scoreLabel:setLayoutComponentEnabled(true)
scoreLabel:setName("scoreLabel")
scoreLabel:setTag(34)
scoreLabel:setCascadeColorEnabled(true)
scoreLabel:setCascadeOpacityEnabled(true)
scoreLabel:setPosition(526.9993, 1200.3870)
layout = ccui.LayoutComponent:bindLayoutComponent(scoreLabel)
layout:setPositionPercentX(0.4117)
layout:setPositionPercentY(1.6672)
layout:setPercentWidth(0.1719)
layout:setPercentHeight(0.0806)
layout:setSize({width = 220.0000, height = 58.0000})
layout:setLeftMargin(416.9993)
layout:setRightMargin(643.0007)
layout:setTopMargin(-509.3873)
layout:setBottomMargin(1171.3870)
Scene:addChild(scoreLabel)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

