--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/GuardCastle/images/game/gamebg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(32)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setVerticalEdge(3)
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Scene:addChild(bg)

--Create killBg
local killBg = ccui.ImageView:create()
killBg:ignoreContentAdaptWithSize(false)
killBg:loadTexture("game/GuardCastle/images/game/ghost.png",0)
killBg:setLayoutComponentEnabled(true)
killBg:setName("killBg")
killBg:setTag(29)
killBg:setCascadeColorEnabled(true)
killBg:setCascadeOpacityEnabled(true)
killBg:setPosition(92.9993, 623.4999)
layout = ccui.LayoutComponent:bindLayoutComponent(killBg)
layout:setPositionPercentX(0.0727)
layout:setPositionPercentY(0.8660)
layout:setPercentWidth(0.0438)
layout:setPercentHeight(0.0778)
layout:setSize({width = 56.0000, height = 56.0000})
layout:setLeftMargin(64.9993)
layout:setRightMargin(1159.0010)
layout:setTopMargin(68.5001)
layout:setBottomMargin(595.4999)
Scene:addChild(killBg)

--Create timeText
local timeText = ccui.Text:create()
timeText:ignoreContentAdaptWithSize(true)
timeText:setTextAreaSize({width = 0, height = 0})
timeText:setFontName("game/GuardCastle/images/font/font.ttf")
timeText:setFontSize(60)
timeText:setString([[Time: 0]])
timeText:enableOutline({r = 71, g = 34, b = 14, a = 255}, 2)
timeText:setLayoutComponentEnabled(true)
timeText:setName("timeText")
timeText:setTag(34)
timeText:setCascadeColorEnabled(true)
timeText:setCascadeOpacityEnabled(true)
timeText:setPosition(632.9600, 669.0240)
timeText:setTextColor({r = 251, g = 231, b = 81})
layout = ccui.LayoutComponent:bindLayoutComponent(timeText)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4945)
layout:setPositionPercentY(0.9292)
layout:setPercentWidth(0.2055)
layout:setPercentHeight(0.1097)
layout:setSize({width = 263.0000, height = 79.0000})
layout:setLeftMargin(501.4600)
layout:setRightMargin(515.5400)
layout:setTopMargin(11.4760)
layout:setBottomMargin(629.5240)
Scene:addChild(timeText)

--Create scoreText
local scoreText = ccui.Text:create()
scoreText:ignoreContentAdaptWithSize(true)
scoreText:setTextAreaSize({width = 0, height = 0})
scoreText:setFontName("game/GuardCastle/images/font/font.ttf")
scoreText:setFontSize(30)
scoreText:setString([[X 0]])
scoreText:enableOutline({r = 71, g = 34, b = 14, a = 255}, 1)
scoreText:setLayoutComponentEnabled(true)
scoreText:setName("scoreText")
scoreText:setTag(34)
scoreText:setCascadeColorEnabled(true)
scoreText:setCascadeOpacityEnabled(true)
scoreText:setAnchorPoint(0.0000, 0.5000)
scoreText:setPosition(142.0000, 623.5000)
scoreText:setTextColor({r = 251, g = 231, b = 81})
layout = ccui.LayoutComponent:bindLayoutComponent(scoreText)
layout:setPositionPercentX(0.1109)
layout:setPositionPercentY(0.8660)
layout:setPercentWidth(0.0469)
layout:setPercentHeight(0.0556)
layout:setSize({width = 60.0000, height = 40.0000})
layout:setLeftMargin(142.0000)
layout:setRightMargin(1078.0000)
layout:setTopMargin(76.5000)
layout:setBottomMargin(603.5000)
Scene:addChild(scoreText)

--Create castle
local castle = ccui.ImageView:create()
castle:ignoreContentAdaptWithSize(false)
castle:loadTexture("game/GuardCastle/images/game/castle.png",0)
castle:setLayoutComponentEnabled(true)
castle:setName("castle")
castle:setTag(15)
castle:setCascadeColorEnabled(true)
castle:setCascadeOpacityEnabled(true)
castle:setPosition(630.0000, 400.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(castle)
layout:setPositionPercentX(0.4922)
layout:setPositionPercentY(0.5556)
layout:setPercentWidth(0.4211)
layout:setPercentHeight(0.7069)
layout:setSize({width = 539.0000, height = 509.0000})
layout:setLeftMargin(360.5000)
layout:setRightMargin(380.5000)
layout:setTopMargin(65.5000)
layout:setBottomMargin(145.5000)
Scene:addChild(castle)

--Create smoke
local smoke = cc.ParticleSystemQuad:create("game/GuardCastle/images/game/yanwu.plist")
smoke:setName("smoke")
smoke:setTag(35)
smoke:setCascadeColorEnabled(true)
smoke:setCascadeOpacityEnabled(true)
smoke:setPosition(615.0000, 236.0000)
smoke:setScaleX(0.9000)
smoke:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(smoke)
layout:setPositionPercentX(0.4805)
layout:setPositionPercentY(0.3278)
layout:setLeftMargin(615.0000)
layout:setRightMargin(665.0000)
layout:setTopMargin(484.0000)
layout:setBottomMargin(236.0000)
smoke:setBlendFunc({src = 770, dst = 771})
Scene:addChild(smoke)

--Create btnPause
local btnPause = ccui.Button:create()
btnPause:ignoreContentAdaptWithSize(false)
btnPause:loadTextureNormal("game/GuardCastle/images/game/btnPause.png",0)
btnPause:setTitleFontSize(14)
btnPause:setTitleColor({r = 65, g = 65, b = 70})
btnPause:setLayoutComponentEnabled(true)
btnPause:setName("btnPause")
btnPause:setTag(112)
btnPause:setCascadeColorEnabled(true)
btnPause:setCascadeOpacityEnabled(true)
btnPause:setPosition(1176.8780, 624.6870)
layout = ccui.LayoutComponent:bindLayoutComponent(btnPause)
layout:setPositionPercentX(0.9194)
layout:setPositionPercentY(0.8676)
layout:setPercentWidth(0.0664)
layout:setPercentHeight(0.1194)
layout:setSize({width = 85.0000, height = 86.0000})
layout:setLeftMargin(1134.3780)
layout:setRightMargin(60.6216)
layout:setTopMargin(52.3130)
layout:setBottomMargin(581.6870)
Scene:addChild(btnPause)

--Create btnKill
local btnKill = ccui.Button:create()
btnKill:ignoreContentAdaptWithSize(false)
btnKill:loadTextureNormal("game/GuardCastle/images/game/skill-sheet0.png",0)
btnKill:setTitleFontSize(14)
btnKill:setTitleColor({r = 65, g = 65, b = 70})
btnKill:setLayoutComponentEnabled(true)
btnKill:setName("btnKill")
btnKill:setTag(36)
btnKill:setCascadeColorEnabled(true)
btnKill:setCascadeOpacityEnabled(true)
btnKill:setPosition(1105.7290, 262.6870)
layout = ccui.LayoutComponent:bindLayoutComponent(btnKill)
layout:setPositionPercentX(0.8639)
layout:setPositionPercentY(0.3648)
layout:setPercentWidth(0.1125)
layout:setPercentHeight(0.2000)
layout:setSize({width = 144.0000, height = 144.0000})
layout:setLeftMargin(1033.7290)
layout:setRightMargin(102.2712)
layout:setTopMargin(385.3130)
layout:setBottomMargin(190.6870)
Scene:addChild(btnKill)

--Create coolingTimeText
local coolingTimeText = ccui.Text:create()
coolingTimeText:ignoreContentAdaptWithSize(true)
coolingTimeText:setTextAreaSize({width = 0, height = 0})
coolingTimeText:setFontName("game/GuardCastle/images/font/font.ttf")
coolingTimeText:setFontSize(40)
coolingTimeText:setString([[15]])
coolingTimeText:enableShadow({r = 110, g = 110, b = 110, a = 255}, {width = 2, height = -2}, 0)
coolingTimeText:enableOutline({r = 238, g = 169, b = 144, a = 255}, 1)
coolingTimeText:setLayoutComponentEnabled(true)
coolingTimeText:setName("coolingTimeText")
coolingTimeText:setTag(12)
coolingTimeText:setCascadeColorEnabled(true)
coolingTimeText:setCascadeOpacityEnabled(true)
coolingTimeText:setPosition(72.0000, 72.0000)
coolingTimeText:setTextColor({r = 255, g = 165, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(coolingTimeText)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3819)
layout:setPercentHeight(0.3611)
layout:setSize({width = 55.0000, height = 52.0000})
layout:setLeftMargin(44.5000)
layout:setRightMargin(44.5000)
layout:setTopMargin(46.0000)
layout:setBottomMargin(46.0000)
btnKill:addChild(coolingTimeText)

--Create hpbg
local hpbg = ccui.ImageView:create()
hpbg:ignoreContentAdaptWithSize(false)
hpbg:loadTexture("game/GuardCastle/images/game/res_2.png",0)
hpbg:setLayoutComponentEnabled(true)
hpbg:setName("hpbg")
hpbg:setTag(23)
hpbg:setCascadeColorEnabled(true)
hpbg:setCascadeOpacityEnabled(true)
hpbg:setPosition(613.0000, 129.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hpbg)
layout:setPositionPercentX(0.4789)
layout:setPositionPercentY(0.1792)
layout:setPercentWidth(0.2594)
layout:setPercentHeight(0.0694)
layout:setSize({width = 332.0000, height = 50.0000})
layout:setLeftMargin(447.0000)
layout:setRightMargin(501.0000)
layout:setTopMargin(566.0000)
layout:setBottomMargin(104.0000)
Scene:addChild(hpbg)

--Create hp
local hp = ccui.LoadingBar:create()
hp:loadTexture("game/GuardCastle/images/game/res_1.png",0)
hp:ignoreContentAdaptWithSize(false)
hp:setLayoutComponentEnabled(true)
hp:setName("hp")
hp:setTag(24)
hp:setCascadeColorEnabled(true)
hp:setCascadeOpacityEnabled(true)
hp:setPosition(166.0000, 25.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hp)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9639)
layout:setPercentHeight(0.4000)
layout:setSize({width = 320.0000, height = 20.0000})
layout:setLeftMargin(6.0000)
layout:setRightMargin(6.0000)
layout:setTopMargin(15.0000)
layout:setBottomMargin(15.0000)
hpbg:addChild(hp)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

