--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("select/res/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(779)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0007, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(0.0007)
layout:setRightMargin(-0.0007)
Layer:addChild(bg)

--Create role
local role = ccui.ImageView:create()
role:ignoreContentAdaptWithSize(false)
role:loadTexture("select/job/huoban_1_0.png",0)
role:setLayoutComponentEnabled(true)
role:setName("role")
role:setTag(8)
role:setCascadeColorEnabled(true)
role:setCascadeOpacityEnabled(true)
role:setPosition(683.0079, 410.9760)
layout = ccui.LayoutComponent:bindLayoutComponent(role)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5336)
layout:setPositionPercentY(0.5708)
layout:setPercentWidth(0.3898)
layout:setPercentHeight(0.7639)
layout:setSize({width = 499.0000, height = 550.0000})
layout:setLeftMargin(433.5079)
layout:setRightMargin(347.4921)
layout:setTopMargin(34.0240)
layout:setBottomMargin(135.9760)
Layer:addChild(role)

--Create dec
local dec = ccui.ImageView:create()
dec:ignoreContentAdaptWithSize(false)
dec:loadTexture("select/job/dec_1.png",0)
dec:setLayoutComponentEnabled(true)
dec:setName("dec")
dec:setTag(40)
dec:setCascadeColorEnabled(true)
dec:setCascadeOpacityEnabled(true)
dec:setAnchorPoint(1.0000, 0.5000)
dec:setPosition(475.5000, 317.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(dec)
layout:setPositionPercentX(0.3715)
layout:setPositionPercentY(0.4403)
layout:setPercentWidth(0.3930)
layout:setPercentHeight(0.5889)
layout:setSize({width = 503.0000, height = 424.0000})
layout:setLeftMargin(-27.5000)
layout:setRightMargin(804.5000)
layout:setTopMargin(191.0000)
layout:setBottomMargin(105.0000)
Layer:addChild(dec)

--Create btnJob1
local btnJob1 = ccui.ImageView:create()
btnJob1:ignoreContentAdaptWithSize(false)
btnJob1:loadTexture("select/btn/zhanshitubiao2.png",0)
btnJob1:setTouchEnabled(true);
btnJob1:setLayoutComponentEnabled(true)
btnJob1:setName("btnJob1")
btnJob1:setTag(9)
btnJob1:setCascadeColorEnabled(true)
btnJob1:setCascadeOpacityEnabled(true)
btnJob1:setAnchorPoint(0.5137, 0.5968)
btnJob1:setPosition(1094.6770, 505.6954)
layout = ccui.LayoutComponent:bindLayoutComponent(btnJob1)
layout:setPositionPercentX(0.8552)
layout:setPositionPercentY(0.7024)
layout:setPercentWidth(0.1797)
layout:setPercentHeight(0.1486)
layout:setSize({width = 230.0000, height = 107.0000})
layout:setLeftMargin(976.5264)
layout:setRightMargin(73.4736)
layout:setTopMargin(171.1622)
layout:setBottomMargin(441.8378)
Layer:addChild(btnJob1)

--Create btnJob2
local btnJob2 = ccui.ImageView:create()
btnJob2:ignoreContentAdaptWithSize(false)
btnJob2:loadTexture("select/btn/fashitubiao2.png",0)
btnJob2:setTouchEnabled(true);
btnJob2:setLayoutComponentEnabled(true)
btnJob2:setName("btnJob2")
btnJob2:setTag(10)
btnJob2:setCascadeColorEnabled(true)
btnJob2:setCascadeOpacityEnabled(true)
btnJob2:setAnchorPoint(0.4846, 0.4200)
btnJob2:setPosition(1086.5800, 359.2268)
layout = ccui.LayoutComponent:bindLayoutComponent(btnJob2)
layout:setPositionPercentX(0.8489)
layout:setPositionPercentY(0.4989)
layout:setPercentWidth(0.1797)
layout:setPercentHeight(0.1486)
layout:setSize({width = 230.0000, height = 107.0000})
layout:setLeftMargin(975.1218)
layout:setRightMargin(74.8782)
layout:setTopMargin(298.7132)
layout:setBottomMargin(314.2868)
Layer:addChild(btnJob2)

--Create btnJob3
local btnJob3 = ccui.ImageView:create()
btnJob3:ignoreContentAdaptWithSize(false)
btnJob3:loadTexture("select/btn/daoshitubiao2.png",0)
btnJob3:setTouchEnabled(true);
btnJob3:setLayoutComponentEnabled(true)
btnJob3:setName("btnJob3")
btnJob3:setTag(11)
btnJob3:setCascadeColorEnabled(true)
btnJob3:setCascadeOpacityEnabled(true)
btnJob3:setAnchorPoint(0.5346, 0.5600)
btnJob3:setPosition(1099.4900, 246.6571)
layout = ccui.LayoutComponent:bindLayoutComponent(btnJob3)
layout:setPositionPercentX(0.8590)
layout:setPositionPercentY(0.3426)
layout:setPercentWidth(0.1797)
layout:setPercentHeight(0.1486)
layout:setSize({width = 230.0000, height = 107.0000})
layout:setLeftMargin(976.5319)
layout:setRightMargin(73.4681)
layout:setTopMargin(426.2629)
layout:setBottomMargin(186.7371)
Layer:addChild(btnJob3)

--Create btnSex2
local btnSex2 = ccui.ImageView:create()
btnSex2:ignoreContentAdaptWithSize(false)
btnSex2:loadTexture("select/res/btnWoman.png",0)
btnSex2:setTouchEnabled(true);
btnSex2:setLayoutComponentEnabled(true)
btnSex2:setName("btnSex2")
btnSex2:setTag(13)
btnSex2:setCascadeColorEnabled(true)
btnSex2:setCascadeOpacityEnabled(true)
btnSex2:setAnchorPoint(0.5811, 0.5079)
btnSex2:setPosition(1039.3990, 627.5596)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSex2)
layout:setPositionPercentX(0.8120)
layout:setPositionPercentY(0.8716)
layout:setPercentWidth(0.0656)
layout:setPercentHeight(0.1208)
layout:setSize({width = 84.0000, height = 87.0000})
layout:setLeftMargin(990.5865)
layout:setRightMargin(205.4135)
layout:setTopMargin(49.6278)
layout:setBottomMargin(583.3723)
Layer:addChild(btnSex2)

--Create btnSex1
local btnSex1 = ccui.ImageView:create()
btnSex1:ignoreContentAdaptWithSize(false)
btnSex1:loadTexture("select/res/btnMan.png",0)
btnSex1:setTouchEnabled(true);
btnSex1:setLayoutComponentEnabled(true)
btnSex1:setName("btnSex1")
btnSex1:setTag(14)
btnSex1:setCascadeColorEnabled(true)
btnSex1:setCascadeOpacityEnabled(true)
btnSex1:setAnchorPoint(0.4467, 0.4880)
btnSex1:setPosition(1166.1100, 625.8284)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSex1)
layout:setPositionPercentX(0.9110)
layout:setPositionPercentY(0.8692)
layout:setPercentWidth(0.0656)
layout:setPercentHeight(0.1208)
layout:setSize({width = 84.0000, height = 87.0000})
layout:setLeftMargin(1128.5870)
layout:setRightMargin(67.4127)
layout:setTopMargin(49.6276)
layout:setBottomMargin(583.3724)
Layer:addChild(btnSex1)

--Create btn_start
local btn_start = ccui.ImageView:create()
btn_start:ignoreContentAdaptWithSize(false)
btn_start:loadTexture("select/res/btn_start.png",0)
btn_start:setTouchEnabled(true);
btn_start:setLayoutComponentEnabled(true)
btn_start:setName("btn_start")
btn_start:setTag(786)
btn_start:setCascadeColorEnabled(true)
btn_start:setCascadeOpacityEnabled(true)
btn_start:setAnchorPoint(0.5089, 0.5058)
btn_start:setPosition(633.5009, 65.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_start)
layout:setPositionPercentX(0.4949)
layout:setPositionPercentY(0.0910)
layout:setPercentWidth(0.1906)
layout:setPercentHeight(0.1236)
layout:setSize({width = 244.0000, height = 89.0000})
layout:setLeftMargin(509.3293)
layout:setRightMargin(526.6707)
layout:setTopMargin(610.5162)
layout:setBottomMargin(20.4838)
Layer:addChild(btn_start)

--Create nameFrame
local nameFrame = ccui.ImageView:create()
nameFrame:ignoreContentAdaptWithSize(false)
nameFrame:loadTexture("select/res/shurumingcheng.png",0)
nameFrame:setLayoutComponentEnabled(true)
nameFrame:setName("nameFrame")
nameFrame:setTag(16)
nameFrame:setCascadeColorEnabled(true)
nameFrame:setCascadeOpacityEnabled(true)
nameFrame:setPosition(632.5000, 158.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nameFrame)
layout:setPositionPercentX(0.4941)
layout:setPositionPercentY(0.2194)
layout:setPercentWidth(0.2734)
layout:setPercentHeight(0.0778)
layout:setSize({width = 350.0000, height = 56.0000})
layout:setLeftMargin(457.5000)
layout:setRightMargin(472.5000)
layout:setTopMargin(534.0000)
layout:setBottomMargin(130.0000)
Layer:addChild(nameFrame)

--Create randNameBtn
local randNameBtn = ccui.ImageView:create()
randNameBtn:ignoreContentAdaptWithSize(false)
randNameBtn:loadTexture("select/res/tuozi.png",0)
randNameBtn:setTouchEnabled(true);
randNameBtn:setLayoutComponentEnabled(true)
randNameBtn:setName("randNameBtn")
randNameBtn:setTag(18)
randNameBtn:setCascadeColorEnabled(true)
randNameBtn:setCascadeOpacityEnabled(true)
randNameBtn:setPosition(746.5000, 160.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(randNameBtn)
layout:setPositionPercentX(0.5832)
layout:setPositionPercentY(0.2222)
layout:setPercentWidth(0.0406)
layout:setPercentHeight(0.0736)
layout:setSize({width = 52.0000, height = 53.0000})
layout:setLeftMargin(720.5000)
layout:setRightMargin(507.5000)
layout:setTopMargin(533.5000)
layout:setBottomMargin(133.5000)
Layer:addChild(randNameBtn)

--Create roleName
local roleName = ccui.TextField:create()
roleName:ignoreContentAdaptWithSize(false)
tolua.cast(roleName:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
roleName:setFontName("common/font/font.ttf")
roleName:setFontSize(25)
roleName:setPlaceHolder("Text Field")
roleName:setString([[昊天锤]])
roleName:setMaxLength(10)
roleName:setLayoutComponentEnabled(true)
roleName:setName("roleName")
roleName:setTag(20)
roleName:setCascadeColorEnabled(true)
roleName:setCascadeOpacityEnabled(true)
roleName:setAnchorPoint(0.4861, 0.6014)
roleName:setPosition(627.3005, 161.0429)
layout = ccui.LayoutComponent:bindLayoutComponent(roleName)
layout:setPositionPercentX(0.4901)
layout:setPositionPercentY(0.2237)
layout:setPercentWidth(0.0672)
layout:setPercentHeight(0.0417)
layout:setSize({width = 86.0000, height = 30.0000})
layout:setLeftMargin(585.4958)
layout:setRightMargin(608.5042)
layout:setTopMargin(546.9991)
layout:setBottomMargin(143.0009)
Layer:addChild(roleName)

--Create title
local title = ccui.ImageView:create()
title:ignoreContentAdaptWithSize(false)
title:loadTexture("select/res/chuangjianjuese.png",0)
title:setLayoutComponentEnabled(true)
title:setName("title")
title:setTag(21)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setAnchorPoint(0.0000, 0.5000)
title:setPosition(11.6183, 640.7988)
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentX(0.0091)
layout:setPositionPercentY(0.8900)
layout:setPercentWidth(0.3039)
layout:setPercentHeight(0.1819)
layout:setSize({width = 389.0000, height = 131.0000})
layout:setLeftMargin(11.6183)
layout:setRightMargin(879.3817)
layout:setTopMargin(13.7012)
layout:setBottomMargin(575.2988)
Layer:addChild(title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

