--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("select/res/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(779)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(bg)

--Create dec
local dec = ccui.ImageView:create()
dec:ignoreContentAdaptWithSize(false)
dec:loadTexture("select/job/dec_1.png",0)
dec:setLayoutComponentEnabled(true)
dec:setName("dec")
dec:setTag(54)
dec:setCascadeColorEnabled(true)
dec:setCascadeOpacityEnabled(true)
dec:setAnchorPoint(1.0000, 0.5000)
dec:setPosition(710.5000, 1063.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(dec)
layout:setPositionPercentX(0.9868)
layout:setPositionPercentY(0.8305)
layout:setPercentWidth(0.2486)
layout:setPercentHeight(0.2688)
layout:setSize({width = 179.0000, height = 344.0000})
layout:setLeftMargin(531.5000)
layout:setRightMargin(9.5000)
layout:setTopMargin(45.0000)
layout:setBottomMargin(891.0000)
Layer:addChild(dec)

--Create role
local role = ccui.ImageView:create()
role:ignoreContentAdaptWithSize(false)
role:loadTexture("select/job/huoban_1_0.png",0)
role:setLayoutComponentEnabled(true)
role:setName("role")
role:setTag(8)
role:setCascadeColorEnabled(true)
role:setCascadeOpacityEnabled(true)
role:setPosition(400.1760, 611.5840)
layout = ccui.LayoutComponent:bindLayoutComponent(role)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5558)
layout:setPositionPercentY(0.4778)
layout:setPercentWidth(0.9833)
layout:setPercentHeight(0.6242)
layout:setSize({width = 708.0000, height = 799.0000})
layout:setLeftMargin(46.1760)
layout:setRightMargin(-34.1760)
layout:setTopMargin(268.9160)
layout:setBottomMargin(212.0840)
Layer:addChild(role)

--Create btnJob1
local btnJob1 = ccui.ImageView:create()
btnJob1:ignoreContentAdaptWithSize(false)
btnJob1:loadTexture("select/btn/zhanshitubiao2.png",0)
btnJob1:setTouchEnabled(true);
btnJob1:setLayoutComponentEnabled(true)
btnJob1:setName("btnJob1")
btnJob1:setTag(9)
btnJob1:setCascadeColorEnabled(true)
btnJob1:setCascadeOpacityEnabled(true)
btnJob1:setPosition(80.0069, 495.6406)
layout = ccui.LayoutComponent:bindLayoutComponent(btnJob1)
layout:setPositionPercentX(0.1111)
layout:setPositionPercentY(0.3872)
layout:setPercentWidth(0.1556)
layout:setPercentHeight(0.0875)
layout:setSize({width = 112.0000, height = 112.0000})
layout:setLeftMargin(24.0069)
layout:setRightMargin(583.9931)
layout:setTopMargin(728.3594)
layout:setBottomMargin(439.6406)
Layer:addChild(btnJob1)

--Create btnJob2
local btnJob2 = ccui.ImageView:create()
btnJob2:ignoreContentAdaptWithSize(false)
btnJob2:loadTexture("select/btn/fashitubiao2.png",0)
btnJob2:setTouchEnabled(true);
btnJob2:setLayoutComponentEnabled(true)
btnJob2:setName("btnJob2")
btnJob2:setTag(10)
btnJob2:setCascadeColorEnabled(true)
btnJob2:setCascadeOpacityEnabled(true)
btnJob2:setPosition(85.0608, 369.1868)
layout = ccui.LayoutComponent:bindLayoutComponent(btnJob2)
layout:setPositionPercentX(0.1181)
layout:setPositionPercentY(0.2884)
layout:setPercentWidth(0.1556)
layout:setPercentHeight(0.0875)
layout:setSize({width = 112.0000, height = 112.0000})
layout:setLeftMargin(29.0608)
layout:setRightMargin(578.9392)
layout:setTopMargin(854.8132)
layout:setBottomMargin(313.1868)
Layer:addChild(btnJob2)

--Create btnJob3
local btnJob3 = ccui.ImageView:create()
btnJob3:ignoreContentAdaptWithSize(false)
btnJob3:loadTexture("select/btn/daoshitubiao2.png",0)
btnJob3:setTouchEnabled(true);
btnJob3:setLayoutComponentEnabled(true)
btnJob3:setName("btnJob3")
btnJob3:setTag(11)
btnJob3:setCascadeColorEnabled(true)
btnJob3:setCascadeOpacityEnabled(true)
btnJob3:setPosition(85.0608, 240.9371)
layout = ccui.LayoutComponent:bindLayoutComponent(btnJob3)
layout:setPositionPercentX(0.1181)
layout:setPositionPercentY(0.1882)
layout:setPercentWidth(0.1556)
layout:setPercentHeight(0.0875)
layout:setSize({width = 112.0000, height = 112.0000})
layout:setLeftMargin(29.0608)
layout:setRightMargin(578.9392)
layout:setTopMargin(983.0629)
layout:setBottomMargin(184.9371)
Layer:addChild(btnJob3)

--Create btnSex2
local btnSex2 = ccui.ImageView:create()
btnSex2:ignoreContentAdaptWithSize(false)
btnSex2:loadTexture("select/res/btnWoman.png",0)
btnSex2:setTouchEnabled(true);
btnSex2:setLayoutComponentEnabled(true)
btnSex2:setName("btnSex2")
btnSex2:setTag(13)
btnSex2:setCascadeColorEnabled(true)
btnSex2:setCascadeOpacityEnabled(true)
btnSex2:setPosition(642.8865, 459.0364)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSex2)
layout:setPositionPercentX(0.8929)
layout:setPositionPercentY(0.3586)
layout:setPercentWidth(0.1347)
layout:setPercentHeight(0.0758)
layout:setSize({width = 97.0000, height = 97.0000})
layout:setLeftMargin(594.3865)
layout:setRightMargin(28.6135)
layout:setTopMargin(772.4636)
layout:setBottomMargin(410.5364)
Layer:addChild(btnSex2)

--Create btnSex1
local btnSex1 = ccui.ImageView:create()
btnSex1:ignoreContentAdaptWithSize(false)
btnSex1:loadTexture("select/res/sexClick.png",0)
btnSex1:setTouchEnabled(true);
btnSex1:setLayoutComponentEnabled(true)
btnSex1:setName("btnSex1")
btnSex1:setTag(14)
btnSex1:setCascadeColorEnabled(true)
btnSex1:setCascadeOpacityEnabled(true)
btnSex1:setPosition(642.8865, 347.0556)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSex1)
layout:setPositionPercentX(0.8929)
layout:setPositionPercentY(0.2711)
layout:setPercentWidth(0.1347)
layout:setPercentHeight(0.0758)
layout:setSize({width = 97.0000, height = 97.0000})
layout:setLeftMargin(594.3865)
layout:setRightMargin(28.6135)
layout:setTopMargin(884.4444)
layout:setBottomMargin(298.5556)
Layer:addChild(btnSex1)

--Create btn_start
local btn_start = ccui.ImageView:create()
btn_start:ignoreContentAdaptWithSize(false)
btn_start:loadTexture("select/res/btn_start.png",0)
btn_start:setTouchEnabled(true);
btn_start:setLayoutComponentEnabled(true)
btn_start:setName("btn_start")
btn_start:setTag(786)
btn_start:setCascadeColorEnabled(true)
btn_start:setCascadeOpacityEnabled(true)
btn_start:setAnchorPoint(0.5089, 0.5058)
btn_start:setPosition(371.5010, 77.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_start)
layout:setPositionPercentX(0.5160)
layout:setPositionPercentY(0.0605)
layout:setPercentWidth(0.4847)
layout:setPercentHeight(0.1188)
layout:setSize({width = 349.0000, height = 152.0000})
layout:setLeftMargin(193.8949)
layout:setRightMargin(177.1051)
layout:setTopMargin(1127.3820)
layout:setBottomMargin(0.6184)
Layer:addChild(btn_start)

--Create nameFrame
local nameFrame = ccui.ImageView:create()
nameFrame:ignoreContentAdaptWithSize(false)
nameFrame:loadTexture("select/res/shurumingcheng.png",0)
nameFrame:setLayoutComponentEnabled(true)
nameFrame:setName("nameFrame")
nameFrame:setTag(16)
nameFrame:setCascadeColorEnabled(true)
nameFrame:setCascadeOpacityEnabled(true)
nameFrame:setPosition(360.0000, 186.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nameFrame)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1453)
layout:setPercentWidth(0.4389)
layout:setPercentHeight(0.0531)
layout:setSize({width = 316.0000, height = 68.0000})
layout:setLeftMargin(202.0000)
layout:setRightMargin(202.0000)
layout:setTopMargin(1060.0000)
layout:setBottomMargin(152.0000)
Layer:addChild(nameFrame)

--Create randNameBtn
local randNameBtn = ccui.ImageView:create()
randNameBtn:ignoreContentAdaptWithSize(false)
randNameBtn:loadTexture("select/res/tuozi.png",0)
randNameBtn:setTouchEnabled(true);
randNameBtn:setLayoutComponentEnabled(true)
randNameBtn:setName("randNameBtn")
randNameBtn:setTag(18)
randNameBtn:setCascadeColorEnabled(true)
randNameBtn:setCascadeOpacityEnabled(true)
randNameBtn:setAnchorPoint(0.5208, 0.4167)
randNameBtn:setPosition(486.5000, 181.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(randNameBtn)
layout:setPositionPercentX(0.6757)
layout:setPositionPercentY(0.1418)
layout:setPercentWidth(0.0667)
layout:setPercentHeight(0.0422)
layout:setSize({width = 48.0000, height = 54.0000})
layout:setLeftMargin(461.5016)
layout:setRightMargin(210.4984)
layout:setTopMargin(1067.0020)
layout:setBottomMargin(158.9982)
Layer:addChild(randNameBtn)

--Create roleName
local roleName = ccui.TextField:create()
roleName:ignoreContentAdaptWithSize(false)
tolua.cast(roleName:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
roleName:setFontName("common/font/font.ttf")
roleName:setFontSize(25)
roleName:setPlaceHolder("Text Field")
roleName:setString([[昊天锤]])
roleName:setMaxLength(10)
roleName:setLayoutComponentEnabled(true)
roleName:setName("roleName")
roleName:setTag(20)
roleName:setCascadeColorEnabled(true)
roleName:setCascadeOpacityEnabled(true)
roleName:setAnchorPoint(0.4187, 0.5500)
roleName:setPosition(334.5000, 186.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(roleName)
layout:setPositionPercentX(0.4646)
layout:setPositionPercentY(0.1457)
layout:setPercentWidth(0.1194)
layout:setPercentHeight(0.0234)
layout:setSize({width = 86.0000, height = 30.0000})
layout:setLeftMargin(298.4918)
layout:setRightMargin(335.5082)
layout:setTopMargin(1080.0000)
layout:setBottomMargin(170.0000)
Layer:addChild(roleName)

--Create title
local title = ccui.ImageView:create()
title:ignoreContentAdaptWithSize(false)
title:loadTexture("select/res/chuangjianjuese.png",0)
title:setLayoutComponentEnabled(true)
title:setName("title")
title:setTag(21)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setAnchorPoint(0.0000, 0.5000)
title:setPosition(194.6180, 1215.7990)
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentX(0.2703)
layout:setPositionPercentY(0.9498)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(0.5000)
layout:setPercentHeight(0.0539)
layout:setSize({width = 360.0000, height = 69.0000})
layout:setLeftMargin(194.6180)
layout:setRightMargin(165.3820)
layout:setTopMargin(29.7013)
layout:setBottomMargin(1181.2990)
Layer:addChild(title)

--Create select_sex
local select_sex = ccui.ImageView:create()
select_sex:ignoreContentAdaptWithSize(false)
select_sex:loadTexture("select/res/btnSexIcon_1.png",0)
select_sex:setLayoutComponentEnabled(true)
select_sex:setName("select_sex")
select_sex:setTag(15)
select_sex:setCascadeColorEnabled(true)
select_sex:setCascadeOpacityEnabled(true)
select_sex:setPosition(1173.0000, 447.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(select_sex)
layout:setPositionPercentX(1.6292)
layout:setPositionPercentY(0.3496)
layout:setPercentWidth(0.1347)
layout:setPercentHeight(0.0758)
layout:setSize({width = 97.0000, height = 97.0000})
layout:setLeftMargin(1124.5000)
layout:setRightMargin(-501.5000)
layout:setTopMargin(784.0000)
layout:setBottomMargin(399.0000)
Layer:addChild(select_sex)

--Create select_job
local select_job = ccui.ImageView:create()
select_job:ignoreContentAdaptWithSize(false)
select_job:loadTexture("select/btn/click.png",0)
select_job:setLayoutComponentEnabled(true)
select_job:setName("select_job")
select_job:setTag(16)
select_job:setCascadeColorEnabled(true)
select_job:setCascadeOpacityEnabled(true)
select_job:setPosition(-320.0000, 304.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(select_job)
layout:setPositionPercentX(-0.4444)
layout:setPositionPercentY(0.2379)
layout:setPercentWidth(0.2097)
layout:setPercentHeight(0.1094)
layout:setSize({width = 151.0000, height = 140.0000})
layout:setLeftMargin(-395.5000)
layout:setRightMargin(964.5000)
layout:setTopMargin(905.5000)
layout:setBottomMargin(234.5000)
Layer:addChild(select_job)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

