--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Default
local Default = cc.Sprite:create("game/huangcheng/image/bg.png")
Default:setName("Default")
Default:setTag(5)
Default:setCascadeColorEnabled(true)
Default:setCascadeOpacityEnabled(true)
Default:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Default)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Default:setBlendFunc({src = 1, dst = 771})
Scene:addChild(Default)

--Create start
local start = ccui.Button:create()
start:ignoreContentAdaptWithSize(false)
start:loadTextureNormal("game/huangcheng/button/start_1.png",0)
start:setTitleFontSize(14)
start:setTitleColor({r = 65, g = 65, b = 70})
start:setLayoutComponentEnabled(true)
start:setName("start")
start:setTag(3)
start:setCascadeColorEnabled(true)
start:setCascadeOpacityEnabled(true)
start:setPosition(639.9976, 188.3725)
layout = ccui.LayoutComponent:bindLayoutComponent(start)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2616)
layout:setPercentWidth(0.1805)
layout:setPercentHeight(0.1139)
layout:setSize({width = 231.0000, height = 82.0000})
layout:setLeftMargin(524.4976)
layout:setRightMargin(524.5024)
layout:setTopMargin(490.6275)
layout:setBottomMargin(147.3725)
Scene:addChild(start)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game/huangcheng/image/kuloutou.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(5)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(639.9976, 449.8954)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6249)
layout:setPercentWidth(0.2547)
layout:setPercentHeight(0.3889)
layout:setSize({width = 326.0000, height = 280.0000})
layout:setLeftMargin(476.9976)
layout:setRightMargin(477.0024)
layout:setTopMargin(130.1046)
layout:setBottomMargin(309.8954)
Scene:addChild(Image_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

