--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("Default/ImageFile.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(29)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(641.0000, 599.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.6677)
layout:setPositionPercentY(0.9359)
layout:setPercentWidth(1.3333)
layout:setPercentHeight(0.3734)
layout:setSize({width = 1280.0000, height = 239.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(-321.0000)
layout:setTopMargin(-78.5000)
layout:setBottomMargin(479.5000)
Scene:addChild(Image_1)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("Default/ImageFile.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(30)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.6667)
layout:setPositionPercentY(0.5625)
layout:setPercentWidth(1.3333)
layout:setPercentHeight(0.3750)
layout:setSize({width = 1280.0000, height = 240.0000})
layout:setRightMargin(-320.0000)
layout:setTopMargin(160.0000)
layout:setBottomMargin(240.0000)
Scene:addChild(Image_2)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("Default/ImageFile.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(31)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(640.0000, 121.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.6667)
layout:setPositionPercentY(0.1891)
layout:setPercentWidth(1.3333)
layout:setPercentHeight(0.3750)
layout:setSize({width = 1280.0000, height = 240.0000})
layout:setRightMargin(-320.0000)
layout:setTopMargin(399.0000)
layout:setBottomMargin(1.0000)
Scene:addChild(Image_3)

--Create back
local back = ccui.Button:create()
back:ignoreContentAdaptWithSize(false)
back:loadTextureNormal("game/Spacels/image/Maininterface/BACK_BACKTOMENU.png",0)
back:loadTexturePressed("game/Spacels/image/Maininterface/BACK_BACKTOMENU.png",0)
back:loadTextureDisabled("Default/Button_Disable.png",0)
back:setTitleFontSize(24)
back:setTitleText("BACK")
back:setTitleColor({r = 26, g = 26, b = 26})
back:setLayoutComponentEnabled(true)
back:setName("back")
back:setTag(32)
back:setCascadeColorEnabled(true)
back:setCascadeOpacityEnabled(true)
back:setPosition(640.0000, 120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(back)
layout:setPositionPercentX(0.6667)
layout:setPositionPercentY(0.1875)
layout:setPercentWidth(0.1250)
layout:setPercentHeight(0.0625)
layout:setSize({width = 120.0000, height = 40.0000})
layout:setLeftMargin(580.0000)
layout:setRightMargin(260.0000)
layout:setTopMargin(500.0000)
layout:setBottomMargin(100.0000)
Scene:addChild(back)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontSize(72)
Text_1:setString([[Level]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(40)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(640.0000, 600.0000)
Text_1:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.6667)
layout:setPositionPercentY(0.9375)
layout:setPercentWidth(0.1802)
layout:setPercentHeight(0.1266)
layout:setSize({width = 173.0000, height = 81.0000})
layout:setLeftMargin(553.5000)
layout:setRightMargin(233.5000)
layout:setTopMargin(-0.5000)
layout:setBottomMargin(559.5000)
Scene:addChild(Text_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

