--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game/Spacels/image/Maininterface/BG1.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(42)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(640.0000, 600.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8333)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3319)
layout:setSize({width = 1280.0000, height = 239.0000})
layout:setTopMargin(0.5000)
layout:setBottomMargin(480.5000)
Scene:addChild(Image_1)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("game/Spacels/image/Maininterface/BG2.png",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(43)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3333)
layout:setSize({width = 1280.0000, height = 240.0000})
layout:setTopMargin(240.0000)
layout:setBottomMargin(240.0000)
Scene:addChild(Image_2)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
Image_3:loadTexture("game/Spacels/image/Maininterface/BG3.png",0)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setTag(44)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setPosition(640.0000, 120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1667)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3333)
layout:setSize({width = 1280.0000, height = 240.0000})
layout:setTopMargin(480.0000)
Scene:addChild(Image_3)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("game/Spacels/image/Maininterface/FZY3JW.TTF")
Text_1:setFontSize(36)
Text_1:setString([[RULE]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(45)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setAnchorPoint(0.0000, 0.5000)
Text_1:setPosition(265.0000, 625.0000)
Text_1:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.2070)
layout:setPositionPercentY(0.8681)
layout:setPercentWidth(0.0633)
layout:setPercentHeight(0.0583)
layout:setSize({width = 81.0000, height = 42.0000})
layout:setLeftMargin(265.0000)
layout:setRightMargin(934.0000)
layout:setTopMargin(74.0000)
layout:setBottomMargin(604.0000)
Scene:addChild(Text_1)

--Create Text_2
local Text_2 = ccui.Text:create()
Text_2:ignoreContentAdaptWithSize(true)
Text_2:setTextAreaSize({width = 0, height = 0})
Text_2:setFontName("game/Spacels/image/Maininterface/FZY3JW.TTF")
Text_2:setFontSize(36)
Text_2:setString([[KEEP TAPPING THE SCREEN BY HAND]])
Text_2:setLayoutComponentEnabled(true)
Text_2:setName("Text_2")
Text_2:setTag(46)
Text_2:setCascadeColorEnabled(true)
Text_2:setCascadeOpacityEnabled(true)
Text_2:setAnchorPoint(0.0000, 0.5000)
Text_2:setPosition(427.9998, 540.0000)
Text_2:setScaleY(1.0083)
Text_2:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_2)
layout:setPositionPercentX(0.3344)
layout:setPositionPercentY(0.7500)
layout:setPercentWidth(0.4461)
layout:setPercentHeight(0.0583)
layout:setSize({width = 571.0000, height = 42.0000})
layout:setLeftMargin(427.9998)
layout:setRightMargin(281.0002)
layout:setTopMargin(159.0000)
layout:setBottomMargin(519.0000)
Scene:addChild(Text_2)

--Create back
local back = ccui.Button:create()
back:ignoreContentAdaptWithSize(false)
back:setTitleFontName("game/Spacels/image/Maininterface/FZY3JW.TTF")
back:setTitleFontSize(36)
back:setTitleText("BACK TO MENU")
back:setTitleColor({r = 26, g = 26, b = 26})
back:setLayoutComponentEnabled(true)
back:setName("back")
back:setTag(47)
back:setCascadeColorEnabled(true)
back:setCascadeOpacityEnabled(true)
back:setAnchorPoint(0.0000, 0.5000)
back:setPosition(503.5000, 359.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(back)
layout:setPositionPercentX(0.3934)
layout:setPositionPercentY(0.4986)
layout:setPercentWidth(0.2133)
layout:setPercentHeight(0.0583)
layout:setSize({width = 273.0000, height = 42.0000})
layout:setLeftMargin(503.5000)
layout:setRightMargin(503.5000)
layout:setTopMargin(340.0000)
layout:setBottomMargin(338.0000)
Scene:addChild(back)

--Create star1
local star1 = ccui.ImageView:create()
star1:ignoreContentAdaptWithSize(false)
star1:loadTexture("game/Spacels/image/Maininterface/star.png",0)
star1:setLayoutComponentEnabled(true)
star1:setName("star1")
star1:setTag(48)
star1:setCascadeColorEnabled(true)
star1:setCascadeOpacityEnabled(true)
star1:setPosition(171.0000, 625.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(star1)
layout:setPositionPercentX(0.1336)
layout:setPositionPercentY(0.8681)
layout:setPercentWidth(0.0313)
layout:setPercentHeight(0.0556)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(151.0000)
layout:setRightMargin(1089.0000)
layout:setTopMargin(75.0000)
layout:setBottomMargin(605.0000)
Scene:addChild(star1)

--Create star2
local star2 = ccui.ImageView:create()
star2:ignoreContentAdaptWithSize(false)
star2:loadTexture("game/Spacels/image/Maininterface/star.png",0)
star2:setLayoutComponentEnabled(true)
star2:setName("star2")
star2:setTag(49)
star2:setCascadeColorEnabled(true)
star2:setCascadeOpacityEnabled(true)
star2:setPosition(302.0000, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(star2)
layout:setPositionPercentX(0.2359)
layout:setPositionPercentY(0.7500)
layout:setPercentWidth(0.0313)
layout:setPercentHeight(0.0556)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(282.0000)
layout:setRightMargin(958.0000)
layout:setTopMargin(160.0000)
layout:setBottomMargin(520.0000)
Scene:addChild(star2)

--Create star3
local star3 = ccui.ImageView:create()
star3:ignoreContentAdaptWithSize(false)
star3:loadTexture("game/Spacels/image/Maininterface/star.png",0)
star3:setLayoutComponentEnabled(true)
star3:setName("star3")
star3:setTag(50)
star3:setCascadeColorEnabled(true)
star3:setCascadeOpacityEnabled(true)
star3:setAnchorPoint(0.5250, 0.5625)
star3:setPosition(410.0000, 362.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(star3)
layout:setPositionPercentX(0.3203)
layout:setPositionPercentY(0.5035)
layout:setPercentWidth(0.0313)
layout:setPercentHeight(0.0556)
layout:setSize({width = 40.0000, height = 40.0000})
layout:setLeftMargin(389.0000)
layout:setRightMargin(851.0000)
layout:setTopMargin(340.0000)
layout:setBottomMargin(340.0000)
Scene:addChild(star3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

