--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(2)
Panel_1:setBackGroundColor({r = 173, g = 216, b = 230},{r = 229, g = 229, b = 229})
Panel_1:setBackGroundColorVector({x = 0, y = 1})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(90)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(Panel_1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game/shilong/image/tc.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(86)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(360.0000, 928.4932)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7254)
layout:setPercentWidth(1.2750)
layout:setPercentHeight(0.4688)
layout:setSize({width = 918.0000, height = 600.0000})
layout:setLeftMargin(-99.0000)
layout:setRightMargin(-99.0000)
layout:setTopMargin(51.5068)
layout:setBottomMargin(628.4932)
Panel_1:addChild(Image_1)

--Create kill
local kill = ccui.Text:create()
kill:ignoreContentAdaptWithSize(true)
kill:setTextAreaSize({width = 0, height = 0})
kill:setFontName("game/shilong/image/mzdzt.ttf")
kill:setFontSize(72)
kill:setString([[0]])
kill:setLayoutComponentEnabled(true)
kill:setName("kill")
kill:setTag(87)
kill:setCascadeColorEnabled(true)
kill:setCascadeOpacityEnabled(true)
kill:setVisible(false)
kill:setPosition(365.3647, 1029.6660)
kill:setTextColor({r = 127, g = 127, b = 127})
layout = ccui.LayoutComponent:bindLayoutComponent(kill)
layout:setPositionPercentX(0.5075)
layout:setPositionPercentY(0.8044)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0648)
layout:setSize({width = 36.0000, height = 83.0000})
layout:setLeftMargin(347.3647)
layout:setRightMargin(336.6353)
layout:setTopMargin(208.8337)
layout:setBottomMargin(988.1663)
Panel_1:addChild(kill)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize({width = 0, height = 0})
Text_1:setFontName("game/shilong/image/mzdzt.ttf")
Text_1:setFontSize(48)
Text_1:setString([[BEST: ]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(93)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setPosition(290.8752, 968.7847)
Text_1:setTextColor({r = 223, g = 28, b = 37})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(0.4040)
layout:setPositionPercentY(0.7569)
layout:setPercentWidth(0.1958)
layout:setPercentHeight(0.0430)
layout:setSize({width = 141.0000, height = 55.0000})
layout:setLeftMargin(220.3752)
layout:setRightMargin(358.6248)
layout:setTopMargin(283.7153)
layout:setBottomMargin(941.2847)
Panel_1:addChild(Text_1)

--Create hightscore
local hightscore = ccui.Text:create()
hightscore:ignoreContentAdaptWithSize(true)
hightscore:setTextAreaSize({width = 0, height = 0})
hightscore:setFontName("game/shilong/image/mzdzt.ttf")
hightscore:setFontSize(72)
hightscore:setString([[0]])
hightscore:setLayoutComponentEnabled(true)
hightscore:setName("hightscore")
hightscore:setTag(88)
hightscore:setCascadeColorEnabled(true)
hightscore:setCascadeOpacityEnabled(true)
hightscore:setPosition(460.6625, 968.0817)
hightscore:setTextColor({r = 127, g = 127, b = 127})
layout = ccui.LayoutComponent:bindLayoutComponent(hightscore)
layout:setPositionPercentX(0.6398)
layout:setPositionPercentY(0.7563)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0648)
layout:setSize({width = 36.0000, height = 83.0000})
layout:setLeftMargin(442.6625)
layout:setRightMargin(241.3375)
layout:setTopMargin(270.4183)
layout:setBottomMargin(926.5817)
Panel_1:addChild(hightscore)

--Create Text_1_0
local Text_1_0 = ccui.Text:create()
Text_1_0:ignoreContentAdaptWithSize(true)
Text_1_0:setTextAreaSize({width = 0, height = 0})
Text_1_0:setFontName("game/shilong/image/mzdzt.ttf")
Text_1_0:setFontSize(48)
Text_1_0:setString([[SCORE:]])
Text_1_0:setLayoutComponentEnabled(true)
Text_1_0:setName("Text_1_0")
Text_1_0:setTag(94)
Text_1_0:setCascadeColorEnabled(true)
Text_1_0:setCascadeOpacityEnabled(true)
Text_1_0:setPosition(282.8754, 852.5968)
Text_1_0:setTextColor({r = 0, g = 179, b = 162})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1_0)
layout:setPositionPercentX(0.3929)
layout:setPositionPercentY(0.6661)
layout:setPercentWidth(0.2583)
layout:setPercentHeight(0.0430)
layout:setSize({width = 186.0000, height = 55.0000})
layout:setLeftMargin(189.8754)
layout:setRightMargin(344.1246)
layout:setTopMargin(399.9032)
layout:setBottomMargin(825.0968)
Panel_1:addChild(Text_1_0)

--Create score
local score = ccui.Text:create()
score:ignoreContentAdaptWithSize(true)
score:setTextAreaSize({width = 0, height = 0})
score:setFontName("game/shilong/image/mzdzt.ttf")
score:setFontSize(72)
score:setString([[0]])
score:setLayoutComponentEnabled(true)
score:setName("score")
score:setTag(89)
score:setCascadeColorEnabled(true)
score:setCascadeOpacityEnabled(true)
score:setPosition(460.6625, 852.4537)
score:setTextColor({r = 127, g = 127, b = 127})
layout = ccui.LayoutComponent:bindLayoutComponent(score)
layout:setPositionPercentX(0.6398)
layout:setPositionPercentY(0.6660)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.0648)
layout:setSize({width = 36.0000, height = 83.0000})
layout:setLeftMargin(442.6625)
layout:setRightMargin(241.3375)
layout:setTopMargin(386.0463)
layout:setBottomMargin(810.9537)
Panel_1:addChild(score)

--Create replay
local replay = ccui.Button:create()
replay:ignoreContentAdaptWithSize(false)
replay:loadTextureNormal("game/shilong/image/btn.png",0)
replay:loadTextureDisabled("Default/Button_Disable.png",0)
replay:setTitleFontName("game/shilong/image/mzdzt.ttf")
replay:setTitleFontSize(40)
replay:setTitleText("Replay")
replay:setTitleColor({r = 0, g = 0, b = 0})
replay:setLayoutComponentEnabled(true)
replay:setName("replay")
replay:setTag(91)
replay:setCascadeColorEnabled(true)
replay:setCascadeOpacityEnabled(true)
replay:setPosition(361.2391, 541.3607)
layout = ccui.LayoutComponent:bindLayoutComponent(replay)
layout:setPositionPercentX(0.5017)
layout:setPositionPercentY(0.4229)
layout:setPercentWidth(0.2431)
layout:setPercentHeight(0.0570)
layout:setSize({width = 175.0000, height = 73.0000})
layout:setLeftMargin(273.7391)
layout:setRightMargin(271.2609)
layout:setTopMargin(702.1393)
layout:setBottomMargin(504.8607)
Panel_1:addChild(replay)

--Create home
local home = ccui.Button:create()
home:ignoreContentAdaptWithSize(false)
home:loadTextureNormal("game/shilong/image/btn.png",0)
home:loadTexturePressed("Default/Button_Press.png",0)
home:setTitleFontName("game/shilong/image/mzdzt.ttf")
home:setTitleFontSize(40)
home:setTitleText("Home")
home:setTitleColor({r = 0, g = 0, b = 0})
home:setLayoutComponentEnabled(true)
home:setName("home")
home:setTag(92)
home:setCascadeColorEnabled(true)
home:setCascadeOpacityEnabled(true)
home:setPosition(361.2391, 390.0594)
layout = ccui.LayoutComponent:bindLayoutComponent(home)
layout:setPositionPercentX(0.5017)
layout:setPositionPercentY(0.3047)
layout:setPercentWidth(0.2431)
layout:setPercentHeight(0.0570)
layout:setSize({width = 175.0000, height = 73.0000})
layout:setLeftMargin(273.7391)
layout:setRightMargin(271.2609)
layout:setTopMargin(853.4406)
layout:setBottomMargin(353.5594)
Panel_1:addChild(home)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

