--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/shilong/image/BG.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(58)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Scene:addChild(bg)

--Create role
local role = cc.Sprite:create("game/shilong/image/role.png")
role:setName("role")
role:setTag(49)
role:setCascadeColorEnabled(true)
role:setCascadeOpacityEnabled(true)
role:setAnchorPoint(1.0000, 0.0000)
role:setPosition(720.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(role)
layout:setPositionPercentX(1.0000)
layout:setPercentWidth(0.7431)
layout:setPercentHeight(0.4953)
layout:setSize({width = 535.0000, height = 634.0000})
layout:setLeftMargin(185.0000)
layout:setTopMargin(646.0000)
role:setBlendFunc({src = 1, dst = 771})
Scene:addChild(role)

--Create BtnSet
local BtnSet = ccui.Button:create()
BtnSet:ignoreContentAdaptWithSize(false)
BtnSet:loadTextureNormal("game/shilong/image/shezhi.png",0)
BtnSet:setTitleFontSize(14)
BtnSet:setTitleColor({r = 65, g = 65, b = 70})
BtnSet:setScale9Enabled(true)
BtnSet:setCapInsets({x = 15, y = 11, width = 27, height = 35})
BtnSet:setLayoutComponentEnabled(true)
BtnSet:setName("BtnSet")
BtnSet:setTag(40)
BtnSet:setCascadeColorEnabled(true)
BtnSet:setCascadeOpacityEnabled(true)
BtnSet:setPosition(647.5892, 1232.2320)
layout = ccui.LayoutComponent:bindLayoutComponent(BtnSet)
layout:setPositionPercentX(0.8994)
layout:setPositionPercentY(0.9627)
layout:setPercentWidth(0.0792)
layout:setPercentHeight(0.0445)
layout:setSize({width = 57.0000, height = 57.0000})
layout:setLeftMargin(619.0892)
layout:setRightMargin(43.9108)
layout:setTopMargin(19.2684)
layout:setBottomMargin(1203.7320)
Scene:addChild(BtnSet)

--Create best
local best = ccui.Text:create()
best:ignoreContentAdaptWithSize(true)
best:setTextAreaSize({width = 0, height = 0})
best:setFontName("game/shilong/image/mzdzt.ttf")
best:setFontSize(40)
best:setString([[BEST:100]])
best:setLayoutComponentEnabled(true)
best:setName("best")
best:setTag(47)
best:setCascadeColorEnabled(true)
best:setCascadeOpacityEnabled(true)
best:setPosition(361.0000, 1045.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(best)
layout:setPositionPercentX(0.5014)
layout:setPositionPercentY(0.8164)
layout:setPercentWidth(0.2514)
layout:setPercentHeight(0.0359)
layout:setSize({width = 181.0000, height = 46.0000})
layout:setLeftMargin(270.5000)
layout:setRightMargin(268.5000)
layout:setTopMargin(212.0000)
layout:setBottomMargin(1022.0000)
Scene:addChild(best)

--Create classic
local classic = ccui.Button:create()
classic:ignoreContentAdaptWithSize(false)
classic:loadTextureNormal("game/shilong/image/btn.png",0)
classic:setTitleFontName("game/shilong/image/mzdzt.ttf")
classic:setTitleFontSize(38)
classic:setTitleColor({r = 0, g = 0, b = 0})
classic:setLayoutComponentEnabled(true)
classic:setName("classic")
classic:setTag(67)
classic:setCascadeColorEnabled(true)
classic:setCascadeOpacityEnabled(true)
classic:setPosition(248.9991, 672.9985)
classic:setScaleX(0.7000)
classic:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(classic)
layout:setPositionPercentX(0.3458)
layout:setPositionPercentY(0.5258)
layout:setPercentWidth(0.3056)
layout:setPercentHeight(0.0703)
layout:setSize({width = 220.0000, height = 90.0000})
layout:setLeftMargin(138.9991)
layout:setRightMargin(361.0009)
layout:setTopMargin(562.0015)
layout:setBottomMargin(627.9985)
Scene:addChild(classic)

--Create class_text
local class_text = ccui.Text:create()
class_text:ignoreContentAdaptWithSize(true)
class_text:setTextAreaSize({width = 0, height = 0})
class_text:setFontName("game/shilong/image/mzdzt.ttf")
class_text:setFontSize(40)
class_text:setString([[Classic]])
class_text:setLayoutComponentEnabled(true)
class_text:setName("class_text")
class_text:setTag(68)
class_text:setCascadeColorEnabled(true)
class_text:setCascadeOpacityEnabled(true)
class_text:setAnchorPoint(0.5000, 0.0000)
class_text:setPosition(114.9940, 19.9980)
class_text:setScaleX(0.9000)
class_text:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(class_text)
layout:setPositionPercentX(0.5227)
layout:setPositionPercentY(0.2222)
layout:setPercentWidth(0.5636)
layout:setPercentHeight(0.5111)
layout:setSize({width = 124.0000, height = 46.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(52.9940)
layout:setRightMargin(43.0060)
layout:setTopMargin(24.0020)
layout:setBottomMargin(19.9980)
classic:addChild(class_text)

--Create survival
local survival = ccui.Button:create()
survival:ignoreContentAdaptWithSize(false)
survival:loadTextureNormal("game/shilong/image/btn.png",0)
survival:setTitleFontName("game/shilong/image/mzdzt.ttf")
survival:setTitleFontSize(38)
survival:setTitleColor({r = 0, g = 0, b = 0})
survival:setLayoutComponentEnabled(true)
survival:setName("survival")
survival:setTag(69)
survival:setCascadeColorEnabled(true)
survival:setCascadeOpacityEnabled(true)
survival:setPosition(506.9990, 672.9985)
survival:setScaleX(0.7000)
survival:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(survival)
layout:setPositionPercentX(0.7042)
layout:setPositionPercentY(0.5258)
layout:setPercentWidth(0.3056)
layout:setPercentHeight(0.0703)
layout:setSize({width = 220.0000, height = 90.0000})
layout:setLeftMargin(396.9990)
layout:setRightMargin(103.0010)
layout:setTopMargin(562.0015)
layout:setBottomMargin(627.9985)
Scene:addChild(survival)

--Create survival_text
local survival_text = ccui.Text:create()
survival_text:ignoreContentAdaptWithSize(true)
survival_text:setTextAreaSize({width = 0, height = 0})
survival_text:setFontName("game/shilong/image/mzdzt.ttf")
survival_text:setFontSize(45)
survival_text:setString([[Survival]])
survival_text:setLayoutComponentEnabled(true)
survival_text:setName("survival_text")
survival_text:setTag(70)
survival_text:setCascadeColorEnabled(true)
survival_text:setCascadeOpacityEnabled(true)
survival_text:setAnchorPoint(0.5000, 0.0000)
survival_text:setPosition(114.9940, 19.9980)
survival_text:setScaleX(0.9000)
survival_text:setScaleY(0.9000)
layout = ccui.LayoutComponent:bindLayoutComponent(survival_text)
layout:setPositionPercentX(0.5227)
layout:setPositionPercentY(0.2222)
layout:setPercentWidth(0.7455)
layout:setPercentHeight(0.5778)
layout:setSize({width = 164.0000, height = 52.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(32.9940)
layout:setRightMargin(23.0060)
layout:setTopMargin(18.0020)
layout:setBottomMargin(19.9980)
survival:addChild(survival_text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

