--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/tiger/image/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(35)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.6667)
layout:setPositionPercentY(0.5625)
layout:setPercentWidth(1.3333)
layout:setPercentHeight(1.1250)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setRightMargin(-320.0000)
layout:setTopMargin(-80.0000)
Scene:addChild(bg)

--Create tiger
local tiger = ccui.ImageView:create()
tiger:ignoreContentAdaptWithSize(false)
tiger:loadTexture("game/tiger/image/tiger.png",0)
tiger:setLayoutComponentEnabled(true)
tiger:setName("tiger")
tiger:setTag(34)
tiger:setCascadeColorEnabled(true)
tiger:setCascadeOpacityEnabled(true)
tiger:setPosition(917.0000, 341.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(tiger)
layout:setPositionPercentX(0.9552)
layout:setPositionPercentY(0.5336)
layout:setPercentWidth(0.5208)
layout:setPercentHeight(0.4688)
layout:setSize({width = 500.0000, height = 300.0000})
layout:setLeftMargin(667.0000)
layout:setRightMargin(-207.0000)
layout:setTopMargin(148.5000)
layout:setBottomMargin(191.5000)
Scene:addChild(tiger)

--Create start
local start = ccui.Button:create()
start:ignoreContentAdaptWithSize(false)
start:loadTextureNormal("game/tiger/image/start_1.png",0)
start:loadTexturePressed("game/tiger/image/start_2.png",0)
start:loadTextureDisabled("Default/Button_Disable.png",0)
start:setTitleFontSize(14)
start:setTitleColor({r = 65, g = 65, b = 70})
start:setScale9Enabled(true)
start:setCapInsets({x = 15, y = 11, width = 201, height = 60})
start:setLayoutComponentEnabled(true)
start:setName("start")
start:setTag(30)
start:setCascadeColorEnabled(true)
start:setCascadeOpacityEnabled(true)
start:setPosition(444.0000, 404.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(start)
layout:setPositionPercentX(0.4625)
layout:setPositionPercentY(0.6313)
layout:setPercentWidth(0.2406)
layout:setPercentHeight(0.1281)
layout:setSize({width = 231.0000, height = 82.0000})
layout:setLeftMargin(328.5000)
layout:setRightMargin(400.5000)
layout:setTopMargin(195.0000)
layout:setBottomMargin(363.0000)
Scene:addChild(start)

--Create rule
local rule = ccui.Button:create()
rule:ignoreContentAdaptWithSize(false)
rule:loadTextureNormal("game/tiger/image/rule_1.png",0)
rule:loadTexturePressed("game/tiger/image/rule_2.png",0)
rule:loadTextureDisabled("Default/Button_Disable.png",0)
rule:setTitleFontSize(14)
rule:setTitleColor({r = 65, g = 65, b = 70})
rule:setScale9Enabled(true)
rule:setCapInsets({x = 15, y = 11, width = 201, height = 60})
rule:setLayoutComponentEnabled(true)
rule:setName("rule")
rule:setTag(31)
rule:setCascadeColorEnabled(true)
rule:setCascadeOpacityEnabled(true)
rule:setPosition(444.0000, 268.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(rule)
layout:setPositionPercentX(0.4625)
layout:setPositionPercentY(0.4187)
layout:setPercentWidth(0.2406)
layout:setPercentHeight(0.1281)
layout:setSize({width = 231.0000, height = 82.0000})
layout:setLeftMargin(328.5000)
layout:setRightMargin(400.5000)
layout:setTopMargin(331.0000)
layout:setBottomMargin(227.0000)
Scene:addChild(rule)

--Create off
local off = ccui.Button:create()
off:ignoreContentAdaptWithSize(false)
off:loadTextureNormal("game/tiger/image/music_2.png",0)
off:loadTexturePressed("game/tiger/image/music_2.png",0)
off:loadTextureDisabled("Default/Button_Disable.png",0)
off:setTitleFontSize(14)
off:setTitleColor({r = 65, g = 65, b = 70})
off:setScale9Enabled(true)
off:setCapInsets({x = 15, y = 11, width = 58, height = 69})
off:setLayoutComponentEnabled(true)
off:setName("off")
off:setTag(32)
off:setCascadeColorEnabled(true)
off:setCascadeOpacityEnabled(true)
off:setVisible(false)
off:setPosition(56.0000, 664.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(off)
layout:setPositionPercentX(0.0583)
layout:setPositionPercentY(1.0375)
layout:setPercentWidth(0.0917)
layout:setPercentHeight(0.1422)
layout:setSize({width = 88.0000, height = 91.0000})
layout:setLeftMargin(12.0000)
layout:setRightMargin(860.0000)
layout:setTopMargin(-69.5000)
layout:setBottomMargin(618.5000)
Scene:addChild(off)

--Create no
local no = ccui.Button:create()
no:ignoreContentAdaptWithSize(false)
no:loadTextureNormal("game/tiger/image/music_1.png",0)
no:loadTexturePressed("game/tiger/image/music_1.png",0)
no:loadTextureDisabled("Default/Button_Disable.png",0)
no:setTitleFontSize(14)
no:setTitleColor({r = 65, g = 65, b = 70})
no:setScale9Enabled(true)
no:setCapInsets({x = 15, y = 11, width = 62, height = 74})
no:setLayoutComponentEnabled(true)
no:setName("no")
no:setTag(33)
no:setCascadeColorEnabled(true)
no:setCascadeOpacityEnabled(true)
no:setPosition(56.0000, 664.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(no)
layout:setPositionPercentX(0.0583)
layout:setPositionPercentY(1.0375)
layout:setPercentWidth(0.0958)
layout:setPercentHeight(0.1500)
layout:setSize({width = 92.0000, height = 96.0000})
layout:setLeftMargin(10.0000)
layout:setRightMargin(858.0000)
layout:setTopMargin(-72.0000)
layout:setBottomMargin(616.0000)
Scene:addChild(no)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

