--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/chuangchuang/images/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(65)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Layer:addChild(bg)

--Create role
local role = ccui.ImageView:create()
role:ignoreContentAdaptWithSize(false)
role:loadTexture("game/chuangchuang/images/role.png",0)
role:setLayoutComponentEnabled(true)
role:setName("role")
role:setTag(43)
role:setCascadeColorEnabled(true)
role:setCascadeOpacityEnabled(true)
role:setAnchorPoint(1.0000, 0.0000)
role:setPosition(720.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(role)
layout:setPositionPercentX(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.4688)
layout:setSize({width = 720.0000, height = 600.0000})
layout:setTopMargin(680.0000)
Layer:addChild(role)

--Create btnStart
local btnStart = ccui.Button:create()
btnStart:ignoreContentAdaptWithSize(false)
btnStart:loadTextureNormal("game/chuangchuang/images/btn.png",0)
btnStart:setTitleFontName("game/chuangchuang/images/hwxk.ttf")
btnStart:setTitleFontSize(35)
btnStart:setTitleText("Play")
btnStart:setTitleColor({r = 0, g = 0, b = 0})
btnStart:setLayoutComponentEnabled(true)
btnStart:setName("btnStart")
btnStart:setTag(53)
btnStart:setCascadeColorEnabled(true)
btnStart:setCascadeOpacityEnabled(true)
btnStart:setPosition(199.0800, 794.2401)
layout = ccui.LayoutComponent:bindLayoutComponent(btnStart)
layout:setPositionPercentX(0.2765)
layout:setPositionPercentY(0.6205)
layout:setPercentWidth(0.3222)
layout:setPercentHeight(0.0742)
layout:setSize({width = 232.0000, height = 95.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(83.0800)
layout:setRightMargin(404.9200)
layout:setTopMargin(438.2599)
layout:setBottomMargin(746.7401)
Layer:addChild(btnStart)

--Create btnAbout
local btnAbout = ccui.Button:create()
btnAbout:ignoreContentAdaptWithSize(false)
btnAbout:loadTextureNormal("game/chuangchuang/images/btn.png",0)
btnAbout:setTitleFontName("game/chuangchuang/images/hwxk.ttf")
btnAbout:setTitleFontSize(35)
btnAbout:setTitleText("Rule")
btnAbout:setTitleColor({r = 0, g = 0, b = 0})
btnAbout:setLayoutComponentEnabled(true)
btnAbout:setName("btnAbout")
btnAbout:setTag(54)
btnAbout:setCascadeColorEnabled(true)
btnAbout:setCascadeOpacityEnabled(true)
btnAbout:setPosition(199.0800, 612.7360)
layout = ccui.LayoutComponent:bindLayoutComponent(btnAbout)
layout:setPositionPercentX(0.2765)
layout:setPositionPercentY(0.4787)
layout:setPercentWidth(0.3222)
layout:setPercentHeight(0.0742)
layout:setSize({width = 232.0000, height = 95.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(83.0800)
layout:setRightMargin(404.9200)
layout:setTopMargin(619.7640)
layout:setBottomMargin(565.2360)
Layer:addChild(btnAbout)

--Create btnSetting
local btnSetting = ccui.Button:create()
btnSetting:ignoreContentAdaptWithSize(false)
btnSetting:loadTextureNormal("game/chuangchuang/images/shezhi.png",0)
btnSetting:loadTexturePressed("game/chuangchuang/images/shezhi.png",0)
btnSetting:loadTextureDisabled("Default/Button_Disable.png",0)
btnSetting:setTitleFontSize(14)
btnSetting:setTitleColor({r = 65, g = 65, b = 70})
btnSetting:setLayoutComponentEnabled(true)
btnSetting:setName("btnSetting")
btnSetting:setTag(66)
btnSetting:setCascadeColorEnabled(true)
btnSetting:setCascadeOpacityEnabled(true)
btnSetting:setPosition(656.8107, 1222.9590)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSetting)
layout:setPositionPercentX(0.9122)
layout:setPositionPercentY(0.9554)
layout:setPercentWidth(0.1139)
layout:setPercentHeight(0.0617)
layout:setSize({width = 82.0000, height = 79.0000})
layout:setHorizontalEdge(2)
layout:setVerticalEdge(2)
layout:setLeftMargin(615.8107)
layout:setRightMargin(22.1893)
layout:setTopMargin(17.5405)
layout:setBottomMargin(1183.4590)
Layer:addChild(btnSetting)

--Create best
local best = ccui.Text:create()
best:ignoreContentAdaptWithSize(true)
best:setTextAreaSize({width = 0, height = 0})
best:setFontName("game/chuangchuang/images/hwxk.ttf")
best:setFontSize(45)
best:setString([[BEAT:1000]])
best:setLayoutComponentEnabled(true)
best:setName("best")
best:setTag(23)
best:setCascadeColorEnabled(true)
best:setCascadeOpacityEnabled(true)
best:setPosition(196.6889, 1090.2170)
layout = ccui.LayoutComponent:bindLayoutComponent(best)
layout:setPositionPercentX(0.2732)
layout:setPositionPercentY(0.8517)
layout:setPercentWidth(0.2764)
layout:setPercentHeight(0.0383)
layout:setSize({width = 199.0000, height = 49.0000})
layout:setLeftMargin(97.1889)
layout:setRightMargin(423.8111)
layout:setTopMargin(165.2828)
layout:setBottomMargin(1065.7170)
Layer:addChild(best)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

