--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 605.0000, height = 430.0000})

--Create shade
local shade = ccui.Layout:create()
shade:ignoreContentAdaptWithSize(false)
shade:setClippingEnabled(false)
shade:setBackGroundColorOpacity(102)
shade:setTouchEnabled(true);
shade:setLayoutComponentEnabled(true)
shade:setName("shade")
shade:setTag(93)
shade:setCascadeColorEnabled(true)
shade:setCascadeOpacityEnabled(true)
shade:setAnchorPoint(0.5000, 0.5000)
shade:setPosition(274.8033, 217.4319)
layout = ccui.LayoutComponent:bindLayoutComponent(shade)
layout:setPositionPercentX(0.4542)
layout:setPositionPercentY(0.5057)
layout:setPercentWidth(3.3058)
layout:setPercentHeight(3.4884)
layout:setSize({width = 2000.0000, height = 1500.0000})
layout:setLeftMargin(-725.1967)
layout:setRightMargin(-669.8033)
layout:setTopMargin(-537.4319)
layout:setBottomMargin(-532.5681)
Layer:addChild(shade)

--Create TopPanel
local TopPanel = ccui.Layout:create()
TopPanel:ignoreContentAdaptWithSize(false)
TopPanel:setClippingEnabled(false)
TopPanel:setBackGroundColorOpacity(102)
TopPanel:setTouchEnabled(true);
TopPanel:setLayoutComponentEnabled(true)
TopPanel:setName("TopPanel")
TopPanel:setTag(78)
TopPanel:setCascadeColorEnabled(true)
TopPanel:setCascadeOpacityEnabled(true)
TopPanel:setAnchorPoint(0.5000, 0.5000)
TopPanel:setPosition(302.5000, 212.9790)
layout = ccui.LayoutComponent:bindLayoutComponent(TopPanel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4953)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 605.0000, height = 430.0000})
layout:setTopMargin(2.0210)
layout:setBottomMargin(-2.0210)
Layer:addChild(TopPanel)

--Create winbg
local winbg = cc.Sprite:create("game/WitchPoker/image/ui2/winbg.png")
winbg:setName("winbg")
winbg:setTag(83)
winbg:setCascadeColorEnabled(true)
winbg:setCascadeOpacityEnabled(true)
winbg:setPosition(300.0927, 217.0781)
layout = ccui.LayoutComponent:bindLayoutComponent(winbg)
layout:setPositionPercentX(0.4960)
layout:setPositionPercentY(0.5048)
layout:setPercentWidth(1.0479)
layout:setPercentHeight(0.8326)
layout:setSize({width = 634.0000, height = 358.0000})
layout:setLeftMargin(-16.9073)
layout:setRightMargin(-12.0927)
layout:setTopMargin(33.9219)
layout:setBottomMargin(38.0781)
winbg:setBlendFunc({src = 1, dst = 771})
TopPanel:addChild(winbg)

--Create closeBtn
local closeBtn = ccui.Button:create()
closeBtn:ignoreContentAdaptWithSize(false)
closeBtn:loadTextureNormal("game/WitchPoker/image/ui2/closeBtn.png",0)
closeBtn:setTitleFontSize(14)
closeBtn:setTitleColor({r = 65, g = 65, b = 70})
closeBtn:setLayoutComponentEnabled(true)
closeBtn:setName("closeBtn")
closeBtn:setTag(81)
closeBtn:setCascadeColorEnabled(true)
closeBtn:setCascadeOpacityEnabled(true)
closeBtn:setPosition(578.9245, 363.4360)
layout = ccui.LayoutComponent:bindLayoutComponent(closeBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9569)
layout:setPositionPercentY(0.8452)
layout:setPercentWidth(0.0942)
layout:setPercentHeight(0.1326)
layout:setSize({width = 57.0000, height = 57.0000})
layout:setLeftMargin(550.4245)
layout:setRightMargin(-2.4245)
layout:setTopMargin(38.0640)
layout:setBottomMargin(334.9360)
TopPanel:addChild(closeBtn)

--Create sliderNum
local sliderNum = ccui.Slider:create()
sliderNum:ignoreContentAdaptWithSize(false)
sliderNum:loadBarTexture("game/WitchPoker/image/ui2/horizontalLine.png",0)
sliderNum:loadProgressBarTexture("game/WitchPoker/image/ui2/horizontalLine.png",0)
sliderNum:loadSlidBallTextureNormal("game/WitchPoker/image/ui2/point.png",0)
sliderNum:loadSlidBallTexturePressed("game/WitchPoker/image/ui2/point.png",0)
sliderNum:loadSlidBallTextureDisabled("game/WitchPoker/image/ui2/point.png",0)
sliderNum:setPercent(50)
sliderNum:setLayoutComponentEnabled(true)
sliderNum:setName("sliderNum")
sliderNum:setTag(86)
sliderNum:setCascadeColorEnabled(true)
sliderNum:setCascadeOpacityEnabled(true)
sliderNum:setPosition(351.4561, 251.7798)
layout = ccui.LayoutComponent:bindLayoutComponent(sliderNum)
layout:setPositionPercentX(0.5809)
layout:setPositionPercentY(0.5855)
layout:setPercentWidth(0.5537)
layout:setPercentHeight(0.0093)
layout:setSize({width = 335.0000, height = 4.0000})
layout:setLeftMargin(183.9561)
layout:setRightMargin(86.0439)
layout:setTopMargin(176.2202)
layout:setBottomMargin(249.7798)
TopPanel:addChild(sliderNum)

--Create music
local music = cc.Sprite:create("game/WitchPoker/image/ui2/music.png")
music:setName("music")
music:setTag(85)
music:setCascadeColorEnabled(true)
music:setCascadeOpacityEnabled(true)
music:setPosition(125.7028, 255.8780)
layout = ccui.LayoutComponent:bindLayoutComponent(music)
layout:setPositionPercentX(0.2078)
layout:setPositionPercentY(0.5951)
layout:setPercentWidth(0.0810)
layout:setPercentHeight(0.1326)
layout:setSize({width = 49.0000, height = 57.0000})
layout:setLeftMargin(101.2028)
layout:setRightMargin(454.7972)
layout:setTopMargin(145.6220)
layout:setBottomMargin(227.3780)
music:setBlendFunc({src = 1, dst = 771})
TopPanel:addChild(music)

--Create effectTitle
local effectTitle = cc.Sprite:create("game/WitchPoker/image/ui2/effect.png")
effectTitle:setName("effectTitle")
effectTitle:setTag(84)
effectTitle:setCascadeColorEnabled(true)
effectTitle:setCascadeOpacityEnabled(true)
effectTitle:setPosition(128.7028, 140.7186)
layout = ccui.LayoutComponent:bindLayoutComponent(effectTitle)
layout:setPositionPercentX(0.2127)
layout:setPositionPercentY(0.3273)
layout:setPercentWidth(0.0711)
layout:setPercentHeight(0.1349)
layout:setSize({width = 43.0000, height = 58.0000})
layout:setLeftMargin(107.2028)
layout:setRightMargin(454.7972)
layout:setTopMargin(260.2814)
layout:setBottomMargin(111.7186)
effectTitle:setBlendFunc({src = 1, dst = 771})
TopPanel:addChild(effectTitle)

--Create sliderEffect
local sliderEffect = ccui.Slider:create()
sliderEffect:ignoreContentAdaptWithSize(false)
sliderEffect:loadBarTexture("game/WitchPoker/image/ui2/horizontalLine.png",0)
sliderEffect:loadProgressBarTexture("game/WitchPoker/image/ui2/horizontalLine.png",0)
sliderEffect:loadSlidBallTextureNormal("game/WitchPoker/image/ui2/point.png",0)
sliderEffect:loadSlidBallTexturePressed("game/WitchPoker/image/ui2/point.png",0)
sliderEffect:loadSlidBallTextureDisabled("game/WitchPoker/image/ui2/point.png",0)
sliderEffect:setPercent(50)
sliderEffect:setLayoutComponentEnabled(true)
sliderEffect:setName("sliderEffect")
sliderEffect:setTag(87)
sliderEffect:setCascadeColorEnabled(true)
sliderEffect:setCascadeOpacityEnabled(true)
sliderEffect:setPosition(351.4548, 135.0490)
layout = ccui.LayoutComponent:bindLayoutComponent(sliderEffect)
layout:setPositionPercentX(0.5809)
layout:setPositionPercentY(0.3141)
layout:setPercentWidth(0.5537)
layout:setPercentHeight(0.0093)
layout:setSize({width = 335.0000, height = 4.0000})
layout:setLeftMargin(183.9548)
layout:setRightMargin(86.0452)
layout:setTopMargin(292.9510)
layout:setBottomMargin(133.0490)
TopPanel:addChild(sliderEffect)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

