--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create shade
local shade = ccui.Layout:create()
shade:ignoreContentAdaptWithSize(false)
shade:setClippingEnabled(false)
shade:setBackGroundColorOpacity(102)
shade:setTouchEnabled(true);
shade:setLayoutComponentEnabled(true)
shade:setName("shade")
shade:setTag(67)
shade:setCascadeColorEnabled(true)
shade:setCascadeOpacityEnabled(true)
shade:setAnchorPoint(0.5000, 0.5000)
shade:setPosition(617.8492, 370.5795)
layout = ccui.LayoutComponent:bindLayoutComponent(shade)
layout:setPositionPercentX(0.4827)
layout:setPositionPercentY(0.5147)
layout:setPercentWidth(1.5625)
layout:setPercentHeight(2.0833)
layout:setSize({width = 2000.0000, height = 1500.0000})
layout:setLeftMargin(-382.1508)
layout:setRightMargin(-337.8491)
layout:setTopMargin(-400.5795)
layout:setBottomMargin(-379.4205)
Layer:addChild(shade)

--Create TopPanel
local TopPanel = ccui.Layout:create()
TopPanel:ignoreContentAdaptWithSize(false)
TopPanel:setClippingEnabled(false)
TopPanel:setBackGroundColorType(1)
TopPanel:setBackGroundColor({r = 127, g = 127, b = 127})
TopPanel:setBackGroundColorOpacity(102)
TopPanel:setTouchEnabled(true);
TopPanel:setLayoutComponentEnabled(true)
TopPanel:setName("TopPanel")
TopPanel:setTag(63)
TopPanel:setCascadeColorEnabled(true)
TopPanel:setCascadeOpacityEnabled(true)
TopPanel:setAnchorPoint(0.5000, 0.5000)
TopPanel:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TopPanel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(TopPanel)

--Create winText
local winText = ccui.Text:create()
winText:ignoreContentAdaptWithSize(true)
winText:setTextAreaSize({width = 0, height = 0})
winText:setFontName("")
winText:setFontSize(72)
winText:setString([[You Win]])
winText:setLayoutComponentEnabled(true)
winText:setName("winText")
winText:setTag(74)
winText:setCascadeColorEnabled(true)
winText:setCascadeOpacityEnabled(true)
winText:setPosition(644.3521, 407.3627)
winText:setTextColor({r = 127, g = 127, b = 127})
layout = ccui.LayoutComponent:bindLayoutComponent(winText)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5034)
layout:setPositionPercentY(0.5658)
layout:setPercentWidth(0.2031)
layout:setPercentHeight(0.1167)
layout:setSize({width = 260.0000, height = 84.0000})
layout:setLeftMargin(514.3521)
layout:setRightMargin(505.6479)
layout:setTopMargin(270.6373)
layout:setBottomMargin(365.3627)
TopPanel:addChild(winText)

--Create nextBtn
local nextBtn = ccui.Button:create()
nextBtn:ignoreContentAdaptWithSize(false)
nextBtn:loadTextureNormal("game/WitchPoker/image/ui2/continueBtn.png",0)
nextBtn:setTitleFontSize(14)
nextBtn:setTitleColor({r = 65, g = 65, b = 70})
nextBtn:setLayoutComponentEnabled(true)
nextBtn:setName("nextBtn")
nextBtn:setTag(64)
nextBtn:setCascadeColorEnabled(true)
nextBtn:setCascadeOpacityEnabled(true)
nextBtn:setPosition(646.5280, 267.1200)
layout = ccui.LayoutComponent:bindLayoutComponent(nextBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5051)
layout:setPositionPercentY(0.3710)
layout:setPercentWidth(0.0680)
layout:setPercentHeight(0.1208)
layout:setSize({width = 87.0000, height = 87.0000})
layout:setLeftMargin(603.0280)
layout:setRightMargin(589.9720)
layout:setTopMargin(409.3800)
layout:setBottomMargin(223.6200)
TopPanel:addChild(nextBtn)

--Create mainBtn
local mainBtn = ccui.Button:create()
mainBtn:ignoreContentAdaptWithSize(false)
mainBtn:loadTextureNormal("game/WitchPoker/image/ui2/exitBtn.png",0)
mainBtn:setTitleFontSize(14)
mainBtn:setTitleColor({r = 65, g = 65, b = 70})
mainBtn:setLayoutComponentEnabled(true)
mainBtn:setName("mainBtn")
mainBtn:setTag(66)
mainBtn:setCascadeColorEnabled(true)
mainBtn:setCascadeOpacityEnabled(true)
mainBtn:setPosition(515.4560, 267.1200)
layout = ccui.LayoutComponent:bindLayoutComponent(mainBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4027)
layout:setPositionPercentY(0.3710)
layout:setPercentWidth(0.0680)
layout:setPercentHeight(0.1208)
layout:setSize({width = 87.0000, height = 87.0000})
layout:setLeftMargin(471.9560)
layout:setRightMargin(721.0440)
layout:setTopMargin(409.3800)
layout:setBottomMargin(223.6200)
TopPanel:addChild(mainBtn)

--Create againBtn
local againBtn = ccui.Button:create()
againBtn:ignoreContentAdaptWithSize(false)
againBtn:loadTextureNormal("game/WitchPoker/image/ui2/refreshBtn.png",0)
againBtn:setTitleFontSize(14)
againBtn:setTitleColor({r = 65, g = 65, b = 70})
againBtn:setLayoutComponentEnabled(true)
againBtn:setName("againBtn")
againBtn:setTag(74)
againBtn:setCascadeColorEnabled(true)
againBtn:setCascadeOpacityEnabled(true)
againBtn:setPosition(784.0000, 266.4000)
layout = ccui.LayoutComponent:bindLayoutComponent(againBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.6125)
layout:setPositionPercentY(0.3700)
layout:setPercentWidth(0.0680)
layout:setPercentHeight(0.1208)
layout:setSize({width = 87.0000, height = 87.0000})
layout:setLeftMargin(740.5000)
layout:setRightMargin(452.5000)
layout:setTopMargin(410.1000)
layout:setBottomMargin(222.9000)
TopPanel:addChild(againBtn)

--Create loseText
local loseText = ccui.Text:create()
loseText:ignoreContentAdaptWithSize(true)
loseText:setTextAreaSize({width = 0, height = 0})
loseText:setFontName("")
loseText:setFontSize(72)
loseText:setString([[You Failed]])
loseText:setLayoutComponentEnabled(true)
loseText:setName("loseText")
loseText:setTag(72)
loseText:setCascadeColorEnabled(true)
loseText:setCascadeOpacityEnabled(true)
loseText:setPosition(640.0000, 408.7019)
loseText:setTextColor({r = 127, g = 127, b = 127})
layout = ccui.LayoutComponent:bindLayoutComponent(loseText)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5676)
layout:setPercentWidth(0.2492)
layout:setPercentHeight(0.1167)
layout:setSize({width = 319.0000, height = 84.0000})
layout:setLeftMargin(480.5000)
layout:setRightMargin(480.5000)
layout:setTopMargin(269.2981)
layout:setBottomMargin(366.7019)
TopPanel:addChild(loseText)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

