--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create shade
local shade = ccui.Layout:create()
shade:ignoreContentAdaptWithSize(false)
shade:setClippingEnabled(false)
shade:setBackGroundColorType(1)
shade:setBackGroundColor({r = 77, g = 77, b = 77})
shade:setBackGroundColorOpacity(102)
shade:setLayoutComponentEnabled(true)
shade:setName("shade")
shade:setTag(55)
shade:setCascadeColorEnabled(true)
shade:setCascadeOpacityEnabled(true)
shade:setAnchorPoint(0.5000, 0.5000)
shade:setPosition(365.4365, 640.0410)
layout = ccui.LayoutComponent:bindLayoutComponent(shade)
layout:setPositionPercentX(0.5076)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(2.7778)
layout:setPercentHeight(1.1719)
layout:setSize({width = 2000.0000, height = 1500.0000})
layout:setLeftMargin(-634.5635)
layout:setRightMargin(-645.4365)
layout:setTopMargin(-110.0410)
layout:setBottomMargin(-109.9590)
Layer:addChild(shade)

--Create TopPanel
local TopPanel = ccui.Layout:create()
TopPanel:ignoreContentAdaptWithSize(false)
TopPanel:setClippingEnabled(false)
TopPanel:setBackGroundColorOpacity(102)
TopPanel:setLayoutComponentEnabled(true)
TopPanel:setName("TopPanel")
TopPanel:setTag(33)
TopPanel:setCascadeColorEnabled(true)
TopPanel:setCascadeOpacityEnabled(true)
TopPanel:setAnchorPoint(0.5000, 0.5000)
TopPanel:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TopPanel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9972)
layout:setPercentHeight(0.4070)
layout:setSize({width = 718.0000, height = 521.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(1.0000)
layout:setTopMargin(379.5000)
layout:setBottomMargin(379.5000)
Layer:addChild(TopPanel)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/knight/images/bg2.png",0)
bg:setScale9Enabled(true)
bg:setCapInsets({x = 131, y = 140, width = 298, height = 287})
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(64)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(362.7435, 264.8071)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5052)
layout:setPositionPercentY(0.5083)
layout:setPercentWidth(1.0306)
layout:setPercentHeight(1.0883)
layout:setSize({width = 740.0000, height = 567.0000})
layout:setLeftMargin(-7.2565)
layout:setRightMargin(-14.7435)
layout:setTopMargin(-27.3071)
layout:setBottomMargin(-18.6929)
TopPanel:addChild(bg)

--Create effectTitle
local effectTitle = cc.Sprite:create("game/knight/images/music_icon2.png")
effectTitle:setName("effectTitle")
effectTitle:setTag(38)
effectTitle:setCascadeColorEnabled(true)
effectTitle:setCascadeOpacityEnabled(true)
effectTitle:setPosition(166.0000, 205.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(effectTitle)
layout:setPositionPercentX(0.2312)
layout:setPositionPercentY(0.3935)
layout:setPercentWidth(0.0808)
layout:setPercentHeight(0.1363)
layout:setSize({width = 58.0000, height = 71.0000})
layout:setLeftMargin(137.0000)
layout:setRightMargin(523.0000)
layout:setTopMargin(280.5000)
layout:setBottomMargin(169.5000)
effectTitle:setBlendFunc({src = 1, dst = 771})
TopPanel:addChild(effectTitle)

--Create musicTitle
local musicTitle = cc.Sprite:create("game/knight/images/music_icon1.png")
musicTitle:setName("musicTitle")
musicTitle:setTag(37)
musicTitle:setCascadeColorEnabled(true)
musicTitle:setCascadeOpacityEnabled(true)
musicTitle:setPosition(162.0000, 335.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(musicTitle)
layout:setPositionPercentX(0.2256)
layout:setPositionPercentY(0.6430)
layout:setPercentWidth(0.0877)
layout:setPercentHeight(0.1401)
layout:setSize({width = 63.0000, height = 73.0000})
layout:setLeftMargin(130.5000)
layout:setRightMargin(524.5000)
layout:setTopMargin(149.5000)
layout:setBottomMargin(298.5000)
musicTitle:setBlendFunc({src = 1, dst = 771})
TopPanel:addChild(musicTitle)

--Create sliderEffect
local sliderEffect = ccui.Slider:create()
sliderEffect:ignoreContentAdaptWithSize(false)
sliderEffect:loadBarTexture("game/knight/images/music_line.png",0)
sliderEffect:loadProgressBarTexture("game/knight/images/music_line.png",0)
sliderEffect:loadSlidBallTextureNormal("game/knight/images/music_point.png",0)
sliderEffect:loadSlidBallTexturePressed("game/knight/images/music_point.png",0)
sliderEffect:loadSlidBallTextureDisabled("game/knight/images/music_point.png",0)
sliderEffect:setPercent(50)
sliderEffect:setLayoutComponentEnabled(true)
sliderEffect:setName("sliderEffect")
sliderEffect:setTag(39)
sliderEffect:setCascadeColorEnabled(true)
sliderEffect:setCascadeOpacityEnabled(true)
sliderEffect:setPosition(407.2290, 202.1181)
layout = ccui.LayoutComponent:bindLayoutComponent(sliderEffect)
layout:setPositionPercentX(0.5672)
layout:setPositionPercentY(0.3879)
layout:setPercentWidth(0.4708)
layout:setPercentHeight(0.0921)
layout:setSize({width = 338.0000, height = 48.0000})
layout:setLeftMargin(238.2290)
layout:setRightMargin(141.7710)
layout:setTopMargin(294.8819)
layout:setBottomMargin(178.1181)
TopPanel:addChild(sliderEffect)

--Create sliderNum
local sliderNum = ccui.Slider:create()
sliderNum:ignoreContentAdaptWithSize(false)
sliderNum:loadBarTexture("game/knight/images/music_line.png",0)
sliderNum:loadProgressBarTexture("game/knight/images/music_line.png",0)
sliderNum:loadSlidBallTextureNormal("game/knight/images/music_point.png",0)
sliderNum:loadSlidBallTexturePressed("game/knight/images/music_point.png",0)
sliderNum:loadSlidBallTextureDisabled("game/knight/images/music_point.png",0)
sliderNum:setPercent(50)
sliderNum:setLayoutComponentEnabled(true)
sliderNum:setName("sliderNum")
sliderNum:setTag(36)
sliderNum:setCascadeColorEnabled(true)
sliderNum:setCascadeOpacityEnabled(true)
sliderNum:setPosition(398.4258, 336.5141)
layout = ccui.LayoutComponent:bindLayoutComponent(sliderNum)
layout:setPositionPercentX(0.5549)
layout:setPositionPercentY(0.6459)
layout:setPercentWidth(0.4708)
layout:setPercentHeight(0.0921)
layout:setSize({width = 338.0000, height = 48.0000})
layout:setLeftMargin(229.4258)
layout:setRightMargin(150.5742)
layout:setTopMargin(160.4859)
layout:setBottomMargin(312.5141)
TopPanel:addChild(sliderNum)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

