--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/ligatureFootball/gameLayer/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(359)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(bg)

--Create role
local role = ccui.ImageView:create()
role:ignoreContentAdaptWithSize(false)
role:loadTexture("game/ligatureFootball/chooseLayer/role.png",0)
role:setLayoutComponentEnabled(true)
role:setName("role")
role:setTag(358)
role:setCascadeColorEnabled(true)
role:setCascadeOpacityEnabled(true)
role:setAnchorPoint(0.5000, 0.0000)
role:setPosition(360.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(role)
layout:setPositionPercentX(0.2813)
layout:setPercentWidth(0.1625)
layout:setPercentHeight(0.8986)
layout:setSize({width = 208.0000, height = 647.0000})
layout:setLeftMargin(256.0000)
layout:setRightMargin(816.0000)
layout:setTopMargin(73.0000)
Layer:addChild(role)

--Create btn_help
local btn_help = ccui.Button:create()
btn_help:ignoreContentAdaptWithSize(false)
btn_help:loadTextureNormal("game/ligatureFootball/gamebtn/UI_guize.png",0)
btn_help:setTitleFontSize(14)
btn_help:setTitleColor({r = 65, g = 65, b = 70})
btn_help:setScale9Enabled(true)
btn_help:setCapInsets({x = 15, y = 11, width = 137, height = 145})
btn_help:setLayoutComponentEnabled(true)
btn_help:setName("btn_help")
btn_help:setTag(354)
btn_help:setCascadeColorEnabled(true)
btn_help:setCascadeOpacityEnabled(true)
btn_help:setPosition(977.1816, 181.6882)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_help)
layout:setPositionPercentX(0.7634)
layout:setPositionPercentY(0.2523)
layout:setPercentWidth(0.1305)
layout:setPercentHeight(0.2319)
layout:setSize({width = 167.0000, height = 167.0000})
layout:setLeftMargin(893.6816)
layout:setRightMargin(219.3184)
layout:setTopMargin(454.8118)
layout:setBottomMargin(98.1882)
Layer:addChild(btn_help)

--Create btn_music_off
local btn_music_off = ccui.Button:create()
btn_music_off:ignoreContentAdaptWithSize(false)
btn_music_off:loadTextureNormal("game/ligatureFootball/gamebtn/UI_music_2.png",0)
btn_music_off:loadTexturePressed("game/ligatureFootball/gamebtn/UI_music_2.png",0)
btn_music_off:loadTextureDisabled("game/ligatureFootball/gamebtn/UI_music_2.png",0)
btn_music_off:setTitleFontSize(14)
btn_music_off:setTitleColor({r = 65, g = 65, b = 70})
btn_music_off:setLayoutComponentEnabled(true)
btn_music_off:setName("btn_music_off")
btn_music_off:setTag(355)
btn_music_off:setCascadeColorEnabled(true)
btn_music_off:setCascadeOpacityEnabled(true)
btn_music_off:setPosition(664.3472, 181.0744)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_music_off)
layout:setPositionPercentX(0.5190)
layout:setPositionPercentY(0.2515)
layout:setPercentWidth(0.1305)
layout:setPercentHeight(0.2319)
layout:setSize({width = 167.0000, height = 167.0000})
layout:setLeftMargin(580.8472)
layout:setRightMargin(532.1528)
layout:setTopMargin(455.4256)
layout:setBottomMargin(97.5744)
Layer:addChild(btn_music_off)

--Create btn_music_on
local btn_music_on = ccui.Button:create()
btn_music_on:ignoreContentAdaptWithSize(false)
btn_music_on:loadTextureNormal("game/ligatureFootball/gamebtn/UI_music_1.png",0)
btn_music_on:loadTexturePressed("game/ligatureFootball/gamebtn/UI_music_1.png",0)
btn_music_on:loadTextureDisabled("game/ligatureFootball/gamebtn/UI_music_1.png",0)
btn_music_on:setTitleFontSize(14)
btn_music_on:setTitleColor({r = 65, g = 65, b = 70})
btn_music_on:setLayoutComponentEnabled(true)
btn_music_on:setName("btn_music_on")
btn_music_on:setTag(356)
btn_music_on:setCascadeColorEnabled(true)
btn_music_on:setCascadeOpacityEnabled(true)
btn_music_on:setPosition(664.3472, 181.0744)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_music_on)
layout:setPositionPercentX(0.5190)
layout:setPositionPercentY(0.2515)
layout:setPercentWidth(0.1305)
layout:setPercentHeight(0.2319)
layout:setSize({width = 167.0000, height = 167.0000})
layout:setLeftMargin(580.8472)
layout:setRightMargin(532.1528)
layout:setTopMargin(455.4256)
layout:setBottomMargin(97.5744)
Layer:addChild(btn_music_on)

--Create btn_start
local btn_start = ccui.Button:create()
btn_start:ignoreContentAdaptWithSize(false)
btn_start:loadTextureNormal("game/ligatureFootball/gamebtn/UI_START.png",0)
btn_start:loadTexturePressed("game/ligatureFootball/gamebtn/UI_START.png",0)
btn_start:loadTextureDisabled("game/ligatureFootball/gamebtn/UI_START.png",0)
btn_start:setTitleFontSize(14)
btn_start:setTitleColor({r = 65, g = 65, b = 70})
btn_start:setLayoutComponentEnabled(true)
btn_start:setName("btn_start")
btn_start:setTag(357)
btn_start:setCascadeColorEnabled(true)
btn_start:setCascadeOpacityEnabled(true)
btn_start:setPosition(814.2200, 465.7287)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_start)
layout:setPositionPercentX(0.6361)
layout:setPositionPercentY(0.6468)
layout:setPercentWidth(0.1773)
layout:setPercentHeight(0.3236)
layout:setSize({width = 227.0000, height = 233.0000})
layout:setLeftMargin(700.7200)
layout:setRightMargin(352.2800)
layout:setTopMargin(137.7713)
layout:setBottomMargin(349.2287)
Layer:addChild(btn_start)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

