--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = import("..LuaExtend")
local cfg = import(".InnerGoCfg")
local goUI = cfg.goUI

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1136.0000, height = 640.0000})

--Create Image_11
-- local Image_11 = ccui.ImageView:create()
-- Image_11:ignoreContentAdaptWithSize(false)
-- Image_11:loadTexture("game/pdk/image/mainview/hall_bg.png",0)
-- Image_11:setScale9Enabled(true)
-- Image_11:setCapInsets({x = 640, y = 360, width = 1, height = 1})
-- Image_11:setLayoutComponentEnabled(true)
-- Image_11:setName("Image_11")
-- Image_11:setTag(189)
-- Image_11:setCascadeColorEnabled(true)
-- Image_11:setCascadeOpacityEnabled(true)
-- Image_11:setPosition(640.0000, 358.9920)
-- layout = ccui.LayoutComponent:bindLayoutComponent(Image_11)
-- layout:setPositionPercentXEnabled(true)
-- layout:setPositionPercentYEnabled(true)
-- layout:setPositionPercentX(0.5000)
-- layout:setPositionPercentY(0.4986)
-- layout:setPercentWidthEnabled(true)
-- layout:setPercentHeightEnabled(true)
-- layout:setPercentWidth(1.0000)
-- layout:setPercentHeight(1.0000)
-- layout:setSize({width = 1280.0000, height = 720.0000})
-- layout:setTopMargin(1.0080)
-- layout:setBottomMargin(-1.0080)
-- Layer:addChild(Image_11)

--Create pnl
local pnl = ccui.Layout:create()
pnl:ignoreContentAdaptWithSize(false)
pnl:setClippingEnabled(false)
pnl:setBackGroundColorOpacity(102)
pnl:setTouchEnabled(true);
pnl:setLayoutComponentEnabled(true)
pnl:setName("pnl")
pnl:setTag(93)
pnl:setCascadeColorEnabled(true)
pnl:setCascadeOpacityEnabled(true)
if callBackProvider~=nil then
      pnl:addClickEventListener(callBackProvider("InnerGo.lua", pnl, "onbtnBackClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(pnl)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
Layer:addChild(pnl)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture(goUI.bg,0)
bg:setTouchEnabled(true);
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(701)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(568.0005, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 800.0000, height = 360})
layout:setLeftMargin(-3.9995)
layout:setRightMargin(3.9995)
Layer:addChild(bg)

--Create innergo_item
local innergo_item = ccui.Layout:create()
innergo_item:ignoreContentAdaptWithSize(false)
innergo_item:setClippingEnabled(false)
innergo_item:setBackGroundColorOpacity(102)
innergo_item:setTouchEnabled(true);
innergo_item:setLayoutComponentEnabled(true)
innergo_item:setName("innergo_item")
innergo_item:setTag(1)
innergo_item:setCascadeColorEnabled(true)
innergo_item:setCascadeOpacityEnabled(true)
innergo_item:setPosition(-356.5278, 183.6948)
innergo_item:setScaleX(0.9000)
innergo_item:setScaleY(0.9000)
if callBackProvider~=nil then
      innergo_item:addClickEventListener(callBackProvider("InnerGo.lua", innergo_item, "onbuyItemClick"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(innergo_item)
layout:setPositionPercentX(-0.3138)
layout:setPositionPercentY(0.2870)
layout:setPercentWidth(0.1937)
layout:setPercentHeight(0.5156)
layout:setSize({width = 220.0000, height = 330.0000})
layout:setLeftMargin(-356.5278)
layout:setRightMargin(1272.5280)
layout:setTopMargin(126.3052)
layout:setBottomMargin(183.6948)
Layer:addChild(innergo_item)

--Create Image_3
-- local Image_3 = ccui.ImageView:create()
-- Image_3:ignoreContentAdaptWithSize(false)
-- Image_3:loadTexture(goUI.goitem_bg,0)
-- Image_3:setLayoutComponentEnabled(true)
-- Image_3:setName("Image_3")
-- Image_3:setTag(71)
-- Image_3:setCascadeColorEnabled(true)
-- Image_3:setCascadeOpacityEnabled(true)
-- Image_3:setPosition(109.6132, 311.3604)
-- layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
-- layout:setPositionPercentX(0.4982)
-- layout:setPositionPercentY(0.9435)
-- layout:setPercentWidth(0.8273)
-- layout:setPercentHeight(0.1364)
-- layout:setSize({width = 182.0000, height = 45.0000})
-- layout:setLeftMargin(18.6132)
-- layout:setRightMargin(19.3868)
-- layout:setTopMargin(-3.8604)
-- layout:setBottomMargin(288.8604)
-- innergo_item:addChild(Image_3)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture(goUI.goitem_bg,0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(170)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(111.0000, 188.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentX(0.5045)
layout:setPositionPercentY(0.5712)
layout:setPercentWidth(0.9091)
layout:setPercentHeight(0.6061)
layout:setSize({width = 200.0000, height = 260.0000})
layout:setLeftMargin(11.0000)
layout:setRightMargin(9.0000)
layout:setTopMargin(41.5000)
layout:setBottomMargin(88.5000)
innergo_item:addChild(Image_2)

--Create desc1
local desc1 = ccui.Text:create()
desc1:ignoreContentAdaptWithSize(true)
desc1:setTextAreaSize({width = 0, height = 0})
desc1:setFontSize(26)
desc1:setString([[600金币]])
desc1:setLayoutComponentEnabled(true)
desc1:setName("desc1")
desc1:setTag(174)
desc1:setCascadeColorEnabled(true)
desc1:setCascadeOpacityEnabled(true)
desc1:setPosition(109.8066, 309.8412)
desc1:setTextColor({r = 255, g = 249, b = 207})
layout = ccui.LayoutComponent:bindLayoutComponent(desc1)
layout:setPositionPercentX(0.4991)
layout:setPositionPercentY(0.9389)
layout:setPercentWidth(0.4364)
layout:setPercentHeight(0.0939)
layout:setSize({width = 96.0000, height = 31.0000})
layout:setLeftMargin(61.8066)
layout:setRightMargin(62.1934)
layout:setTopMargin(4.6588)
layout:setBottomMargin(294.3412)
innergo_item:addChild(desc1)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("game/pdk/image/mainview/shop_item_text_bg.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(172)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(110.0000, 83.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2530)
layout:setPercentWidth(0.8273)
layout:setPercentHeight(0.1364)
layout:setSize({width = 182.0000, height = 45.0000})
layout:setLeftMargin(19.0000)
layout:setRightMargin(19.0000)
layout:setTopMargin(224.0000)
layout:setBottomMargin(61.0000)
innergo_item:addChild(Image_1)

--Create price1
local price1 = ccui.Text:create()
price1:ignoreContentAdaptWithSize(true)
price1:setTextAreaSize({width = 0, height = 0})
price1:setFontSize(30)
price1:setString([[¥6]])
price1:setLayoutComponentEnabled(true)
price1:setName("price1")
price1:setTag(173)
price1:setCascadeColorEnabled(true)
price1:setCascadeOpacityEnabled(true)
price1:setAnchorPoint(0.5000, 0.5441)
price1:setPosition(109.8066, 86.0000)
price1:setTextColor({r = 255, g = 249, b = 207})
layout = ccui.LayoutComponent:bindLayoutComponent(price1)
layout:setPositionPercentX(0.4991)
layout:setPositionPercentY(0.2606)
layout:setPercentWidth(0.1545)
layout:setPercentHeight(0.1030)
layout:setSize({width = 34.0000, height = 34.0000})
layout:setLeftMargin(92.8066)
layout:setRightMargin(93.1934)
layout:setTopMargin(228.4994)
layout:setBottomMargin(67.5006)
innergo_item:addChild(price1)

--Create list
local list = ccui.ListView:create()
list:setDirection(2)
list:setGravity(3)
list:ignoreContentAdaptWithSize(false)
list:setClippingEnabled(true)
list:setBackGroundColorOpacity(102)
list:setTouchEnabled(false);
list:setLayoutComponentEnabled(true)
list:setName("list")
list:setTag(158)
list:setCascadeColorEnabled(true)
list:setCascadeOpacityEnabled(true)
list:setVisible(true)
list:setPosition(300.8625, 164.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(list)
layout:setPositionPercentX(0.2648)
layout:setPositionPercentY(0.2875)
layout:setPercentWidth(0.5282)
layout:setPercentHeight(0.4813)
layout:setSize({width = 600.0000, height = 308.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(300.8625)
layout:setRightMargin(235.1375)
layout:setTopMargin(148.0000)
layout:setBottomMargin(184.0000)
Layer:addChild(list)

--Create title
local title = ccui.Text:create()
title:ignoreContentAdaptWithSize(true)
title:setTextAreaSize({width = 0, height = 0})
title:setFontName("game/pdk/image/FZY3JW.TTF")
title:setFontSize(48)
title:setString([[商城]])
title:setLayoutComponentEnabled(true)
title:setName("title")
title:setTag(360)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setPosition(568.0000, 497.6546)
title:setTextColor({r = 0, g = 0, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.7776)
layout:setPercentWidth(0.0863)
layout:setPercentHeight(0.0875)
layout:setSize({width = 98.0000, height = 56.0000})
layout:setLeftMargin(519.0000)
layout:setRightMargin(519.0000)
layout:setTopMargin(114.3454)
layout:setBottomMargin(469.6546)
Layer:addChild(title)

--Create btnBack
local btnBack = ccui.Button:create()
btnBack:ignoreContentAdaptWithSize(false)
btnBack:loadTextureNormal("game/pdk/image/mainview/btn_return.png",0)
btnBack:setTitleFontSize(14)
btnBack:setTitleColor({r = 65, g = 65, b = 70})
btnBack:setLayoutComponentEnabled(true)
btnBack:setName("btnBack")
btnBack:setTag(258)
btnBack:setCascadeColorEnabled(true)
btnBack:setCascadeOpacityEnabled(true)
btnBack:setPosition(62.6516, 587.5200)
layout = ccui.LayoutComponent:bindLayoutComponent(btnBack)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0552)
layout:setPositionPercentY(0.9180)
layout:setPercentWidth(0.0863)
layout:setPercentHeight(0.1531)
layout:setSize({width = 98.0000, height = 98.0000})
layout:setHorizontalEdge(1)
layout:setLeftMargin(13.6516)
layout:setRightMargin(1024.3480)
layout:setTopMargin(3.4800)
layout:setBottomMargin(538.5200)
Layer:addChild(btnBack)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List
local uiEnter = {name="uiEnter", startIndex=0, endIndex=30}
result['animation']:addAnimationInfo(uiEnter)
local uiExit = {name="uiExit", startIndex=30, endIndex=60}
result['animation']:addAnimationInfo(uiExit)

result['root'] = Layer
return result;
end

return Result

