--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create pnl
local pnl = ccui.Layout:create()
pnl:ignoreContentAdaptWithSize(false)
pnl:setClippingEnabled(false)
pnl:setBackGroundColorOpacity(102)
pnl:setTouchEnabled(true);
pnl:setLayoutComponentEnabled(true)
pnl:setName("pnl")
pnl:setTag(145)
pnl:setCascadeColorEnabled(true)
pnl:setCascadeOpacityEnabled(true)
pnl:setPosition(248.9400, 120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(pnl)
layout:setPositionPercentX(0.1945)
layout:setPositionPercentY(0.1667)
layout:setPercentWidth(0.6250)
layout:setPercentHeight(0.6944)
layout:setSize({width = 800.0000, height = 500.0000})
layout:setLeftMargin(248.9400)
layout:setRightMargin(231.0601)
layout:setTopMargin(100.0000)
layout:setBottomMargin(120.0000)
Layer:addChild(pnl)

--Create Image_9
local Image_9 = ccui.ImageView:create()
Image_9:ignoreContentAdaptWithSize(false)
Image_9:loadTexture("game/chuidizhu/image/gameover/gameEndBg.png",0)
Image_9:setLayoutComponentEnabled(true)
Image_9:setName("Image_9")
Image_9:setTag(77)
Image_9:setCascadeColorEnabled(true)
Image_9:setCascadeOpacityEnabled(true)
Image_9:setPosition(377.6666, 256.7321)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_9)
layout:setPositionPercentX(0.4721)
layout:setPositionPercentY(0.5135)
layout:setPercentWidth(0.8650)
layout:setPercentHeight(0.9280)
layout:setSize({width = 692.0000, height = 464.0000})
layout:setLeftMargin(31.6666)
layout:setRightMargin(76.3334)
layout:setTopMargin(11.2679)
layout:setBottomMargin(24.7321)
pnl:addChild(Image_9)

--Create textScore
local textScore = ccui.Text:create()
textScore:ignoreContentAdaptWithSize(true)
textScore:setTextAreaSize({width = 0, height = 0})
textScore:setFontSize(40)
textScore:setString([[得分:]])
textScore:setTextHorizontalAlignment(1)
textScore:setLayoutComponentEnabled(true)
textScore:setName("textScore")
textScore:setTag(80)
textScore:setCascadeColorEnabled(true)
textScore:setCascadeOpacityEnabled(true)
textScore:setPosition(279.2805, 295.0573)
textScore:setTextColor({r = 146, g = 238, b = 144})
layout = ccui.LayoutComponent:bindLayoutComponent(textScore)
layout:setPositionPercentX(0.3491)
layout:setPositionPercentY(0.5901)
layout:setPercentWidth(0.1150)
layout:setPercentHeight(0.0900)
layout:setSize({width = 92.0000, height = 45.0000})
layout:setLeftMargin(233.2805)
layout:setRightMargin(474.7195)
layout:setTopMargin(182.4427)
layout:setBottomMargin(272.5573)
pnl:addChild(textScore)

--Create Score
local Score = ccui.Text:create()
Score:ignoreContentAdaptWithSize(true)
Score:setTextAreaSize({width = 0, height = 0})
Score:setFontSize(40)
Score:setString([[1000]])
Score:setTextHorizontalAlignment(1)
Score:setLayoutComponentEnabled(true)
Score:setName("Score")
Score:setTag(81)
Score:setCascadeColorEnabled(true)
Score:setCascadeOpacityEnabled(true)
Score:setAnchorPoint(0.0000, 0.5000)
Score:setPosition(383.1049, 295.0573)
Score:setTextColor({r = 146, g = 238, b = 144})
layout = ccui.LayoutComponent:bindLayoutComponent(Score)
layout:setPositionPercentX(0.4789)
layout:setPositionPercentY(0.5901)
layout:setPercentWidth(0.1112)
layout:setPercentHeight(0.0900)
layout:setSize({width = 89.0000, height = 45.0000})
layout:setLeftMargin(383.1049)
layout:setRightMargin(327.8951)
layout:setTopMargin(182.4427)
layout:setBottomMargin(272.5573)
pnl:addChild(Score)

--Create btnRetry
local btnRetry = ccui.Button:create()
btnRetry:ignoreContentAdaptWithSize(false)
btnRetry:loadTextureNormal("game/chuidizhu/image/gameover/btnReplay.png",0)
btnRetry:setTitleFontSize(14)
btnRetry:setTitleColor({r = 65, g = 65, b = 70})
btnRetry:setScale9Enabled(true)
btnRetry:setCapInsets({x = 15, y = 11, width = 204, height = 67})
btnRetry:setLayoutComponentEnabled(true)
btnRetry:setName("btnRetry")
btnRetry:setTag(150)
btnRetry:setCascadeColorEnabled(true)
btnRetry:setCascadeOpacityEnabled(true)
btnRetry:setPosition(526.2740, 130.8461)
if callBackProvider~=nil then
      btnRetry:addClickEventListener(callBackProvider("balance.lua", btnRetry, "onReplay"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnRetry)
layout:setPositionPercentX(0.6578)
layout:setPositionPercentY(0.2617)
layout:setPercentWidth(0.2925)
layout:setPercentHeight(0.1780)
layout:setSize({width = 234.0000, height = 89.0000})
layout:setLeftMargin(409.2740)
layout:setRightMargin(156.7260)
layout:setTopMargin(324.6539)
layout:setBottomMargin(86.3461)
pnl:addChild(btnRetry)

--Create btnBack
local btnBack = ccui.Button:create()
btnBack:ignoreContentAdaptWithSize(false)
btnBack:loadTextureNormal("game/chuidizhu/image/gameover/btnBack.png",0)
btnBack:setTitleFontSize(14)
btnBack:setTitleColor({r = 65, g = 65, b = 70})
btnBack:setScale9Enabled(true)
btnBack:setCapInsets({x = 15, y = 11, width = 204, height = 67})
btnBack:setLayoutComponentEnabled(true)
btnBack:setName("btnBack")
btnBack:setTag(151)
btnBack:setCascadeColorEnabled(true)
btnBack:setCascadeOpacityEnabled(true)
btnBack:setPosition(266.3061, 130.8461)
if callBackProvider~=nil then
      btnBack:addClickEventListener(callBackProvider("balance.lua", btnBack, "onBack"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnBack)
layout:setPositionPercentX(0.3329)
layout:setPositionPercentY(0.2617)
layout:setPercentWidth(0.2925)
layout:setPercentHeight(0.1780)
layout:setSize({width = 234.0000, height = 89.0000})
layout:setLeftMargin(149.3061)
layout:setRightMargin(416.6939)
layout:setTopMargin(324.6539)
layout:setBottomMargin(86.3461)
pnl:addChild(btnBack)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

