--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/chuidizhu/image/BG.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(94)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(639.9997, 359.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(-0.0003)
layout:setRightMargin(0.0002)
layout:setTopMargin(0.0001)
layout:setBottomMargin(-0.0001)
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Layer:addChild(bg)

--Create role
local role = cc.Sprite:create("game/chuidizhu/image/game/role.png")
role:setName("role")
role:setTag(93)
role:setCascadeColorEnabled(true)
role:setCascadeOpacityEnabled(true)
role:setAnchorPoint(0.5000, 0.0000)
role:setPosition(640.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(role)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(0.5078)
layout:setPercentHeight(0.9444)
layout:setSize({width = 650.0000, height = 680.0000})
layout:setLeftMargin(315.0000)
layout:setRightMargin(315.0000)
layout:setTopMargin(40.0000)
role:setBlendFunc({src = 1, dst = 771})
Layer:addChild(role)

--Create btnUnlimit
local btnUnlimit = ccui.Button:create()
btnUnlimit:ignoreContentAdaptWithSize(false)
btnUnlimit:loadTextureNormal("game/chuidizhu/image/main/unlimit_model.png",0)
btnUnlimit:setTitleFontSize(14)
btnUnlimit:setTitleColor({r = 65, g = 65, b = 70})
btnUnlimit:setScale9Enabled(true)
btnUnlimit:setCapInsets({x = 15, y = 11, width = 359, height = 89})
btnUnlimit:setLayoutComponentEnabled(true)
btnUnlimit:setName("btnUnlimit")
btnUnlimit:setTag(91)
btnUnlimit:setCascadeColorEnabled(true)
btnUnlimit:setCascadeOpacityEnabled(true)
btnUnlimit:setPosition(891.0000, 162.5599)
if callBackProvider~=nil then
      btnUnlimit:addClickEventListener(callBackProvider("main_2.lua", btnUnlimit, "onUnlimitGame"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnUnlimit)
layout:setPositionPercentX(0.6961)
layout:setPositionPercentY(0.2258)
layout:setPercentWidth(0.3039)
layout:setPercentHeight(0.1542)
layout:setSize({width = 389.0000, height = 111.0000})
layout:setLeftMargin(696.5000)
layout:setRightMargin(194.5000)
layout:setTopMargin(501.9401)
layout:setBottomMargin(107.0599)
Layer:addChild(btnUnlimit)

--Create btnGame
local btnGame = ccui.Button:create()
btnGame:ignoreContentAdaptWithSize(false)
btnGame:loadTextureNormal("game/chuidizhu/image/main/gamemodel.png",0)
btnGame:setTitleFontSize(14)
btnGame:setTitleColor({r = 65, g = 65, b = 70})
btnGame:setScale9Enabled(true)
btnGame:setCapInsets({x = 15, y = 11, width = 359, height = 89})
btnGame:setLayoutComponentEnabled(true)
btnGame:setName("btnGame")
btnGame:setTag(92)
btnGame:setCascadeColorEnabled(true)
btnGame:setCascadeOpacityEnabled(true)
btnGame:setPosition(417.0000, 159.5599)
if callBackProvider~=nil then
      btnGame:addClickEventListener(callBackProvider("main_2.lua", btnGame, "onGame"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnGame)
layout:setPositionPercentX(0.3258)
layout:setPositionPercentY(0.2216)
layout:setPercentWidth(0.3039)
layout:setPercentHeight(0.1542)
layout:setSize({width = 389.0000, height = 111.0000})
layout:setLeftMargin(222.5000)
layout:setRightMargin(668.5000)
layout:setTopMargin(504.9401)
layout:setBottomMargin(104.0599)
Layer:addChild(btnGame)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

