--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create pnl
local pnl = ccui.Layout:create()
pnl:ignoreContentAdaptWithSize(false)
pnl:setClippingEnabled(false)
pnl:setBackGroundColorOpacity(102)
pnl:setTouchEnabled(true);
pnl:setLayoutComponentEnabled(true)
pnl:setName("pnl")
pnl:setTag(157)
pnl:setCascadeColorEnabled(true)
pnl:setCascadeOpacityEnabled(true)
pnl:setPosition(248.9400, 120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(pnl)
layout:setPositionPercentX(0.1945)
layout:setPositionPercentY(0.1667)
layout:setPercentWidth(0.6250)
layout:setPercentHeight(0.6944)
layout:setSize({width = 800.0000, height = 500.0000})
layout:setLeftMargin(248.9400)
layout:setRightMargin(231.0601)
layout:setTopMargin(100.0000)
layout:setBottomMargin(120.0000)
Layer:addChild(pnl)

--Create Image_9
local Image_9 = ccui.ImageView:create()
Image_9:ignoreContentAdaptWithSize(false)
Image_9:loadTexture("game/chuidizhu/image/pause/pauseBg.png",0)
Image_9:setLayoutComponentEnabled(true)
Image_9:setName("Image_9")
Image_9:setTag(158)
Image_9:setCascadeColorEnabled(true)
Image_9:setCascadeOpacityEnabled(true)
Image_9:setPosition(377.6666, 256.7321)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_9)
layout:setPositionPercentX(0.4721)
layout:setPositionPercentY(0.5135)
layout:setPercentWidth(0.8650)
layout:setPercentHeight(0.9280)
layout:setSize({width = 692.0000, height = 464.0000})
layout:setLeftMargin(31.6666)
layout:setRightMargin(76.3334)
layout:setTopMargin(11.2679)
layout:setBottomMargin(24.7321)
pnl:addChild(Image_9)

--Create btnRetry
local btnRetry = ccui.Button:create()
btnRetry:ignoreContentAdaptWithSize(false)
btnRetry:loadTextureNormal("game/chuidizhu/image/gameover/btnReplay.png",0)
btnRetry:setTitleFontSize(14)
btnRetry:setTitleColor({r = 65, g = 65, b = 70})
btnRetry:setScale9Enabled(true)
btnRetry:setCapInsets({x = 15, y = 11, width = 204, height = 67})
btnRetry:setLayoutComponentEnabled(true)
btnRetry:setName("btnRetry")
btnRetry:setTag(161)
btnRetry:setCascadeColorEnabled(true)
btnRetry:setCascadeOpacityEnabled(true)
btnRetry:setPosition(377.6664, 221.3466)
if callBackProvider~=nil then
      btnRetry:addClickEventListener(callBackProvider("setting.lua", btnRetry, "onReplay"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnRetry)
layout:setPositionPercentX(0.4721)
layout:setPositionPercentY(0.4427)
layout:setPercentWidth(0.2925)
layout:setPercentHeight(0.1780)
layout:setSize({width = 234.0000, height = 89.0000})
layout:setLeftMargin(260.6664)
layout:setRightMargin(305.3336)
layout:setTopMargin(234.1534)
layout:setBottomMargin(176.8466)
pnl:addChild(btnRetry)

--Create btnBack
local btnBack = ccui.Button:create()
btnBack:ignoreContentAdaptWithSize(false)
btnBack:loadTextureNormal("game/chuidizhu/image/gameover/btnBack.png",0)
btnBack:setTitleFontSize(14)
btnBack:setTitleColor({r = 65, g = 65, b = 70})
btnBack:setScale9Enabled(true)
btnBack:setCapInsets({x = 15, y = 11, width = 204, height = 67})
btnBack:setLayoutComponentEnabled(true)
btnBack:setName("btnBack")
btnBack:setTag(162)
btnBack:setCascadeColorEnabled(true)
btnBack:setCascadeOpacityEnabled(true)
btnBack:setPosition(377.6666, 120.9710)
if callBackProvider~=nil then
      btnBack:addClickEventListener(callBackProvider("setting.lua", btnBack, "onBack"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnBack)
layout:setPositionPercentX(0.4721)
layout:setPositionPercentY(0.2419)
layout:setPercentWidth(0.2925)
layout:setPercentHeight(0.1780)
layout:setSize({width = 234.0000, height = 89.0000})
layout:setLeftMargin(260.6666)
layout:setRightMargin(305.3334)
layout:setTopMargin(334.5290)
layout:setBottomMargin(76.4710)
pnl:addChild(btnBack)

--Create btnRetry_0
local btnRetry_0 = ccui.Button:create()
btnRetry_0:ignoreContentAdaptWithSize(false)
btnRetry_0:loadTextureNormal("game/chuidizhu/image/pause/btnContinue.png",0)
btnRetry_0:setTitleFontSize(14)
btnRetry_0:setTitleColor({r = 65, g = 65, b = 70})
btnRetry_0:setScale9Enabled(true)
btnRetry_0:setCapInsets({x = 15, y = 11, width = 204, height = 67})
btnRetry_0:setLayoutComponentEnabled(true)
btnRetry_0:setName("btnRetry_0")
btnRetry_0:setTag(163)
btnRetry_0:setCascadeColorEnabled(true)
btnRetry_0:setCascadeOpacityEnabled(true)
btnRetry_0:setPosition(377.6667, 319.7527)
if callBackProvider~=nil then
      btnRetry_0:addClickEventListener(callBackProvider("setting.lua", btnRetry_0, "onContinue"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(btnRetry_0)
layout:setPositionPercentX(0.4721)
layout:setPositionPercentY(0.6395)
layout:setPercentWidth(0.2925)
layout:setPercentHeight(0.1780)
layout:setSize({width = 234.0000, height = 89.0000})
layout:setLeftMargin(260.6667)
layout:setRightMargin(305.3333)
layout:setTopMargin(135.7473)
layout:setBottomMargin(275.2527)
pnl:addChild(btnRetry_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

