--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("game/ligatureFootball/gameLayer/bg_scene.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(98)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setAnchorPoint(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
Layer:addChild(bg)

--Create wang
local wang = cc.Sprite:create("game/ligatureFootball/gameLayer/goal.png")
wang:setName("wang")
wang:setTag(97)
wang:setCascadeColorEnabled(true)
wang:setCascadeOpacityEnabled(true)
wang:setPosition(1211.3560, 359.4759)
layout = ccui.LayoutComponent:bindLayoutComponent(wang)
layout:setPositionPercentX(0.9464)
layout:setPositionPercentY(0.4993)
layout:setPercentWidth(0.0977)
layout:setPercentHeight(0.7667)
layout:setSize({width = 125.0000, height = 552.0000})
layout:setLeftMargin(1148.8560)
layout:setRightMargin(6.1436)
layout:setTopMargin(84.5241)
layout:setBottomMargin(83.4759)
wang:setBlendFunc({src = 1, dst = 771})
Layer:addChild(wang)

--Create enemyLayer
local enemyLayer=cc.Node:create()
enemyLayer:setName("enemyLayer")
enemyLayer:setTag(96)
enemyLayer:setCascadeColorEnabled(true)
enemyLayer:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(enemyLayer)
layout:setRightMargin(1280.0000)
layout:setTopMargin(720.0000)
Layer:addChild(enemyLayer)

--Create name_level
local name_level = ccui.Text:create()
name_level:ignoreContentAdaptWithSize(true)
name_level:setTextAreaSize({width = 0, height = 0})
name_level:setFontName("game/ligatureFootball/font.ttf")
name_level:setFontSize(40)
name_level:setString([[关
卡]])
name_level:setLayoutComponentEnabled(true)
name_level:setName("name_level")
name_level:setTag(28)
name_level:setCascadeColorEnabled(true)
name_level:setCascadeOpacityEnabled(true)
name_level:setPosition(51.0000, 395.0000)
name_level:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(name_level)
layout:setPositionPercentX(0.0398)
layout:setPositionPercentY(0.5486)
layout:setPercentWidth(0.0328)
layout:setPercentHeight(0.1278)
layout:setSize({width = 42.0000, height = 92.0000})
layout:setLeftMargin(30.0000)
layout:setRightMargin(1208.0000)
layout:setTopMargin(279.0000)
layout:setBottomMargin(349.0000)
Layer:addChild(name_level)

--Create num_level
local num_level = ccui.Text:create()
num_level:ignoreContentAdaptWithSize(true)
num_level:setTextAreaSize({width = 0, height = 0})
num_level:setFontName("game/ligatureFootball/font.ttf")
num_level:setFontSize(40)
num_level:setString([[25]])
num_level:setLayoutComponentEnabled(true)
num_level:setName("num_level")
num_level:setTag(94)
num_level:setCascadeColorEnabled(true)
num_level:setCascadeOpacityEnabled(true)
num_level:setPosition(51.5000, 314.8256)
num_level:setTextColor({r = 255, g = 255, b = 0})
layout = ccui.LayoutComponent:bindLayoutComponent(num_level)
layout:setPositionPercentX(0.0402)
layout:setPositionPercentY(0.4373)
layout:setPercentWidth(0.0422)
layout:setPercentHeight(0.0639)
layout:setSize({width = 54.0000, height = 46.0000})
layout:setLeftMargin(24.5000)
layout:setRightMargin(1201.5000)
layout:setTopMargin(382.1744)
layout:setBottomMargin(291.8256)
Layer:addChild(num_level)

--Create ball
local ball = cc.Sprite:create("game/ligatureFootball/obstacle/ball.png")
ball:setName("ball")
ball:setTag(93)
ball:setCascadeColorEnabled(true)
ball:setCascadeOpacityEnabled(true)
ball:setPosition(2.4235, 3.3915)
layout = ccui.LayoutComponent:bindLayoutComponent(ball)
layout:setPositionPercentX(0.0019)
layout:setPositionPercentY(0.0047)
layout:setPercentWidth(0.0203)
layout:setPercentHeight(0.0361)
layout:setSize({width = 26.0000, height = 26.0000})
layout:setLeftMargin(-10.5765)
layout:setRightMargin(1264.5770)
layout:setTopMargin(703.6085)
layout:setBottomMargin(-9.6085)
ball:setBlendFunc({src = 1, dst = 771})
Layer:addChild(ball)

--Create touchLayer
local touchLayer = ccui.Layout:create()
touchLayer:ignoreContentAdaptWithSize(false)
touchLayer:setClippingEnabled(false)
touchLayer:setBackGroundColorOpacity(102)
touchLayer:setTouchEnabled(true);
touchLayer:setLayoutComponentEnabled(true)
touchLayer:setName("touchLayer")
touchLayer:setTag(92)
touchLayer:setCascadeColorEnabled(true)
touchLayer:setCascadeOpacityEnabled(true)
touchLayer:setPosition(0.0023, 1.8751)
layout = ccui.LayoutComponent:bindLayoutComponent(touchLayer)
layout:setPositionPercentY(0.0026)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setLeftMargin(0.0023)
layout:setRightMargin(-0.0023)
layout:setTopMargin(-1.8751)
layout:setBottomMargin(1.8751)
Layer:addChild(touchLayer)

--Create accoutLayer
local accoutLayer=cc.Node:create()
accoutLayer:setName("accoutLayer")
accoutLayer:setTag(87)
accoutLayer:setCascadeColorEnabled(true)
accoutLayer:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(accoutLayer)
layout:setRightMargin(1280.0000)
layout:setTopMargin(720.0000)
Layer:addChild(accoutLayer)

--Create btn_music_on
local btn_music_on = ccui.Button:create()
btn_music_on:ignoreContentAdaptWithSize(false)
btn_music_on:loadTextureNormal("game/ligatureFootball/gamebtn/UI_music_1.png",0)
btn_music_on:loadTexturePressed("game/ligatureFootball/gamebtn/UI_music_1.png",0)
btn_music_on:loadTextureDisabled("game/ligatureFootball/gamebtn/UI_music_1.png",0)
btn_music_on:setTitleFontSize(14)
btn_music_on:setTitleColor({r = 65, g = 65, b = 70})
btn_music_on:setLayoutComponentEnabled(true)
btn_music_on:setName("btn_music_on")
btn_music_on:setTag(88)
btn_music_on:setCascadeColorEnabled(true)
btn_music_on:setCascadeOpacityEnabled(true)
btn_music_on:setPosition(57.2206, 659.7102)
btn_music_on:setScaleX(0.6000)
btn_music_on:setScaleY(0.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_music_on)
layout:setPositionPercentX(0.0447)
layout:setPositionPercentY(0.9163)
layout:setPercentWidth(0.1305)
layout:setPercentHeight(0.2319)
layout:setSize({width = 167.0000, height = 167.0000})
layout:setLeftMargin(-26.2794)
layout:setRightMargin(1139.2790)
layout:setTopMargin(-23.2102)
layout:setBottomMargin(576.2102)
Layer:addChild(btn_music_on)

--Create btn_music_off
local btn_music_off = ccui.Button:create()
btn_music_off:ignoreContentAdaptWithSize(false)
btn_music_off:loadTextureNormal("game/ligatureFootball/gamebtn/UI_music_2.png",0)
btn_music_off:loadTexturePressed("game/ligatureFootball/gamebtn/UI_music_2.png",0)
btn_music_off:loadTextureDisabled("game/ligatureFootball/gamebtn/UI_music_2.png",0)
btn_music_off:setTitleFontSize(14)
btn_music_off:setTitleColor({r = 65, g = 65, b = 70})
btn_music_off:setLayoutComponentEnabled(true)
btn_music_off:setName("btn_music_off")
btn_music_off:setTag(89)
btn_music_off:setCascadeColorEnabled(true)
btn_music_off:setCascadeOpacityEnabled(true)
btn_music_off:setPosition(57.2206, 659.7102)
btn_music_off:setScaleX(0.6000)
btn_music_off:setScaleY(0.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_music_off)
layout:setPositionPercentX(0.0447)
layout:setPositionPercentY(0.9163)
layout:setPercentWidth(0.1305)
layout:setPercentHeight(0.2319)
layout:setSize({width = 167.0000, height = 167.0000})
layout:setLeftMargin(-26.2794)
layout:setRightMargin(1139.2790)
layout:setTopMargin(-23.2102)
layout:setBottomMargin(576.2102)
Layer:addChild(btn_music_off)

--Create btn_shoot
local btn_shoot = ccui.Button:create()
btn_shoot:ignoreContentAdaptWithSize(false)
btn_shoot:loadTextureNormal("game/ligatureFootball/gamebtn/UI_shoot.png",0)
btn_shoot:loadTexturePressed("game/ligatureFootball/gamebtn/UI_shoot.png",0)
btn_shoot:loadTextureDisabled("game/ligatureFootball/gamebtn/UI_shoot.png",0)
btn_shoot:setTitleFontSize(14)
btn_shoot:setTitleColor({r = 65, g = 65, b = 70})
btn_shoot:setScale9Enabled(true)
btn_shoot:setCapInsets({x = 15, y = 11, width = 137, height = 145})
btn_shoot:setLayoutComponentEnabled(true)
btn_shoot:setName("btn_shoot")
btn_shoot:setTag(90)
btn_shoot:setCascadeColorEnabled(true)
btn_shoot:setCascadeOpacityEnabled(true)
btn_shoot:setPosition(83.5000, 83.5000)
btn_shoot:setScaleX(0.8000)
btn_shoot:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_shoot)
layout:setPositionPercentX(0.0652)
layout:setPositionPercentY(0.1160)
layout:setPercentWidth(0.1305)
layout:setPercentHeight(0.2319)
layout:setSize({width = 167.0000, height = 167.0000})
layout:setRightMargin(1113.0000)
layout:setTopMargin(553.0000)
Layer:addChild(btn_shoot)

--Create btn_pause
local btn_pause = ccui.Button:create()
btn_pause:ignoreContentAdaptWithSize(false)
btn_pause:loadTextureNormal("game/ligatureFootball/gamebtn/UI_stopNormal.png",0)
btn_pause:loadTexturePressed("game/ligatureFootball/gamebtn/UI_stopNormal.png",0)
btn_pause:loadTextureDisabled("game/ligatureFootball/gamebtn/UI_stopNormal.png",0)
btn_pause:setTitleFontSize(14)
btn_pause:setTitleColor({r = 65, g = 65, b = 70})
btn_pause:setScale9Enabled(true)
btn_pause:setCapInsets({x = 15, y = 11, width = 124, height = 132})
btn_pause:setLayoutComponentEnabled(true)
btn_pause:setName("btn_pause")
btn_pause:setTag(91)
btn_pause:setCascadeColorEnabled(true)
btn_pause:setCascadeOpacityEnabled(true)
btn_pause:setPosition(1212.2760, 659.7837)
btn_pause:setScaleX(0.6000)
btn_pause:setScaleY(0.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_pause)
layout:setPositionPercentX(0.9471)
layout:setPositionPercentY(0.9164)
layout:setPercentWidth(0.1203)
layout:setPercentHeight(0.2139)
layout:setSize({width = 154.0000, height = 154.0000})
layout:setLeftMargin(1135.2760)
layout:setRightMargin(-9.2760)
layout:setTopMargin(-16.7837)
layout:setBottomMargin(582.7837)
Layer:addChild(btn_pause)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

