--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)
panel:setClippingEnabled(false)
panel:setBackGroundColorType(1)
panel:setBackGroundColor({r = 0, g = 0, b = 0})
panel:setBackGroundColorOpacity(153)
panel:setTouchEnabled(true);
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setTag(3030)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Layer:addChild(panel)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("common/pop_bg/bg.png",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(3031)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5289)
layout:setPercentHeight(0.6167)
layout:setSize({width = 677.0000, height = 444.0000})
layout:setLeftMargin(301.5000)
layout:setRightMargin(301.5000)
layout:setTopMargin(138.0000)
layout:setBottomMargin(138.0000)
panel:addChild(bg)

--Create img_text_rule
local img_text_rule = ccui.ImageView:create()
img_text_rule:ignoreContentAdaptWithSize(false)
img_text_rule:loadTexture("common/pop_bg/over_text.png",0)
img_text_rule:setLayoutComponentEnabled(true)
img_text_rule:setName("img_text_rule")
img_text_rule:setTag(124)
img_text_rule:setCascadeColorEnabled(true)
img_text_rule:setCascadeOpacityEnabled(true)
img_text_rule:setPosition(346.0000, 341.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img_text_rule)
layout:setPositionPercentX(0.5111)
layout:setPositionPercentY(0.7680)
layout:setPercentWidth(0.1610)
layout:setPercentHeight(0.1351)
layout:setSize({width = 109.0000, height = 60.0000})
layout:setLeftMargin(291.5000)
layout:setRightMargin(276.5000)
layout:setTopMargin(73.0000)
layout:setBottomMargin(311.0000)
bg:addChild(img_text_rule)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("over/txt_3.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(7)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(338.0000, 226.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentX(0.4993)
layout:setPositionPercentY(0.5090)
layout:setPercentWidth(0.6278)
layout:setPercentHeight(0.0698)
layout:setSize({width = 425.0000, height = 31.0000})
layout:setLeftMargin(125.5000)
layout:setRightMargin(126.5000)
layout:setTopMargin(202.5000)
layout:setBottomMargin(210.5000)
bg:addChild(Image_1)

--Create Image_1_0_0
local Image_1_0_0 = ccui.ImageView:create()
Image_1_0_0:ignoreContentAdaptWithSize(false)
Image_1_0_0:loadTexture("over/txt_1.png",0)
Image_1_0_0:setLayoutComponentEnabled(true)
Image_1_0_0:setName("Image_1_0_0")
Image_1_0_0:setTag(10)
Image_1_0_0:setCascadeColorEnabled(true)
Image_1_0_0:setCascadeOpacityEnabled(true)
Image_1_0_0:setVisible(false)
Image_1_0_0:setAnchorPoint(0.5139, 0.4194)
Image_1_0_0:setPosition(273.0000, 246.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1_0_0)
layout:setPositionPercentX(0.4032)
layout:setPositionPercentY(0.5552)
layout:setPercentWidth(0.4239)
layout:setPercentHeight(0.0698)
layout:setSize({width = 287.0000, height = 31.0000})
layout:setLeftMargin(125.5107)
layout:setRightMargin(264.4893)
layout:setTopMargin(179.5014)
layout:setBottomMargin(233.4986)
bg:addChild(Image_1_0_0)

--Create Image_1_0_0_0
local Image_1_0_0_0 = ccui.ImageView:create()
Image_1_0_0_0:ignoreContentAdaptWithSize(false)
Image_1_0_0_0:loadTexture("over/txt_2.png",0)
Image_1_0_0_0:setLayoutComponentEnabled(true)
Image_1_0_0_0:setName("Image_1_0_0_0")
Image_1_0_0_0:setTag(11)
Image_1_0_0_0:setCascadeColorEnabled(true)
Image_1_0_0_0:setCascadeOpacityEnabled(true)
Image_1_0_0_0:setVisible(false)
Image_1_0_0_0:setPosition(485.0000, 249.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1_0_0_0)
layout:setPositionPercentX(0.7164)
layout:setPositionPercentY(0.5608)
layout:setPercentWidth(0.1699)
layout:setPercentHeight(0.0698)
layout:setSize({width = 115.0000, height = 31.0000})
layout:setLeftMargin(427.5000)
layout:setRightMargin(134.5000)
layout:setTopMargin(179.5000)
layout:setBottomMargin(233.5000)
bg:addChild(Image_1_0_0_0)

--Create btnRestart
local btnRestart = ccui.Button:create()
btnRestart:ignoreContentAdaptWithSize(false)
btnRestart:loadTextureNormal("over/btnRestart.png",0)
btnRestart:setTitleFontSize(14)
btnRestart:setTitleColor({r = 65, g = 65, b = 70})
btnRestart:setLayoutComponentEnabled(true)
btnRestart:setName("btnRestart")
btnRestart:setTag(13)
btnRestart:setCascadeColorEnabled(true)
btnRestart:setCascadeOpacityEnabled(true)
btnRestart:setAnchorPoint(0.4874, 0.5317)
btnRestart:setPosition(225.0000, 96.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnRestart)
layout:setPositionPercentX(0.3323)
layout:setPositionPercentY(0.2173)
layout:setPercentWidth(0.2349)
layout:setPercentHeight(0.1419)
layout:setSize({width = 159.0000, height = 63.0000})
layout:setLeftMargin(147.5034)
layout:setRightMargin(370.4966)
layout:setTopMargin(317.9971)
layout:setBottomMargin(63.0029)
bg:addChild(btnRestart)

--Create btnHome
local btnHome = ccui.Button:create()
btnHome:ignoreContentAdaptWithSize(false)
btnHome:loadTextureNormal("over/btnExit.png",0)
btnHome:setTitleFontSize(14)
btnHome:setTitleColor({r = 65, g = 65, b = 70})
btnHome:setLayoutComponentEnabled(true)
btnHome:setName("btnHome")
btnHome:setTag(14)
btnHome:setCascadeColorEnabled(true)
btnHome:setCascadeOpacityEnabled(true)
btnHome:setAnchorPoint(0.4874, 0.5317)
btnHome:setPosition(453.0000, 96.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnHome)
layout:setPositionPercentX(0.6691)
layout:setPositionPercentY(0.2173)
layout:setPercentWidth(0.2349)
layout:setPercentHeight(0.1419)
layout:setSize({width = 159.0000, height = 63.0000})
layout:setLeftMargin(375.5034)
layout:setRightMargin(142.4966)
layout:setTopMargin(317.9971)
layout:setBottomMargin(63.0029)
bg:addChild(btnHome)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

