--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create bg_1_6
local bg_1_6 = cc.Sprite:create("game/basketball/image/bg.png")
bg_1_6:setName("bg_1_6")
bg_1_6:setTag(100)
bg_1_6:setCascadeColorEnabled(true)
bg_1_6:setCascadeOpacityEnabled(true)
bg_1_6:setPosition(640.0000, 360.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg_1_6)
layout:setPositionPercentX(0.6667)
layout:setPositionPercentY(0.5625)
layout:setPercentWidth(1.3333)
layout:setPercentHeight(1.1250)
layout:setSize({width = 1280.0000, height = 720.0000})
layout:setRightMargin(-320.0000)
layout:setTopMargin(-80.0000)
bg_1_6:setFlippedX(true)
bg_1_6:setBlendFunc({src = 1, dst = 771})
Scene:addChild(bg_1_6)

--Create role_1
local role_1 = cc.Sprite:create("game/basketball/image/role.png")
role_1:setName("role_1")
role_1:setTag(100)
role_1:setCascadeColorEnabled(true)
role_1:setCascadeOpacityEnabled(true)
role_1:setAnchorPoint(0.5000, 0.0000)
role_1:setPosition(457.0700, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(role_1)
layout:setPositionPercentX(0.4761)
layout:setPercentWidth(0.3021)
layout:setPercentHeight(1.0391)
layout:setSize({width = 290.0000, height = 665.0000})
layout:setLeftMargin(312.0700)
layout:setRightMargin(357.9300)
layout:setTopMargin(-25.0000)
role_1:setBlendFunc({src = 1, dst = 771})
Scene:addChild(role_1)

--Create began
local began = ccui.Button:create()
began:ignoreContentAdaptWithSize(false)
began:loadTextureNormal("game/basketball/image/hall_btn.png",0)
began:setTitleFontSize(14)
began:setTitleColor({r = 65, g = 65, b = 70})
began:setLayoutComponentEnabled(true)
began:setName("began")
began:setTag(94)
began:setCascadeColorEnabled(true)
began:setCascadeOpacityEnabled(true)
began:setPosition(761.4097, 435.2962)
layout = ccui.LayoutComponent:bindLayoutComponent(began)
layout:setPositionPercentX(0.7931)
layout:setPositionPercentY(0.6802)
layout:setPercentWidth(0.2719)
layout:setPercentHeight(0.2063)
layout:setSize({width = 261.0000, height = 132.0000})
layout:setLeftMargin(630.9097)
layout:setRightMargin(68.0903)
layout:setTopMargin(138.7038)
layout:setBottomMargin(369.2962)
Scene:addChild(began)

--Create Text_3
local Text_3 = ccui.Text:create()
Text_3:ignoreContentAdaptWithSize(true)
Text_3:setTextAreaSize({width = 0, height = 0})
Text_3:setFontName("game/basketball/image/FZY3JW.TTF")
Text_3:setFontSize(48)
Text_3:setString([[play]])
Text_3:setLayoutComponentEnabled(true)
Text_3:setName("Text_3")
Text_3:setTag(81)
Text_3:setCascadeColorEnabled(true)
Text_3:setCascadeOpacityEnabled(true)
Text_3:setPosition(126.5721, 67.9643)
Text_3:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_3)
layout:setPositionPercentX(0.4850)
layout:setPositionPercentY(0.5149)
layout:setPercentWidth(0.3372)
layout:setPercentHeight(0.4242)
layout:setSize({width = 88.0000, height = 56.0000})
layout:setLeftMargin(82.5721)
layout:setRightMargin(90.4279)
layout:setTopMargin(36.0357)
layout:setBottomMargin(39.9643)
began:addChild(Text_3)

--Create help
local help = ccui.Button:create()
help:ignoreContentAdaptWithSize(false)
help:loadTextureNormal("game/basketball/image/hall_btn.png",0)
help:setTitleFontSize(14)
help:setTitleColor({r = 65, g = 65, b = 70})
help:setLayoutComponentEnabled(true)
help:setName("help")
help:setTag(95)
help:setCascadeColorEnabled(true)
help:setCascadeOpacityEnabled(true)
help:setPosition(761.4097, 253.2962)
layout = ccui.LayoutComponent:bindLayoutComponent(help)
layout:setPositionPercentX(0.7931)
layout:setPositionPercentY(0.3958)
layout:setPercentWidth(0.2719)
layout:setPercentHeight(0.2063)
layout:setSize({width = 261.0000, height = 132.0000})
layout:setLeftMargin(630.9097)
layout:setRightMargin(68.0903)
layout:setTopMargin(320.7038)
layout:setBottomMargin(187.2962)
Scene:addChild(help)

--Create Text_3_0
local Text_3_0 = ccui.Text:create()
Text_3_0:ignoreContentAdaptWithSize(true)
Text_3_0:setTextAreaSize({width = 0, height = 0})
Text_3_0:setFontName("game/basketball/image/FZY3JW.TTF")
Text_3_0:setFontSize(48)
Text_3_0:setString([[rule]])
Text_3_0:setLayoutComponentEnabled(true)
Text_3_0:setName("Text_3_0")
Text_3_0:setTag(82)
Text_3_0:setCascadeColorEnabled(true)
Text_3_0:setCascadeOpacityEnabled(true)
Text_3_0:setPosition(132.6204, 66.8530)
Text_3_0:setTextColor({r = 26, g = 26, b = 26})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_3_0)
layout:setPositionPercentX(0.5081)
layout:setPositionPercentY(0.5065)
layout:setPercentWidth(0.2989)
layout:setPercentHeight(0.4242)
layout:setSize({width = 78.0000, height = 56.0000})
layout:setLeftMargin(93.6204)
layout:setRightMargin(89.3796)
layout:setTopMargin(37.1470)
layout:setBottomMargin(38.8530)
help:addChild(Text_3_0)

--Create Image_5
local Image_5 = ccui.ImageView:create()
Image_5:ignoreContentAdaptWithSize(false)
Image_5:loadTexture("game/basketball/image/lanwang.png",0)
Image_5:setFlippedX(true)
Image_5:setLayoutComponentEnabled(true)
Image_5:setName("Image_5")
Image_5:setTag(23)
Image_5:setCascadeColorEnabled(true)
Image_5:setCascadeOpacityEnabled(true)
Image_5:setPosition(935.0000, 482.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_5)
layout:setPositionPercentX(0.9740)
layout:setPositionPercentY(0.7531)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.1250)
layout:setSize({width = 100.0000, height = 80.0000})
layout:setLeftMargin(885.0000)
layout:setRightMargin(-25.0000)
layout:setTopMargin(118.0000)
layout:setBottomMargin(442.0000)
Scene:addChild(Image_5)

--Create Image_8
local Image_8 = ccui.ImageView:create()
Image_8:ignoreContentAdaptWithSize(false)
Image_8:loadTexture("game/basketball/image/lankuanghou.png",0)
Image_8:setFlippedX(true)
Image_8:setLayoutComponentEnabled(true)
Image_8:setName("Image_8")
Image_8:setTag(105)
Image_8:setCascadeColorEnabled(true)
Image_8:setCascadeOpacityEnabled(true)
Image_8:setPosition(933.0000, 518.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_8)
layout:setPositionPercentX(0.9719)
layout:setPositionPercentY(0.8094)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.0313)
layout:setSize({width = 100.0000, height = 20.0000})
layout:setLeftMargin(883.0000)
layout:setRightMargin(-23.0000)
layout:setTopMargin(112.0000)
layout:setBottomMargin(508.0000)
Scene:addChild(Image_8)

--Create Image_10
local Image_10 = ccui.ImageView:create()
Image_10:ignoreContentAdaptWithSize(false)
Image_10:loadTexture("game/basketball/image/lankuangqian .png",0)
Image_10:setFlippedX(true)
Image_10:setLayoutComponentEnabled(true)
Image_10:setName("Image_10")
Image_10:setTag(106)
Image_10:setCascadeColorEnabled(true)
Image_10:setCascadeOpacityEnabled(true)
Image_10:setPosition(934.0000, 506.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_10)
layout:setPositionPercentX(0.9729)
layout:setPositionPercentY(0.7906)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.0313)
layout:setSize({width = 100.0000, height = 20.0000})
layout:setLeftMargin(884.0000)
layout:setRightMargin(-24.0000)
layout:setTopMargin(124.0000)
layout:setBottomMargin(496.0000)
Scene:addChild(Image_10)

--Create basketball_7
local basketball_7 = cc.Sprite:create("game/basketball/image/ball.png")
basketball_7:setName("basketball_7")
basketball_7:setTag(101)
basketball_7:setCascadeColorEnabled(true)
basketball_7:setCascadeOpacityEnabled(true)
basketball_7:setPosition(927.5000, 538.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(basketball_7)
layout:setPositionPercentX(0.9661)
layout:setPositionPercentY(0.8406)
layout:setPercentWidth(0.0438)
layout:setPercentHeight(0.0641)
layout:setSize({width = 42.0000, height = 41.0000})
layout:setLeftMargin(906.5000)
layout:setRightMargin(11.5000)
layout:setTopMargin(81.5000)
layout:setBottomMargin(517.5000)
basketball_7:setBlendFunc({src = 1, dst = 771})
Scene:addChild(basketball_7)

--Create best
local best = ccui.Text:create()
best:ignoreContentAdaptWithSize(true)
best:setTextAreaSize({width = 0, height = 0})
best:setFontName("game/basketball/image/FZY3JW.TTF")
best:setFontSize(45)
best:setString([[BEST:1000]])
best:setLayoutComponentEnabled(true)
best:setName("best")
best:setTag(111)
best:setCascadeColorEnabled(true)
best:setCascadeOpacityEnabled(true)
best:setPosition(819.0000, 650.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(best)
layout:setPositionPercentX(0.8531)
layout:setPositionPercentY(1.0156)
layout:setPercentWidth(0.2344)
layout:setPercentHeight(0.0828)
layout:setSize({width = 225.0000, height = 53.0000})
layout:setLeftMargin(706.5000)
layout:setRightMargin(28.5000)
layout:setTopMargin(-36.5000)
layout:setBottomMargin(623.5000)
Scene:addChild(best)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

