--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create gamepnl
local gamepnl = ccui.Layout:create()
gamepnl:ignoreContentAdaptWithSize(false)
gamepnl:setClippingEnabled(false)
gamepnl:setBackGroundColorOpacity(102)
gamepnl:setTouchEnabled(true);
gamepnl:setLayoutComponentEnabled(true)
gamepnl:setName("gamepnl")
gamepnl:setTag(26)
gamepnl:setCascadeColorEnabled(true)
gamepnl:setCascadeOpacityEnabled(true)
gamepnl:setPosition(20.0000, 363.0848)
layout = ccui.LayoutComponent:bindLayoutComponent(gamepnl)
layout:setPositionPercentX(0.0278)
layout:setPositionPercentY(0.2837)
layout:setPercentWidth(0.9444)
layout:setPercentHeight(0.4375)
layout:setSize({width = 680.0000, height = 560.0000})
layout:setLeftMargin(20.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(356.9152)
layout:setBottomMargin(363.0848)
Layer:addChild(gamepnl)

--Create img_bg
local img_bg = ccui.ImageView:create()
img_bg:ignoreContentAdaptWithSize(false)
img_bg:loadTexture("game/niuniutiaozhan/images/border/gameover.png",0)
img_bg:setLayoutComponentEnabled(true)
img_bg:setName("img_bg")
img_bg:setTag(31)
img_bg:setCascadeColorEnabled(true)
img_bg:setCascadeOpacityEnabled(true)
img_bg:setPosition(344.6401, 280.8383)
layout = ccui.LayoutComponent:bindLayoutComponent(img_bg)
layout:setPositionPercentX(0.5068)
layout:setPositionPercentY(0.5015)
layout:setPercentWidth(0.9691)
layout:setPercentHeight(0.9804)
layout:setSize({width = 659.0000, height = 549.0000})
layout:setLeftMargin(15.1401)
layout:setRightMargin(5.8599)
layout:setTopMargin(4.6617)
layout:setBottomMargin(6.3383)
gamepnl:addChild(img_bg)

--Create img_score
local img_score = ccui.ImageView:create()
img_score:ignoreContentAdaptWithSize(false)
img_score:loadTexture("game/niuniutiaozhan/images/img_txts/score.png",0)
img_score:setLayoutComponentEnabled(true)
img_score:setName("img_score")
img_score:setTag(27)
img_score:setCascadeColorEnabled(true)
img_score:setCascadeOpacityEnabled(true)
img_score:setPosition(342.3341, 360.9393)
layout = ccui.LayoutComponent:bindLayoutComponent(img_score)
layout:setPositionPercentX(0.5034)
layout:setPositionPercentY(0.6445)
layout:setPercentWidth(0.4662)
layout:setPercentHeight(0.2054)
layout:setSize({width = 317.0000, height = 115.0000})
layout:setLeftMargin(183.8341)
layout:setRightMargin(179.1659)
layout:setTopMargin(141.5607)
layout:setBottomMargin(303.4393)
gamepnl:addChild(img_score)

--Create label_score
local label_score = ccui.Text:create()
label_score:ignoreContentAdaptWithSize(true)
label_score:setTextAreaSize({width = 0, height = 0})
label_score:setFontSize(60)
label_score:setString([[0]])
label_score:setLayoutComponentEnabled(true)
label_score:setName("label_score")
label_score:setTag(33)
label_score:setCascadeColorEnabled(true)
label_score:setCascadeOpacityEnabled(true)
label_score:setPosition(400.0859, 364.9395)
layout = ccui.LayoutComponent:bindLayoutComponent(label_score)
layout:setPositionPercentX(0.5884)
layout:setPositionPercentY(0.6517)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.1214)
layout:setSize({width = 34.0000, height = 68.0000})
layout:setLeftMargin(383.0859)
layout:setRightMargin(262.9141)
layout:setTopMargin(161.0605)
layout:setBottomMargin(330.9395)
gamepnl:addChild(label_score)

--Create img_hit
local img_hit = ccui.ImageView:create()
img_hit:ignoreContentAdaptWithSize(false)
img_hit:loadTexture("game/niuniutiaozhan/images/img_txts/Hit.png",0)
img_hit:setLayoutComponentEnabled(true)
img_hit:setName("img_hit")
img_hit:setTag(29)
img_hit:setCascadeColorEnabled(true)
img_hit:setCascadeOpacityEnabled(true)
img_hit:setPosition(342.3341, 218.8274)
layout = ccui.LayoutComponent:bindLayoutComponent(img_hit)
layout:setPositionPercentX(0.5034)
layout:setPositionPercentY(0.3908)
layout:setPercentWidth(0.4662)
layout:setPercentHeight(0.2054)
layout:setSize({width = 317.0000, height = 115.0000})
layout:setLeftMargin(183.8341)
layout:setRightMargin(179.1659)
layout:setTopMargin(283.6726)
layout:setBottomMargin(161.3274)
gamepnl:addChild(img_hit)

--Create label_hit
local label_hit = ccui.Text:create()
label_hit:ignoreContentAdaptWithSize(true)
label_hit:setTextAreaSize({width = 0, height = 0})
label_hit:setFontSize(60)
label_hit:setString([[0]])
label_hit:setLayoutComponentEnabled(true)
label_hit:setName("label_hit")
label_hit:setTag(34)
label_hit:setCascadeColorEnabled(true)
label_hit:setCascadeOpacityEnabled(true)
label_hit:setPosition(400.0859, 222.8275)
layout = ccui.LayoutComponent:bindLayoutComponent(label_hit)
layout:setPositionPercentX(0.5884)
layout:setPositionPercentY(0.3979)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.1214)
layout:setSize({width = 34.0000, height = 68.0000})
layout:setLeftMargin(383.0859)
layout:setRightMargin(262.9141)
layout:setTopMargin(303.1725)
layout:setBottomMargin(188.8275)
gamepnl:addChild(label_hit)

--Create backhome
local backhome = ccui.Button:create()
backhome:ignoreContentAdaptWithSize(false)
backhome:loadTextureNormal("game/niuniutiaozhan/images/btns/backhome.png",0)
backhome:setTitleFontSize(14)
backhome:setTitleColor({r = 65, g = 65, b = 70})
backhome:setScale9Enabled(true)
backhome:setCapInsets({x = 15, y = 11, width = 208, height = 64})
backhome:setLayoutComponentEnabled(true)
backhome:setName("backhome")
backhome:setTag(33)
backhome:setCascadeColorEnabled(true)
backhome:setCascadeOpacityEnabled(true)
backhome:setPosition(488.0515, 96.4725)
if callBackProvider~=nil then
      backhome:addClickEventListener(callBackProvider("balance.lua", backhome, "onBackHome"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(backhome)
layout:setPositionPercentX(0.7177)
layout:setPositionPercentY(0.1723)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.1536)
layout:setSize({width = 238.0000, height = 86.0000})
layout:setLeftMargin(369.0515)
layout:setRightMargin(72.9485)
layout:setTopMargin(420.5275)
layout:setBottomMargin(53.4725)
gamepnl:addChild(backhome)

--Create restart
local restart = ccui.Button:create()
restart:ignoreContentAdaptWithSize(false)
restart:loadTextureNormal("game/niuniutiaozhan/images/btns/restart.png",0)
restart:setTitleFontSize(14)
restart:setTitleColor({r = 65, g = 65, b = 70})
restart:setScale9Enabled(true)
restart:setCapInsets({x = 15, y = 11, width = 208, height = 64})
restart:setLayoutComponentEnabled(true)
restart:setName("restart")
restart:setTag(32)
restart:setCascadeColorEnabled(true)
restart:setCascadeOpacityEnabled(true)
restart:setPosition(201.0356, 96.4725)
if callBackProvider~=nil then
      restart:addClickEventListener(callBackProvider("balance.lua", restart, "onRestart"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(restart)
layout:setPositionPercentX(0.2956)
layout:setPositionPercentY(0.1723)
layout:setPercentWidth(0.3500)
layout:setPercentHeight(0.1536)
layout:setSize({width = 238.0000, height = 86.0000})
layout:setLeftMargin(82.0356)
layout:setRightMargin(359.9644)
layout:setTopMargin(420.5275)
layout:setBottomMargin(53.4725)
gamepnl:addChild(restart)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

