--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create pageview
local pageview = ccui.PageView:create()
pageview:ignoreContentAdaptWithSize(false)
pageview:setClippingEnabled(false)
pageview:setBackGroundColorOpacity(102)
pageview:setLayoutComponentEnabled(true)
pageview:setName("pageview")
pageview:setTag(31)
pageview:setCascadeColorEnabled(true)
pageview:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(pageview)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
Layer:addChild(pageview)

--Create page1
local page1 = ccui.Layout:create()
page1:ignoreContentAdaptWithSize(false)
page1:setClippingEnabled(false)
page1:setBackGroundColorOpacity(102)
page1:setTouchEnabled(true);
page1:setLayoutComponentEnabled(true)
page1:setName("page1")
page1:setTag(32)
page1:setCascadeColorEnabled(true)
page1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(page1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
pageview:addPage(page1)

--Create img
local img = ccui.ImageView:create()
img:ignoreContentAdaptWithSize(false)
img:loadTexture("game/niuniutiaozhan/images/upmodel/upmodel_eye.png",0)
img:setLayoutComponentEnabled(true)
img:setName("img")
img:setTag(38)
img:setCascadeColorEnabled(true)
img:setCascadeOpacityEnabled(true)
img:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
page1:addChild(img)

--Create startGame
local startGame = ccui.Button:create()
startGame:ignoreContentAdaptWithSize(false)
startGame:loadTextureNormal("game/niuniutiaozhan/images/btns/startgame.png",0)
startGame:setTitleFontSize(14)
startGame:setTitleColor({r = 65, g = 65, b = 70})
startGame:setScale9Enabled(true)
startGame:setCapInsets({x = 15, y = 11, width = 208, height = 64})
startGame:setLayoutComponentEnabled(true)
startGame:setName("startGame")
startGame:setTag(2)
startGame:setCascadeColorEnabled(true)
startGame:setCascadeOpacityEnabled(true)
startGame:setPosition(360.0000, 419.4396)
if callBackProvider~=nil then
      startGame:addClickEventListener(callBackProvider("upmodel.lua", startGame, "onStartGame"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(startGame)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3277)
layout:setPercentWidth(0.3306)
layout:setPercentHeight(0.0672)
layout:setSize({width = 238.0000, height = 86.0000})
layout:setLeftMargin(241.0000)
layout:setRightMargin(241.0000)
layout:setTopMargin(817.5604)
layout:setBottomMargin(376.4396)
page1:addChild(startGame)

--Create page2
local page2 = ccui.Layout:create()
page2:ignoreContentAdaptWithSize(false)
page2:setClippingEnabled(false)
page2:setBackGroundColorOpacity(102)
page2:setTouchEnabled(true);
page2:setLayoutComponentEnabled(true)
page2:setName("page2")
page2:setLocalZOrder(1)
page2:setTag(33)
page2:setCascadeColorEnabled(true)
page2:setCascadeOpacityEnabled(true)
page2:setPosition(720.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(page2)
layout:setPositionPercentX(0.2500)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setLeftMargin(720.0000)
layout:setRightMargin(1440.0000)
pageview:addPage(page2)

--Create img
local img = ccui.ImageView:create()
img:ignoreContentAdaptWithSize(false)
img:loadTexture("game/niuniutiaozhan/images/upmodel/upmodel_highscore.png",0)
img:setLayoutComponentEnabled(true)
img:setName("img")
img:setTag(34)
img:setCascadeColorEnabled(true)
img:setCascadeOpacityEnabled(true)
img:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
page2:addChild(img)

--Create startGame
local startGame = ccui.Button:create()
startGame:ignoreContentAdaptWithSize(false)
startGame:loadTextureNormal("game/niuniutiaozhan/images/btns/startgame.png",0)
startGame:setTitleFontSize(14)
startGame:setTitleColor({r = 65, g = 65, b = 70})
startGame:setScale9Enabled(true)
startGame:setCapInsets({x = 15, y = 11, width = 208, height = 64})
startGame:setLayoutComponentEnabled(true)
startGame:setName("startGame")
startGame:setTag(3)
startGame:setCascadeColorEnabled(true)
startGame:setCascadeOpacityEnabled(true)
startGame:setPosition(360.0000, 419.4396)
if callBackProvider~=nil then
      startGame:addClickEventListener(callBackProvider("upmodel.lua", startGame, "onStartGame"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(startGame)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3277)
layout:setPercentWidth(0.3306)
layout:setPercentHeight(0.0672)
layout:setSize({width = 238.0000, height = 86.0000})
layout:setLeftMargin(241.0000)
layout:setRightMargin(241.0000)
layout:setTopMargin(817.5604)
layout:setBottomMargin(376.4396)
page2:addChild(startGame)

--Create page3
local page3 = ccui.Layout:create()
page3:ignoreContentAdaptWithSize(false)
page3:setClippingEnabled(false)
page3:setBackGroundColorOpacity(102)
page3:setTouchEnabled(true);
page3:setLayoutComponentEnabled(true)
page3:setName("page3")
page3:setLocalZOrder(2)
page3:setTag(36)
page3:setCascadeColorEnabled(true)
page3:setCascadeOpacityEnabled(true)
page3:setPosition(1440.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(page3)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setLeftMargin(1440.0000)
layout:setRightMargin(720.0000)
pageview:addPage(page3)

--Create img
local img = ccui.ImageView:create()
img:ignoreContentAdaptWithSize(false)
img:loadTexture("game/niuniutiaozhan/images/upmodel/upmodel_nomistake.png",0)
img:setLayoutComponentEnabled(true)
img:setName("img")
img:setTag(37)
img:setCascadeColorEnabled(true)
img:setCascadeOpacityEnabled(true)
img:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
page3:addChild(img)

--Create startGame
local startGame = ccui.Button:create()
startGame:ignoreContentAdaptWithSize(false)
startGame:loadTextureNormal("game/niuniutiaozhan/images/btns/startgame.png",0)
startGame:setTitleFontSize(14)
startGame:setTitleColor({r = 65, g = 65, b = 70})
startGame:setScale9Enabled(true)
startGame:setCapInsets({x = 15, y = 11, width = 208, height = 64})
startGame:setLayoutComponentEnabled(true)
startGame:setName("startGame")
startGame:setTag(4)
startGame:setCascadeColorEnabled(true)
startGame:setCascadeOpacityEnabled(true)
startGame:setPosition(360.0000, 419.4396)
if callBackProvider~=nil then
      startGame:addClickEventListener(callBackProvider("upmodel.lua", startGame, "onStartGame"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(startGame)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3277)
layout:setPercentWidth(0.3306)
layout:setPercentHeight(0.0672)
layout:setSize({width = 238.0000, height = 86.0000})
layout:setLeftMargin(241.0000)
layout:setRightMargin(241.0000)
layout:setTopMargin(817.5604)
layout:setBottomMargin(376.4396)
page3:addChild(startGame)

--Create page4
local page4 = ccui.Layout:create()
page4:ignoreContentAdaptWithSize(false)
page4:setClippingEnabled(false)
page4:setBackGroundColorOpacity(102)
page4:setTouchEnabled(true);
page4:setLayoutComponentEnabled(true)
page4:setName("page4")
page4:setLocalZOrder(3)
page4:setTag(39)
page4:setCascadeColorEnabled(true)
page4:setCascadeOpacityEnabled(true)
page4:setPosition(2160.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(page4)
layout:setPositionPercentX(0.7500)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setLeftMargin(2160.0000)
pageview:addPage(page4)

--Create img
local img = ccui.ImageView:create()
img:ignoreContentAdaptWithSize(false)
img:loadTexture("game/niuniutiaozhan/images/upmodel/upmodel_showtime.png",0)
img:setLayoutComponentEnabled(true)
img:setName("img")
img:setTag(40)
img:setCascadeColorEnabled(true)
img:setCascadeOpacityEnabled(true)
img:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(img)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
page4:addChild(img)

--Create startGame
local startGame = ccui.Button:create()
startGame:ignoreContentAdaptWithSize(false)
startGame:loadTextureNormal("game/niuniutiaozhan/images/btns/startgame.png",0)
startGame:setTitleFontSize(14)
startGame:setTitleColor({r = 65, g = 65, b = 70})
startGame:setScale9Enabled(true)
startGame:setCapInsets({x = 15, y = 11, width = 208, height = 64})
startGame:setLayoutComponentEnabled(true)
startGame:setName("startGame")
startGame:setTag(5)
startGame:setCascadeColorEnabled(true)
startGame:setCascadeOpacityEnabled(true)
startGame:setPosition(360.0000, 419.4396)
if callBackProvider~=nil then
      startGame:addClickEventListener(callBackProvider("upmodel.lua", startGame, "onStartGame"))
end
layout = ccui.LayoutComponent:bindLayoutComponent(startGame)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.3277)
layout:setPercentWidth(0.3306)
layout:setPercentHeight(0.0672)
layout:setSize({width = 238.0000, height = 86.0000})
layout:setLeftMargin(241.0000)
layout:setRightMargin(241.0000)
layout:setTopMargin(817.5604)
layout:setBottomMargin(376.4396)
page4:addChild(startGame)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

