--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1280.0000, height = 720.0000})

--Create shade
local shade = ccui.Layout:create()
shade:ignoreContentAdaptWithSize(false)
shade:setClippingEnabled(false)
shade:setBackGroundColorType(1)
shade:setBackGroundColor({r = 0, g = 0, b = 0})
shade:setBackGroundColorOpacity(102)
shade:setTouchEnabled(true);
shade:setLayoutComponentEnabled(true)
shade:setName("shade")
shade:setTag(67)
shade:setCascadeColorEnabled(true)
shade:setCascadeOpacityEnabled(true)
shade:setAnchorPoint(0.5000, 0.5000)
shade:setPosition(612.2023, 408.9962)
layout = ccui.LayoutComponent:bindLayoutComponent(shade)
layout:setPositionPercentX(0.4783)
layout:setPositionPercentY(0.5681)
layout:setPercentWidth(1.5625)
layout:setPercentHeight(2.0833)
layout:setSize({width = 2000.0000, height = 1500.0000})
layout:setLeftMargin(-387.7977)
layout:setRightMargin(-332.2023)
layout:setTopMargin(-438.9962)
layout:setBottomMargin(-341.0038)
Layer:addChild(shade)

--Create winBg_1
local winBg_1 = cc.Sprite:create("game/DiamondMemory/ui/winBg.png")
winBg_1:setName("winBg_1")
winBg_1:setTag(94)
winBg_1:setCascadeColorEnabled(true)
winBg_1:setCascadeOpacityEnabled(true)
winBg_1:setPosition(642.8160, 475.9200)
layout = ccui.LayoutComponent:bindLayoutComponent(winBg_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5022)
layout:setPositionPercentY(0.6610)
layout:setPercentWidth(0.4445)
layout:setPercentHeight(0.3722)
layout:setSize({width = 569.0000, height = 268.0000})
layout:setLeftMargin(358.3160)
layout:setRightMargin(352.6840)
layout:setTopMargin(110.0800)
layout:setBottomMargin(341.9200)
winBg_1:setBlendFunc({src = 1, dst = 771})
Layer:addChild(winBg_1)

--Create levelText
local levelText = ccui.Text:create()
levelText:ignoreContentAdaptWithSize(true)
levelText:setTextAreaSize({width = 0, height = 0})
levelText:setFontName("game/DiamondMemory/ui/FZY3JW.TTF")
levelText:setFontSize(72)
levelText:setString([[1]])
levelText:setLayoutComponentEnabled(true)
levelText:setName("levelText")
levelText:setTag(95)
levelText:setCascadeColorEnabled(true)
levelText:setCascadeOpacityEnabled(true)
levelText:setAnchorPoint(0.0000, 0.5000)
levelText:setPosition(731.1360, 289.1339)
levelText:setTextColor({r = 239, g = 255, b = 211})
layout = ccui.LayoutComponent:bindLayoutComponent(levelText)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5712)
layout:setPositionPercentY(0.4016)
layout:setPercentWidth(0.0273)
layout:setPercentHeight(0.1167)
layout:setSize({width = 35.0000, height = 84.0000})
layout:setLeftMargin(731.1360)
layout:setRightMargin(513.8640)
layout:setTopMargin(388.8661)
layout:setBottomMargin(247.1339)
Layer:addChild(levelText)

--Create winText
local winText = ccui.Text:create()
winText:ignoreContentAdaptWithSize(true)
winText:setTextAreaSize({width = 0, height = 0})
winText:setFontName("game/DiamondMemory/ui/FZY3JW.TTF")
winText:setFontSize(72)
winText:setString([[LEVEL:]])
winText:setLayoutComponentEnabled(true)
winText:setName("winText")
winText:setTag(74)
winText:setCascadeColorEnabled(true)
winText:setCascadeOpacityEnabled(true)
winText:setPosition(611.5840, 291.1774)
winText:setTextColor({r = 239, g = 255, b = 211})
layout = ccui.LayoutComponent:bindLayoutComponent(winText)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.4778)
layout:setPositionPercentY(0.4044)
layout:setPercentWidth(0.1484)
layout:setPercentHeight(0.1167)
layout:setSize({width = 190.0000, height = 84.0000})
layout:setLeftMargin(516.5840)
layout:setRightMargin(573.4160)
layout:setTopMargin(386.8226)
layout:setBottomMargin(249.1774)
Layer:addChild(winText)

--Create againBtn
local againBtn = ccui.Button:create()
againBtn:ignoreContentAdaptWithSize(false)
againBtn:loadTextureNormal("game/DiamondMemory/ui/btn.png",0)
againBtn:setTitleFontName("game/DiamondMemory/ui/FZY3JW.TTF")
againBtn:setTitleFontSize(30)
againBtn:setTitleText("Restart")
againBtn:setTitleColor({r = 65, g = 65, b = 70})
againBtn:setLayoutComponentEnabled(true)
againBtn:setName("againBtn")
againBtn:setTag(74)
againBtn:setCascadeColorEnabled(true)
againBtn:setCascadeOpacityEnabled(true)
againBtn:setPosition(786.3040, 163.4400)
againBtn:setScaleX(1.3000)
againBtn:setScaleY(1.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(againBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.6143)
layout:setPositionPercentY(0.2270)
layout:setPercentWidth(0.1367)
layout:setPercentHeight(0.0972)
layout:setSize({width = 175.0000, height = 70.0000})
layout:setLeftMargin(698.8040)
layout:setRightMargin(406.1960)
layout:setTopMargin(521.5600)
layout:setBottomMargin(128.4400)
Layer:addChild(againBtn)

--Create mainBtn
local mainBtn = ccui.Button:create()
mainBtn:ignoreContentAdaptWithSize(false)
mainBtn:loadTextureNormal("game/DiamondMemory/ui/btn.png",0)
mainBtn:setTitleFontName("game/DiamondMemory/ui/FZY3JW.TTF")
mainBtn:setTitleFontSize(30)
mainBtn:setTitleText("Exit")
mainBtn:setTitleColor({r = 65, g = 65, b = 70})
mainBtn:setLayoutComponentEnabled(true)
mainBtn:setName("mainBtn")
mainBtn:setTag(66)
mainBtn:setCascadeColorEnabled(true)
mainBtn:setCascadeOpacityEnabled(true)
mainBtn:setPosition(508.2880, 163.4400)
mainBtn:setScaleX(1.3000)
mainBtn:setScaleY(1.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(mainBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3971)
layout:setPositionPercentY(0.2270)
layout:setPercentWidth(0.1367)
layout:setPercentHeight(0.0972)
layout:setSize({width = 175.0000, height = 70.0000})
layout:setLeftMargin(420.7880)
layout:setRightMargin(684.2120)
layout:setTopMargin(521.5600)
layout:setBottomMargin(128.4400)
Layer:addChild(mainBtn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

